CREATE TABLE collector_cdc_config
(
    config_id           VARCHAR(50) NOT NULL,
    name                VARCHAR(50) NOT NULL,
    table_name          VARCHAR(50) NOT NULL,
    model_name          VARCHAR(50) NOT NULL,
    parent_name         VARCHAR(50),
    join_key            JSON,
    disabled            TINYINT,
	filter_criteria     VARCHAR(50),
	dependency          VARCHAR(50),
	triggered           TINYINT,
	audit_column        VARCHAR(50),
    data_source_id      VARCHAR(50) NOT NULL,
    is_list             TINYINT,
    tenant_id           VARCHAR(50) NOT NULL,
    created_at          DATETIME    NOT NULL,
    created_by          VARCHAR(50) NOT NULL,
    last_modified_at    DATETIME    NOT NULL,
    last_modified_by    VARCHAR(50) NOT NULL,
    version             BIGINT,
    PRIMARY KEY (config_id),
    UNIQUE KEY unique_name(name),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);