[tool.poetry]
name = "watchmen-rest-reactor"
version = "16.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_rest_reactor", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
watchmen-rest = { path = "../watchmen-rest", develop = true }
watchmen-reactor-service = { path = "../watchmen-reactor-service", develop = true }
watchmen-storage-mysql = { path = "../watchmen-storage-mysql", develop = true, optional = true }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
