global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: watchmen_doll
    metrics_path: /metrics
    static_configs:
      - targets: ['watchmen_doll:8000']

  - job_name: localstack
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets: ['localstack:4566']
