CREATE TABLE collector_table_config
(
    config_id           VARCHAR(50)     NOT NULL,
    name                VARCHAR(50)     NOT NULL,
    table_name          VARCHAR(50)     NOT NULL,
    primary_key         JSON            NOT NULL,
    object_key          VARCHAR(50),
    sequence_key        VARCHAR(50),
    model_name          VARCHAR(50)     NOT NULL,
    parent_name         VARCHAR(50),
    label               VARCHAR(50),
    join_keys           JSON,
	depend_on           JSON,
	audit_column        VARCHAR(50)     NOT NULL,
	conditions          JSON,
    data_source_id      VARCHAR(50)     NOT NULL,
    is_list             TINYINT         NOT NULL,
    triggered           TINYINT         NOT NULL,
    version             BIGINT,
    tenant_id           VARCHAR(50)     NOT NULL,
    created_at          DATETIME        NOT NULL,
    created_by          VARCHAR(50)     NOT NULL,
    last_modified_at    DATETIME        NOT NULL,
    last_modified_by    VARCHAR(50)     NOT NULL,
    PRIMARY KEY (config_id),
    UNIQUE KEY unique_name(name),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);