import React from 'react';
import {LanguageDeclareType} from './types';

export const VI: LanguageDeclareType = {
	$$settings: {
		code: 'vi',
		name: 'Tiếng Anh',
		fallback: ''
	},
	// fix key, anything under PLAIN will not be proxy to other type
	// anything must be string, should be placed here.
	// such as input tooltip(string property), tuple name(not for react component)
	PLAIN: {
		CONSOLE_SEARCH_PLACEHOLDER: 'Tìm kiếm không gian kết nối, đối tượng, báo cáo và bảng điều khiển',
		NEW_DASHBOARD_NAME: 'Bảng điều khiển',
		DEFAULT_DASHBOARD_NAME: 'Bảng điều khiển',
		NEW_CONNECTED_SPACE_NAME: 'Không gian kết nối',
		DEFAULT_CONNECTED_SPACE_NAME: 'Không gian kết nối',
		NEW_SUBJECT_NAME: 'Đối tượng',
		DEFAULT_SUBJECT_NAME: 'Đối tượng',
		NEW_REPORT_NAME: 'Báo cáo',
		DEFAULT_REPORT_NAME: 'Báo cáo',
		CONSTANT_INPUT_PLACEHOLDER: 'Nhâp Giá trị không đổi tại đây...',
		UNKNOWN_TOPIC_NAME: 'Chủ đề không xác định',
		UNKNOWN_FACTOR_NAME: 'Yếu tố không xác định',
		REPORT_DESCRIPTION_PLACEHOLDER: 'Nhập mô tả tại đây',
		LOADING: 'Loading...',
		FIND_INDICATOR_PLACEHOLDER: 'Tìm bởi chỉ báo, mô tả',
		FIND_TOPIC_OR_FACTOR_OR_SUBJECT_PLACEHOLDER: 'Tìm bởi tên chủ đề, yếu tố, đối tượng',
		INDICATOR_NAME_PLACEHOLDER: 'Chỉ báo tên người',
		INDICATOR_DESCRIPTION_PLACEHOLDER: 'Mô tả chỉ báo tại đây...',
		FIND_BUCKET_PLACEHOLDER: 'Tìm bởi tên bucket, mô tả',
		BUCKET_CATEGORY_SEGMENT_VALUE_PLACEHOLDER: 'Nhập giá trị danh mục tại đây, xác nhận để thêm vào phần này.',
		FIND_INDICATOR_VALUE_BUCKETS_PLACEHOLDER: 'Tìm kiếm bởi tên bucket.',
		FIND_OBJECTIVE_PLACEHOLDER: 'Tìm kiếm bởi tên đối tượng, mô tả',
		FIND_CONVERGENCE_PLACEHOLDER: 'Tìm kiếm theo tên hội tụ, mô tả',
		FIND_DATA_STORY_PLACEHOLDER: 'Tìm kiếm theo tên câu chuyện dữ liệu, mô tả',
		OBJECTIVE_NAME_PLACEHOLDER: 'Đối tượng tên người',
		OBJECTIVE_DESCRIPTION_PLACEHOLDER: 'Mô tả đối tượng tại đây...',
		OBJECTIVE_VARIABLE_NAME_PLACEHOLDER: 'Tên biến.',
		OBJECTIVE_FACTOR_NAME_PLACEHOLDER: 'Tên chỉ báo',
		OBJECTIVE_FORMULA_CONSTANT_PLACEHOLDER: 'Sử dụng "{}" để bao gồm biến.',
		OBJECTIVE_FACTOR_FILTER_CONSTANT_PLACEHOLDER: 'Sử dụng "{}" để  bao gồm biến.',
		SUBSCRIBE_MAIL_ADDRESS_PLACEHOLDER: '";" để phân cách nhiều địa chỉ.',
		NEW_DERIVED_OBJECTIVE_NAME: 'Mục tiêu',
		DEFAULT_DERIVED_OBJECTIVE_NAME: 'Mục tiêu',
		NEW_DERIVED_OBJECTIVE_TARGET_BREAKDOWN_NAME: 'Phân tích chi tiết',
		CONVERGENCE_NAME_PLACEHOLDER: 'Tên để đọc đối với hội tụ việc trên, từ thuật ngữ.',
		CONVERGENCE_DESCRIPTION_PLACEHOLDER: 'Mô tả về sự hội tụ ở đây...',
		CONVERGENCE_FREEWALK_VALUE_PLACEHOLDER: 'Phân tách bằng dấu chấm phẩy ";"'
	},
	STANDARD: {
		YES: 'Có',
		NO: 'Không'
	},
	ERROR: {
		UNAUTHORIZED: 'Không có quyền truy cập, vui lòng đăng nhập',
		ACCESS_DENIED: 'Từ chối truy cập, vui lòng liên hệ Admin để biết thêm chi tiết.',
		UNPREDICTED: 'Có lỗi xảy ra, vui lòng liên hệ Admin để biết thêm chi tiết.'
	},
	ALERT: {
		BUTTON: 'Đã hiểu',
		NOT_IMPLEMENT: 'Chưa được thực hiện.'
	},
	DIALOG: {
		BUTTON_YES: 'Có',
		BUTTON_NO: 'Không'
	},
	ACTIONS: {
		SAVE: 'Lưu',
		COPY: 'Sao lưu',
		CLOSE: 'Đóng',
		CANCEL: 'Huỷ',
		DELETE: 'Xoá',
		REMOVE: 'Loại bỏ',
		CONFIRM: 'Xác nhận',
		NEXT: 'Tiếp',
		SORT_ASC: 'Thứ tự tăng lên',
		SORT_DESC: 'Thứ tự giảm dần',
		PREVIOUS_PAGE: 'Trang trước',
		NEXT_PAGE: 'Trang sau',
		EXPAND: 'Mở rộng',
		COLLAPSE: 'Ghép',
		MINIMIZE: 'Thu nhỏ',
		MAXIMIZE: 'Phóng to',
		RESTORE: 'Lưu trữ',
		SUBSCRIBE: 'Đăng ký'
	},
	LOGIN: {
		PRODUCT_TITLE: <>Indexical Metrics <span>&</span> Measure Advisory</>,
		MORNING: 'Chào buổi sáng !',
		AFTERNOON: 'Chào buổi chiều!',
		EVENING: 'Chào buổi tối !',
		BUTTON: 'Bắt đầu !',
		NAME_EMPTY: 'Hãy nói cho tôi biết bạn là ai.',
		CREDENTIAL_EMPTY: 'Bạn cần được xác thực trước khi bắt đầu.',
		FAIL: 'Không xác thực được.'
	},
	ADMIN: {
		UNKNOWN_USER_GROUP: 'Nhóm người dùng không xác định',
		NONAME_USER_GROUP: 'Nhóm người dùng không tên'
	},
	DATASET: {
		UNFIX_COLUMN: 'Bỏ cố định và tiếp tục',
		FIX_COLUMN: 'Cố định cột tại đây',
		COMPRESS_COLUMNS: 'Nén cột',
		DOWNLOAD_PAGE: 'Xoá trang này',
		DOWNLOAD_ALL: 'Xoá tất cả',
		SIMULATE_DATA: 'Mô phỏng',
		UPLOAD_DATA: 'Tải số liệu',
		UPLOAD_DATA_FAILURE: 'Nhập tệp số liệu thất bại, kiểm tra lại định dạng của tệp.',
		DOWNLOAD_TEMPLATE: 'Tải mẫu'
	},
	CONSOLE: {
		LOADING: 'Đang tải số liệu cá nhân...',
		BYE: 'Dừng tại đây?',
		ERROR: {
			DASHBOARD_NOT_FOUND: 'Không tìm thấy bảng điều khiển này.',
			CONNECTED_SPACE_NOT_FOUND: 'Không tìm thấy không gian kết nối này.',
			DERIVED_OBJECTIVE_NOT_FOUND: 'Không tìm thấy mục tiêu.',
			SUBJECT_NOT_FOUND: 'Không tìm thấy đối tượng này.',
			REPORT_NOT_FOUND: 'Không tìm thấy báo cáo này.'
		},
		MENU: {
			TITLE: 'Watchmen Console',
			HOME: 'Trang chủ',
			DASHBOARDS: 'Bảng điều khiển',
			FAVORITE: 'Hiện mục yêu thích',
			CONNECT_SPACE: 'Không gian kết nối',
			SETTINGS: 'Cài đặt',
			TO_CONSOLE: 'Điều khiển',
			TO_ADMIN: 'Quản trị',
			TO_DATA_QUALITY: 'Tới trung tâm chất lượng số liệu',
			TO_INDICATOR: 'Tới chỉ báo',
			LOGOUT: 'Đăng xuất'
		},
		FAVORITE: {
			TITLE: 'Mục yêu thích của tôi',
			NO_DATA: 'Không có mục yêu thích',
			PIN: 'Ghim',
			UNPIN: 'Bỏ ghim'
		},
		HOME: {
			TITLE: 'Trang chủ',
			SORT_BY_NAME: 'Phân loại Theo tên',
			SORT_BY_VISIT_TIME: 'Phân loại Theo thời gian ghé trang',
			VIEW_COLLAPSE: 'Ghép',
			VIEW_ALL: 'Xem tất cả',
			CONNECTED_SPACE_TITLE: 'Không gian truy cập gần đây',
			CREATE_CONNECTED_SPACE_BUTTON: 'Kết nối không gian',
			DERIVED_OBJECTIVE_TITLE: 'Mục tiêu gần đây',
			CREATE_DERIVED_OBJECTIVE_BUTTON: 'Tạo mục tiêu',
			DASHBOARD_TITLE: 'Bảng điều khiển gần đây',
			CREATE_DASHBOARD_BUTTON: 'Tạo bảng điều khiển',
			NO_RECENT: 'Không sử dụng gần đây.'
		},
		DASHBOARD: {
			SHARE: 'Chia sẻ',
			PRINT: 'In',
			REFRESH: 'Tải lại',
			AUTO_REFRESH: 'Tải lại tự động (5 Phút)',
			ADD_INTO_FAVORITE: 'Thêm vào mục yêu thích',
			REMOVE_FROM_FAVORITE: 'Bỏ khỏi mục kiêu thích',
			ADD_REPORT: 'Thêm báo cáo',
			ADD_PARAGRAPH: 'Thêm đoạn',
			ADD_DASHBOARD: 'Thêm bảng điều khiển',
			SWITCH_DASHBOARD: 'Đổi bảng điều khiển',
			DELETE_ME: 'Xoá',
			SHARE_DIALOG_LABEL: 'Sao chép liên kết này, và chia sẻ tới nơi bạn muốn chia sẻ',
			URL_COPIED: 'Đã sao chép liên kết.',
			DELETE_DIALOG_LABEL: 'Bạn có chắc chắn muốn xoá bảng điều khiển này? Xin lưu ý bạn không thể khôi phục lại sau khi xoá.',
			NO_MORE_DASHBOARD: 'Không có bảng điều khiển.',
			SWITCH_DIALOG_LABEL: 'Hãy chọn bảng điều khiển',
			NO_MORE_REPORT: 'Không có báo cáo nào.',
			DELETE_REPORT_DIALOG_LABEL: 'Bạn có chắc chắn muốn xoá báo cáo này? Xin lưu ý bạn không thể khôi phục lại sau khi xoá.',
			DELETE_PARAGRAPH_DIALOG_LABEL: 'Bạn có chắc chắn muốn xoá đoạn này? Hãy lưu ý rằng bạn không thể khôi phục lại sau khi xoá.',
			NO_REPORT: 'Không có báo cáo.',
			SHOW_PRINT_PAGE: 'Hiển thị cỡ trang',
			HIDE_PRINT_PAGE: 'Ẩn cỡ trang',
			SET_AS_ADMIN_HOME: 'Cài đặt làm trang chủ',
			FUNNEL_TITLE: 'Phễu'
		},
		CONNECTED_SPACE: {
			CATALOG: 'Cẩm nang',
			SUBJECT_DEF: 'Định nghĩa',
			SUBJECT_DATA: 'Tệp số liệu',
			SUBJECT_REPORTS: 'Báo cáo',
			SUBJECT_REPORT: 'Báo cáo',
			REPORT_DATA: 'Tệp số liệu',
			REPORT_FILTER: 'Lọc',
			REPORT_FUNNEL: 'Phễu',
			SHARE: 'Chia sẻ',
			ADD_REPORT: 'Thêm báo cáo',
			ADD_SUBJECT: 'Thêm đối tượng',
			COPILOT: 'Phi công phụ',
			OPEN_SUBJECT: 'Mở đối tượng',
			ADD_CONNECTED_SPACE: 'Kết nối không gian',
			SWITCH_CONNECTED_SPACE: 'Tráo đổi không gian',
			DELETE_ME: 'Xoá',
			ADD_INTO_FAVORITE: 'Thêm vào mục yêu thích',
			REMOVE_FROM_FAVORITE: 'Bỏ khỏi mục yêu thích',
			SET_AS_TEMPLATE: 'Cài đặt thành mẫu',
			REMOVE_FROM_TEMPLATE: 'Xoá khỏi mẫu',
			DELETE_DIALOG_LABEL: 'Bạn có chắc chắn muốn xoá không gian kết nối? Hãy lưu ý rằng bạn không thể khôi phục lại sau khi xoá.',
			NO_MORE_CONNECTED_SPACE: 'Không còn không gian kết nối.',
			SWITCH_DIALOG_LABEL: 'Hãy chọn không gian kết nối',
			CREATE_DIALOG_LABEL: 'Hãy chọn không gian kết nối hiện có',
			CREATE_DIALOG_CHOOSE_TEMPLATE_LABEL: 'Hãy chọn mẫu yêu thích',
			TEMPLATE: 'Mẫu',
			TEMPLATE_CREATE_BY: 'Tạo bởi',
			NO_MORE_SPACE: 'Không tổn tại không gian, vui lòng liên hệ Admin để biết thêm chi tiết.',
			SPACE_NOT_FOUND: 'Không tổn tại định nghĩa không gian, vui lòng liên hệ Admin để biết thêm chi tiết.',
			TOPICS_NOT_FOUND: 'Không tổn tại định nghĩa không gian, vui lòng liên hệ Admin để biết thêm chi tiết.',
			TOPICS_COUNT_MISMATCH: 'Không khớp chủ đề, vui lòng liên hệ Admin để biết thêm chi tiết.',
			TOPIC_WITH_NO_FACTOR: 'Không tìm thấy yếu tố, vui lòng liên hệ Admin để biết thêm chi tiết.',
			DELETE_SUBJECT_DIALOG_LABEL: 'Bạn có chắc chắn muốn xoá chủ đề? Hãy lưu ý rằng bạn không thể khôi phục lại sau khi xoá.',
			SWITCH_SUBJECT: 'Đổi chủ đề',
			SWITCH_SUBJECT_DIALOG_LABEL: 'Hãy chọn chủ đề',
			NO_MORE_SUBJECT: 'Không còn tồn tại chủ đề',
			SUBJECT_DEF_INVALID: 'Định nghĩa chủ đề không đúng, vui lòng sửa lại',
			SUBJECT_PICK_TOPICS: 'Chọn chủ đề',
			SUBJECT_DEFINE_COLUMNS: 'Định nghĩa cột',
			SUBJECT_FILTER_DATA: 'Lọc số liệu',
			SUBJECT_SET_JOINS: 'Cài đặt Joins',
			SUBJECT_DEF_OVERVIEW: 'Overview',
			NO_PICKED_TOPIC_FOR_SUBJECT: 'Chưa có chủ đề nào được chọn.',
			NO_DATASET_COLUMN_FOR_SUBJECT: 'Chưa định nghĩa cột, bạn có muốn ',
			CREATE_DATASET_COLUMN_WHEN_NONE: 'Tạo',
			NO_DATASET_COLUMN_FOR_SUBJECT_2: '?',
			ALIAS: 'As',
			SUBJECT_COLUMN_ARITHMETIC: 'Gộp',
			SUBJECT_COLUMN_ARITHMETIC_NONE: 'Giữ nguyên',
			SUBJECT_COLUMN_ARITHMETIC_COUNT: 'Đếm',
			SUBJECT_COLUMN_ARITHMETIC_DISTINCT_COUNT: 'Đếm khác nhau',
			SUBJECT_COLUMN_ARITHMETIC_SUMMARY: 'Tổng',
			SUBJECT_COLUMN_ARITHMETIC_AVERAGE: 'Bình quân',
			SUBJECT_COLUMN_ARITHMETIC_MAX: 'Lớn nhất',
			SUBJECT_COLUMN_ARITHMETIC_MIN: 'Nhỏ nhất',
			SUBJECT_COLUMN_RENDERER_ALIGNMENT: 'Căn lề',
			SUBJECT_COLUMN_RENDERER_ALIGNMENT_LEFT: 'Trái',
			SUBJECT_COLUMN_RENDERER_ALIGNMENT_CENTER: 'Giữa',
			SUBJECT_COLUMN_RENDERER_ALIGNMENT_RIGHT: 'Phải',
			SUBJECT_COLUMN_RENDERER_FORMAT: 'Định dạng',
			SUBJECT_COLUMN_RENDERER_FORMAT_NONE: 'Giữ nguyên',
			SUBJECT_COLUMN_RENDERER_HIGHLIGHT_NEGATIVE: 'Làm nổi bật số âm',
			SUBJECT_COLUMN_POSITION_ALREADY_AT_FIRST: 'Không thể rời lên trên vì đã ở trên cùng',
			SUBJECT_COLUMN_POSITION_ALREADY_AT_LAST: 'Không thể rời xuống dưới vì đã ở dưới cùng',
			ADD_SUBJECT_COLUMN: 'Thêm cột',
			ADD_SUBJECT_RECALCULATE_COLUMN: 'Thêm cột tính lại',
			CAN_NOT_DELETE_CHILD_FROM_COMPUTED: 'Không thể xoá vì chạm tới tham số nhỏ nhất',
			CAN_NOT_ADD_CHILD_INTO_COMPUTED: 'Không thể thêm vì chạm tới tham số lớn nhất.',
			ADD_COMPUTE_PARAMETER: 'Thêm tham số',
			NO_DATASET_FILTER_FOR_SUBJECT: 'Chưa định nghĩa bọ lọc, bạn có muốn',
			CREATE_DATASET_FILTER_WHEN_NONE: 'Tạo',
			NO_DATASET_FILTER_FOR_SUBJECT_2: '?',
			ADD_SUB_EXPRESSION_FILTER: 'Thêm Sub Expression',
			ADD_SUB_JOINT_FILTER: 'Thêm Sub Joint',
			NO_DATASET_JOIN_FOR_SUBJECT: 'Không có định nghĩa join nào, bạn có muốn ',
			CREATE_DATASET_JOIN_WHEN_NONE: 'Tạo',
			NO_DATASET_JOIN_FOR_SUBJECT_2: '?',
			ADD_SUBJECT_JOIN: 'Thêm Join',
			SUBJECT_SELECT: 'Chọn',
			SUBJECT_NO_SELECT: 'Chưa cột nào được định nghĩa',
			SUBJECT_FROM: 'Từ',
			SUBJECT_NO_FROM: 'Không có join được định nghĩa.',
			SUBJECT_JOIN_INNER: 'Trong Join',
			SUBJECT_JOIN_LEFT: 'Join trái',
			SUBJECT_JOIN_RIGHT: 'Join phải',
			SUBJECT_JOIN_ON: 'Trên',
			SUBJECT_JOIN_EQUALS: '=',
			SUBJECT_JOIN_AND: 'và',
			SUBJECT_WHERE: 'Tại',
			SUBJECT_NO_WHERE: 'Chưa định nghĩa bộ lọc.',
			SUBJECT_UNKNOWN_PARAMETER: 'Tham số không xác định',
			SUBJECT_EMPTY_CONSTANT: 'Giá trị bất biến trống',
			SUBJECT_COLUMN_AS: 'Là',
			SUBJECT_NO_ALIAS: '?',
			SUBJECT_FILTER_JOINT_NO_STATEMENT: 'Không Statement in Joint',
			SUBJECT_UNKNOWN_FILTER: 'Bộ lọc chưa xác định',
			NO_DATASET_COLUMN: 'Chưa có cột nào được định nghĩa.',
			NO_REPORT: 'Không có báo cáo được định nghĩa, ban có muốn ',
			CREATE_REPORT: 'Tạo',
			NO_REPORT_2: '?',
			NO_MORE_REPORT: 'Không có báo cáo',
			OPEN_REPORT: 'Mở báo cáo',
			SWITCH_REPORT: 'Trao đổi báo cáo',
			SWITCH_REPORT_DIALOG_LABEL: 'Vui lòng chọn báo cáo',
			DELETE_REPORT_DIALOG_LABEL: 'Bạn có chắc chắn muốn xoá báo cáo? Hãy lưu ý rằng bạn không thể khôi phục lại sau khi xoá.',
			COLLAPSE_REPORT_SETTINGS_SECTIONS: 'Lồng tất cả các phần',
			EXPAND_REPORT_SETTINGS_SECTIONS: 'Mở rộng tất cả các phần',
			REPORT_NO_FILTER: 'Không có bộ lọc được định nghĩa, bạn có muốn ',
			CREATE_REPORT_FILTER: 'Tạo',
			REPORT_NO_FILTER_2: '?',
			REPORT_NO_FUNNEL: 'Không có phễu.'
		},
		DERIVED_OBJECTIVE: {
			CREATE_DIALOG_CHOOSE_TEMPLATE_LABEL: 'Vui lòng chọn mục tiêu yêu thích',
			TEMPLATE: 'Mục tiêu',
			NO_MORE_OBJECTIVE: 'Không có mục tiêu nào tồn tại, vui lòng liên hệ với người quản trị để biết thêm thông tin.',
			NO_OBJECTIVE_SELECTED: 'Không có mục tiêu nào được chọn.',
			ADD_INTO_FAVORITE: 'Thêm vào Yêu thích',
			REMOVE_FROM_FAVORITE: 'Xóa khỏi Yêu thích',
			ADD_DERIVED_OBJECTIVE: 'Tạo Mục tiêu',
			SWITCH_DERIVED_OBJECTIVE: 'Chuyển đổi Mục tiêu',
			SWITCH_DIALOG_LABEL: 'Vui lòng chọn mục tiêu',
			DELETE_DIALOG_LABEL: 'Bạn có chắc chắn muốn xóa mục tiêu không? Lưu ý rằng hành động này không thể phục hồi.',
			DELETE_ME: 'Xóa Tôi',
			REFRESH_VALUES: 'Làm mới',
			SHOW_VARIABLES: 'Hiển thị Biến số',
			HIDE_VARIABLES: 'Ẩn Biến số',
			UNKNOWN_TARGET_NAME: 'Mục tiêu không xác định',
			VARIABLES_TITLE: 'Biến số Tiêu chí',
			UNKNOWN_VARIABLE_NAME: 'Biến số không xác định',
			TIME_FRAME_TITLE: 'Khung thời gian',
			NOT_TIME_RELATED: 'Mục tiêu không liên quan đến thời gian.',
			TIME_FRAME_KIND_YEAR: 'Hàng năm',
			TIME_FRAME_KIND_HALF_YEAR: 'Mỗi nửa năm',
			TIME_FRAME_KIND_QUARTER: 'Hàng quý',
			TIME_FRAME_KIND_MONTH: 'Hàng tháng',
			TIME_FRAME_KIND_WEEK_OF_YEAR: 'Hàng tuần',
			TIME_FRAME_KIND_DAY_OF_MONTH: 'Hàng ngày, của tháng',
			TIME_FRAME_KIND_DAY_OF_WEEK: 'Hàng ngày, của tuần',
			TIME_FRAME_KIND_LAST_N_YEARS: 'Năm gần đây',
			TIME_FRAME_KIND_LAST_N_MONTHS: 'Tháng gần đây',
			TIME_FRAME_KIND_LAST_N_WEEKS: 'Tuần gần đây',
			TIME_FRAME_KIND_LAST_N_DAYS: 'Ngày gần đây',
			BREAKDOWN: 'Phân tích chi tiết',
			HIDE_BREAKDOWN: 'Ẩn phân tích chi tiết',
			ADD_BREAKDOWN: 'Thêm phân tích chi tiết',
			REMOVE_BREAKDOWN: 'Xóa phân tích chi tiết',
			DIMENSION_ON_INDICATOR_VALUE: 'Trên Giá trị Mục tiêu',
			ADD_FIRST_BREAKDOWN_DIMENSION: 'Thêm chiều đầu tiên',
			ADD_BREAKDOWN_DIMENSION: 'Thêm chiều',
			VALUE_AS_DIMENSION: 'Sử dụng Phân loại Tự nhiên',
			ASK_BREAKDOWN_VALUES: 'Lấy Giá trị',
			BREAKDOWN_NO_DIMENSION: 'Không có chiều được khai báo.',
			FAILED_ON_FETCH_BREAKDOWN_VALUES: 'Không thành công trong việc lấy giá trị.',
			NO_DATA_FETCHED_BREAKDOWN_VALUES: 'Không có dữ liệu.',
			SHARE: 'Chia sẻ',
			PRINT: 'In',
			SHARE_DIALOG_LABEL: 'Sao chép URL sau và chia sẻ nơi bạn muốn.',
			URL_COPIED: 'URL đã được sao chép.'
		}
	},
	INDICATOR: {
		MENU: {
			TITLE: 'Chỉ bro Watchmen',
			BUCKETS: 'Buckets',
			INDICATORS: 'Chỉ báo',
			OBJECTIVES: 'Đối tượng',
			CONVERGENCES: 'Hội tụ',
			SETTINGS: 'Cài đặt',
			STORY: 'Câu chuyện',
			LOGOUT: 'Đăng xuất'
		},
		ON_EDIT: 'Bạn đang sửa, tất cả thay đổi sẽ không được lưu lại nếu bị gián đoạn. Bạn có chắc chắn muốn tiếp tục?',
		STEP: 'Bước',
		INDICATOR: {
			LIST_TITLE: 'Chỉ báo',
			LIST_CREATE_INDICATOR: 'Định nghĩa chỉ báo',
			LIST_LABEL: 'Chỉ báo',
			NEW_INDICATOR_PREFIX: 'Mới',
			EXISTING_INDICATOR_PREFIX: 'Có sẵn',
			CREATE_AT: 'Tạo tại',
			LAST_MODIFIED_AT: 'Lần cuối chỉnh sửa',
			TITLE: 'Định nghĩa chỉ báo',
			WAIT_INPUT: 'Đợi nhập...',
			SEARCHING: 'Tìm...',
			NO_MATCHED: 'Không có số liệu khớp...',
			OR: 'hoặc',
			CREATE_INDICATOR: 'Định nghĩa mới',
			FIND_INDICATOR: 'Tìm đã có',
			DISCARD_FIND_INDICATOR: 'Bỏ tìm kiếm',
			ON_CREATE_INDICATOR: 'Định nghĩa 1 chỉ báo',
			ON_VIEW_INDICATOR: 'Xem chỉ báo',
			RESTART: 'Khởi động lại',
			BACK_TO_LIST: 'Quay lại danh sách',
			PICK_TOPIC_OR_SUBJECT: 'Tìm chủ đề',
			DEFINE_ON_TOPIC: 'Tìm chủ đề',
			DEFINE_ON_SUBJECT: 'Định nghĩa chủ đề',
			INDICATOR_ON_TOPIC: 'Trong chủ đề',
			INDICATOR_ON_SUBJECT: 'Trong chủ đề',
			FAILED_TO_LOAD_INDICATOR: 'Tải chỉ báo thất bại, vui lòng liên hệ Admin để biết thêm chi tiết.',
			AGGREGATE_ITEM_TITLE: 'Chọn một chức năng.',
			MEASURE_METHODS_TITLE: 'Thước đo có sẵn cho chỉ báo này được tìm thấy tự động.',
			FACTOR: 'Yếu tố',
			FACTOR_NAME: 'Tên',
			FACTOR_LABEL: 'Mác',
			FACTOR_TYPE: 'Loại',
			FACTOR_ENUM: 'Đếm',
			GEO: 'GEO',
			TIME_PERIOD: 'Khoảng thời gian',
			INDIVIDUAL: 'Cá nhân',
			ORGANIZATION: 'Tổ chức',
			CATEGORY: 'Phân loại',
			DEFINE_BUCKETS_TITLE: 'Buckets được định nghĩa sẵn để phân loại dễ dàng hơn',
			INDICATOR_VALUE_BUCKET_ONLY_ON_FACTOR_LABEL: 'Giá trị bucket có sẵn cho từng chỉ báo yếu tố',
			INDICATOR_VALUE_BUCKET_LABEL: 'Giá trị chỉ báo bucketing',
			LINK_INDICATOR_VALUE_BUCKETS: 'Liên kết được định nghĩa giá trị Buckets với giá trị chỉ báo',
			DISCARD_LINK_INDICATOR_VALUE_BUCKETS: 'Bỏ link',
			MEASURE_BUCKET_LABEL: 'Đo bucketing',
			NO_MEASURE_BUCKET: 'Không có thước đo bucket.',
			VIEW_MEASURE_BUCKETS: 'Xem Buckets đã đo được định nghĩa sẵn',
			IGNORE_DEFINE_BUCKETS: 'Bỏ qua định nghĩa Buckets',
			CHANGE_NAME: 'Thay đổi tên',
			NOT_NOW: 'Lúc khác',
			SAVE_INDICATOR: 'Lưu chỉ báo',
			SAVE_NAME: 'Lưu tên',
			REQUIRE_INDICATOR_NAME: 'Tên của chỉ báo được yêu cầu.',
			RELEVANT_TITLE: 'Chỉ báo có liên quan của chỉ báo hiện tại có thể được tìm thấy tự động',
			INDICATOR_NAME: 'Chỉ báo',
			INDICATOR_RELEVANT_TYPE: 'Loại liên quan',
			IRRELEVANT: 'Không liên quan',
			NO_RELEVANT_DETECTED: 'Không có chỉ báo nào có liên quan được tìm thấy.',
			DETECT_RELEVANT: 'Tìm chỉ báo tiềm năng',
			IGNORE_DETECT_RELEVANT: 'Bỏ qua',
			FILTERS_ON_TOPIC: 'Hạn chế số liệu.',
			FILTERS_ON_SUBJECT: 'Hạn chế số liệu đã được định nghĩa trong chủ đề và không gian, sẽ được quy định bởi chỉ báo.',
			CATEGORIES_TITLE: 'Phan loại.',
			DESCRIPTION_TITLE: 'Mô tả.',
			LAST_STEP_TITLE: 'Chỉ báo đã sẵn sàng',
			PREPARE_ANOTHER: 'Định nghĩa một cái khác'
		},
		BUCKET: {
			TITLE: 'Buckets',
			LABEL: 'Bucket',
			NEW_BUCKET_PREFIX: 'Mới',
			EXISTING_BUCKET_PREFIX: 'Có sẵn',
			CREATE_BUCKET: 'Tạo Bucket',
			NAME_LABEL: 'Tên Bucket:',
			TYPE_LABEL: 'Loại Bucket:',
			TYPE_IS_FIXED_ONCE_SAVE: 'Loại Bucket không thể thay đổi sau khi lưu.',
			DESCRIPTION_LABEL: 'Mô tả:',
			CREATE_AT: 'Tạo tại',
			LAST_MODIFIED_AT: 'Ngày sửa gần nhất',
			BUCKET_NAME_IS_REQUIRED: 'Tên người được yêu cầu.',
			BUCKET_MEASURE_IS_REQUIRED: 'Vui lòng chọn phương thức đo.',
			BUCKET_ENUM_IS_REQUIRED: 'Vui lòng chọn kiểu dữ liệu.',
			BUCKET_SEGMENTS_IS_REQUIRED: 'Ít nhất hai phần chưa được định nghĩa',
			BUCKET_SEGMENT_NAME_IS_REQUIRED: 'Tên người được yêu cầu',
			BE_NUMERIC_OF_NUMERIC_SEGMENT: 'Giá trị phải là dạng số',
			EMPTY_FIRST_MIN_OF_NUMERIC_SEGMENT: 'Giá trị nhỏ nhất của phần đầu tiên không được để trống.',
			NOT_EMPTY_FIRST_MAX_OF_NUMERIC_SEGMENT: 'Giá trị lớn nhất của phần đầu tiên không được để trống.',
			NOT_EMPTY_OF_NUMERIC_SEGMENT: 'Giá trị của phần ở giữa không được để trống.',
			MIN_MAX_ORDER_OF_NUMERIC_SEGMENT: 'Giá trị nhỏ nhất không được nhỏ hơn giá trị lớn nhất.',
			NOT_EMPTY_LAST_MIN_OF_NUMERIC_SEGMENT: 'Giá trị nhỏ nhất của phần cuối phải để trống.',
			EMPTY_LAST_MAX_OF_NUMERIC_SEGMENT: 'Giá trị lớn nhất của phần cuối phải để trống.',
			RANGE_LACK_EXISTS_OF_NUMERIC_SEGMENT: 'Có thiếu khoảng.',
			RANGE_OVERLAP_EXISTS_OF_NUMERIC_SEGMENT: 'Có khoảng chồng chéo.',
			NOT_EMPTY_OF_CATEGORY_SEGMENT: 'Cần định nghĩa ít nhất một loại.',
			NO_DUPLICATED_OF_CATEGORY_SEGMENT: 'Không thể định nghĩa loại trùng lặp trong một phần.',
			ONE_OTHERS_SEGMENT_OF_CATEGORY_SEGMENT: 'Chỉ một phần có thể chứa loại "Khác".',
			ONE_OTHERS_VALUE_OF_CATEGORY_SEGMENT: 'Chỉ có một loại "Khác" trong phần.',
			NO_SHARED_OF_CATEGORY_SEGMENT: 'Không thể định nghĩa cùng loại trong nhiều phần.',
			NO_SEGMENT_DEFINED: 'Không có phần được định nghĩa',
			ONE_SEGMENT_DEFINED: '1 Phần',
			N_SEGMENT_DEFINED: 'Các phần',
			BUCKET_TYPE_VALUE: 'Giá trị',
			BUCKET_TYPE_VALUE_MEASURE: 'Giá trị đo',
			BUCKET_TYPE_CATEGORY_MEASURE: 'Loại đo',
			BUCKET_TYPE_ENUM_MEASURE: 'Đo Enumeration',
			RANGE_INCLUDING_LABEL: 'Giá trị Inclusion Mode:',
			RANGE_INCLUDE_MIN: '[Gồm giá trị nhỏ nhất, Không gồm giá trị lớn nhất)',
			RANGE_INCLUDE_MAX: '(Không gồm giá trị lớn nhất, Gồm Giá trị lớn nhất]',
			SEGMENTS_LABEL: 'Phần:',
			SEGMENT_NAME: 'Tên phần',
			VALUE_SEGMENT_MIN_LABEL: 'Giá trị nhỏ nhất',
			VALUE_SEGMENT_MAX_LABEL: 'Giá trị lớn nhất',
			ADD_SEGMENT: 'Thêm phần',
			SORT_SEGMENTS: 'Phân loại phần',
			MEASURE_METHOD_LABEL: 'Phương pháp đo',
			MEASURE_METHOD_IS_FIXED_ONCE_SAVE: 'Phương pháp đo không thể thay đổi sau khi lưu.',
			CATEGORY_SEGMENT_LABEL: 'Giá trị phân loại',
			DUPLICATE_CATEGORY_SEGMENT_VALUE: 'Loại này đã tồn tại trong phần.',
			DUPLICATE_CATEGORY_SEGMENT_VALUE_CASE_IGNORED: 'Loại này đã tồn tại trong phần này, bạn có chắc chắn muốn thêm?',
			OTHERS_IS_EXCLUSIVE_ON_CATEGORY_SEGMENT: 'Loại "khác" đã tồn tại trong phần này, bạn có chắc chắn muốn thêm.',
			NO_SEGMENT_VALUE_DEFINED: 'Không có giá trị được định nghĩa',
			ADD_OTHER_CATEGORY: 'Thêm phần cho Khác',
			ENUM_LABEL: 'Enumeration:',
			ENUM_IS_FIXED_ONCE_SAVE: 'Enumeration không thể thay đổi sau khi lưu.',
			SORT_SEGMENTS_BY_CODE: 'Phân loại phần bằng mã',
			SORT_SEGMENTS_BY_NAME: 'Phân loại phần bằng tên',
			AVAILABLE_ENUM_ITEMS_LABEL: 'Enumeration Items có sẵn:',
			NO_AVAILABLE_ENUM_ITEMS: 'Không có items nào.',
			ADD_AVAILABLE_ITEMS_INTO_SEGMENT: 'Thêm vào phần',
			SEGMENT_LABEL: 'Phần',
			PLEASE_SELECT_SEGMENT: 'Vui lòng chọn một phần để thêm enumeration items này.',
			PLEASE_SELECT_ENUM_ITEM: 'Vui lòng chọn ít nhất một enumeration item để thêm vào phần.'
		},
		OBJECTIVE: {
			LIST_TITLE: 'Mục tiêu',
			LIST_CREATE_OBJECTIVE: 'Định nghĩa mục tiêu',
			LIST_LABEL: 'Mục tiêu',
			NEW_OBJECTIVE_PREFIX: 'Mới',
			EXISTING_OBJECTIVE_PREFIX: 'Có sẵn',
			CREATE_AT: 'Tạo lúc',
			LAST_MODIFIED_AT: 'Lần sửa gần nhất lúc',
			TITLE: 'Định nghĩa mục tiêu',
			FAILED_TO_LOAD_OBJECTIVE: 'Tải mục tiêu thất bại, vui lòng liên hệ Admin để biết thêm chi tiết.',
			TARGETS_TITLE: 'Khai báo giá trị mục tiêu định lượng.',
			BACK_TO_LIST: 'Quay lại danh sách',
			TARGET_NAME: ':',
			TARGET_TOBE: 'Để trở thành giá trị:',
			TARGET_TOBE_PLACEHOLDER: 'Giá trị số hoặc giá trị phần trăm (kết thúc bằng %).',
			TARGET_ASIS: 'Như là giá trị:',
			TARGET_ASIS_REFER: 'Tham khảo',
			TARGET_ASIS_COMPUTED: 'Tính toán',
			TARGET_BETTER_SIDE: 'Giá trị tốt hơn:',
			TARGET_BETTER_SIDE_MORE: 'Nhiều hơn là tốt hơn',
			TARGET_BETTER_SIDE_LESS: 'Ít hơn là tốt hơn',
			TARGET_ASK_PREVIOUS_CYCLE: 'Bao gồm chu kỳ trước (ví dụ: hàng tháng)?',
			TARGET_ASK_CHAIN_CYCLE: 'Bao gồm chu kỳ chuỗi (ví dụ: hàng năm)?',
			TARGET_VALUES: 'Giá trị:',
			TARGET_CURRENT_VALUE: 'Hiện tại',
			TARGET_PREVIOUS_VALUE: 'Trước đó',
			TARGET_CHAIN_VALUE: 'Chuỗi',
			TARGET_FINISH_RATE: 'Tỷ lệ',
			ADD_TARGET: 'Thêm mục tiêu mới',
			TARGET_CONSANGUINITY: 'Consanguinity',
			TIME_FRAME_TITLE: 'Đặt khung thời gian.',
			TIME_FRAME_KIND: 'Loại:',
			TIME_FRAME_KIND_NONE: 'Không liên quan đến khung thời gian',
			TIME_FRAME_KIND_YEAR: 'Năm',
			TIME_FRAME_KIND_HALF_YEAR: 'Nửa năm',
			TIME_FRAME_KIND_QUARTER: 'Quý',
			TIME_FRAME_KIND_MONTH: 'Tháng',
			TIME_FRAME_KIND_WEEK_OF_YEAR: 'Tuần',
			TIME_FRAME_KIND_DAY_OF_MONTH: 'Ngày, Của tháng',
			TIME_FRAME_KIND_DAY_OF_WEEK: 'Ngày, Của tuần',
			TIME_FRAME_KIND_LAST_N_YEARS: 'N Năm qua',
			TIME_FRAME_KIND_LAST_N_MONTHS: 'N Tháng qua',
			TIME_FRAME_KIND_LAST_N_WEEKS: 'N Tuần qua',
			TIME_FRAME_KIND_LAST_N_DAYS: 'N Ngày qua',
			TIME_FRAME_N_IS: 'N là:',
			TIME_FRAME_TILL: 'Tới khi:',
			TIME_FRAME_TILL_NOW: 'Bây giờ',
			TIME_FRAME_TILL_LAST_COMPLETE_CYCLE: 'Chu kỳ hoàn chỉnh cuối cùng',
			TIME_FRAME_TILL_SPECIFIED: 'Đã chỉ định',
			TIME_FRAME_TILL_SPECIFIED_AT: ':',
			TIME_FRAME_TILL_SPECIFIED_AT_DESC: 'Đây là ngày cuối cùng của khung thời gian quy định, khung được ngoại suy về phía trước từ ngày được chỉ định',
			TIME_FRAME_CALCULATED: 'Khung hiện tại:',
			TIME_FRAME_PREVIOUS_CYCLE: 'Khung hình trước:',
			TIME_FRAME_CHAIN_CYCLE: 'FKhung trong chu kỳ trước:',
			VARIABLES_TITLE: 'Biến.',
			VARIABLE_IS: 'là',
			VARIABLE_KIND_SINGLE_VALUE: 'Single Value',
			VARIABLE_KIND_RANGE: 'Range Values',
			VARIABLE_KIND_BUCKET: 'From Bucket',
			VARIABLE_RANGE_TO: '..',
			VARIABLE_RANGE_INCLUDE_MIN: '[',
			VARIABLE_RANGE_NOT_INCLUDE_MIN: '(',
			VARIABLE_RANGE_INCLUDE_MAX: ']',
			VARIABLE_RANGE_NOT_INCLUDE_MAX: ')',
			VARIABLE_BUCKET_PLACEHOLDER: 'Một bucket...',
			VARIABLE_BUCKET_INCORRECT_SELECTED: 'Đã chọn xô không xác định.',
			VARIABLE_BUCKET_NO_AVAILABLE: 'Không có bucket sẵn.',
			VARIABLE_BUCKET_SEGMENT_PLACEHOLDER: 'Một phần...',
			VARIABLE_BUCKET_SELECT_FIRST: 'Chọn bucket .',
			VARIABLE_BUCKET_SEGMENT_INCORRECT_SELECTED: 'Đã chọn phân đoạn không xác định.',
			VARIABLE_BUCKET_SEGMENT_NO_AVAILABLE: 'Không có phần khả dụng.',
			ADD_VARIABLE: 'Thêm biến mới',
			REMOVE_VARIABLE: 'Remove Variable',
			FACTORS_TITLE: 'Measure by indicators.',
			FACTOR_INDICATOR: 'Indicator',
			FACTOR_INDICATOR_FILTER: 'Filter',
			FACTOR_FORMULA: 'Formula',
			FACTOR_REFER_SELF: 'Myself',
			REFER_INDICATOR_PLACEHOLDER: 'An indicator...',
			REFER_INDICATOR_BUT_INCORRECT: 'Unknown indicator',
			REFER_INDICATOR_BUT_NO_AVAILABLE: 'No available indicator.',
			REFER_INDICATOR_BUT_NOT_READY: 'is available only when indicator selected.',
			REFER_INDICATOR_ON_NO_FILTER: 'On all data',
			REFER_INDICATOR_ON_TOPIC_FILTER_PLACEHOLDER: 'A factor...',
			REFER_INDICATOR_ON_SUBJECT_FILTER_PLACEHOLDER: 'A column...',
			REFER_INDICATOR_FILTER_ON_INCORRECT_FACTOR_OR_COLUMN: 'Unknown selection',
			REFER_INDICATOR_FILTER_NO_AVAILABLE_FACTOR_OR_COLUMN: 'No available candidate.',
			REFER_INDICATOR_FILTER_ON_INCORRECT_BUCKET: 'Unknown bucket',
			REFER_INDICATOR_FILTER_NO_AVAILABLE_BUCKET: 'No available bucket.',
			REFER_INDICATOR_FILTER_BUCKET_PLACEHOLDER: 'A bucket...',
			REFER_INDICATOR_FILTER_BUCKET_FIRST: 'Select bucket first.',
			REFER_INDICATOR_FILTER_NO_AVAILABLE_BUCKET_SEGMENT: 'No available segment.',
			REFER_INDICATOR_FILTER_BUCKET_SEGMENT_PLACEHOLDER: 'A segment...',
			ADD_INDICATOR: 'Add Indicator',
			ADD_COMPUTED_INDICATOR: 'Add Computation',
			NOT_NOW: 'Not Now',
			SAVE_OBJECTIVE: 'Save Objective',
			SAVE_NAME: 'Save Name',
			REQUIRE_OBJECTIVE_NAME: 'A human reading name for objective is required.',
			CHANGE_NAME: 'Change Name',
			NAME_TITLE: 'Set a human reading name.',
			DESCRIPTION_TITLE: 'Description.',
			USER_GROUP_TITLE: 'Grant to user group.',
			GRANT_USER_GROUP: 'Grant Access',
			REFER_FACTOR_PLACEHOLDER: 'An indicator...',
			REFER_FACTOR_BUT_NONAME: 'Noname Indicator',
			REFER_FACTOR_BUT_INCORRECT: 'Unknown indicator',
			REFER_FACTOR_BUT_NO_AVAILABLE: 'No available indicator.',
			ADD_SUB_PARAMETER: 'Add Parameter',
			CANNOT_ADD_COMPUTATION_PARAMETER: 'Cannot add more because of reach maximum parameter(s).',
			CANNOT_DELETE_COMPUTATION_PARAMETER: 'Cannot delete this because of reach minimum parameter(s).',
			EXPRESSION: 'Expression',
			ADD_SUB_EXPRESSION: 'Add Sub Expression',
			ADD_SUB_JOINT: 'Add Sub Joint',
			TEST_FACTOR: 'Value',
			TEST_VALUE_CLICK: 'Click to retrieve values',
			TEST_VALUE_GET_NONE: 'No data retrieved from server side.'
		},
		STORY: {
			DATA_STORY: 'Câu chuyện dữ liệu',
			NEW_STORY_PREFIX: 'Một câu chuyện dữ liệu mới',
			LIST_LABEL: 'Danh sách câu chuyện dữ liệu',
			EXISTING_STORY_PREFIX: 'Một câu chuyện hiện có'
		},
		CONVERGENCE: {
			LIST_TITLE: 'Hội tụ',
			LIST_CREATE_CONVERGENCE: 'Định nghĩa Hội tụ',
			LIST_LABEL: 'Hội tụ',
			NEW_CONVERGENCE_PREFIX: 'Một Hội tụ mới',
			EXISTING_CONVERGENCE_PREFIX: 'Một Hội tụ hiện có',
			CREATE_AT: 'Được tạo lúc',
			LAST_MODIFIED_AT: 'Chỉnh sửa lần cuối lúc',
			FAILED_TO_LOAD_CONVERGENCE: 'Không thể tải hội tụ, vui lòng liên hệ quản trị viên để biết thêm thông tin.',
			TITLE: 'Định nghĩa Hội tụ',
			BACK_TO_LIST: 'Quay lại danh sách',
			DEF_TITLE: 'Định nghĩa.',
			VARIABLE_NAME: 'Tên',
			VARIABLE_TYPE_FREE_WALK: 'Đi bộ tự do',
			VARIABLE_FREE_WALK_SEGMENTS: 'Các đoạn đi bộ',
			VARIABLE_TYPE_BUCKET: 'Thùng',
			VARIABLE_BUCKET: 'Thùng',
			VARIABLE_BUCKET_SEGMENTS: 'Các đoạn thùng',
			VARIABLE_TYPE_TIMEFRAME: 'Khung thời gian',
			VARIABLE_TIMEFRAME_KIND: 'Tần suất',
			VARIABLE_TIMEFRAME_TILL: 'Đến',
			VARIABLE_TIMEFRAME_TIMES: 'Lần',
			VARIABLE_TIMEFRAME_KIND_DAY: 'Hàng ngày',
			VARIABLE_TIMEFRAME_KIND_WEEK: 'Hàng tuần',
			VARIABLE_TIMEFRAME_KIND_MONTH: 'Hàng tháng',
			VARIABLE_TIMEFRAME_KIND_QUARTER: 'Hàng quý',
			VARIABLE_TIMEFRAME_KIND_HALFYEAR: 'Hàng nửa năm',
			VARIABLE_TIMEFRAME_KIND_YEAR: 'Hàng năm',
			X_AXIS_ADD_PLACEHOLDER: 'Thêm chú giải vào trục X',
			Y_AXIS_ADD_PLACEHOLDER: 'Thêm chú giải vào trục Y',
			PLEASE_SELECT_TARGET: 'Vui lòng chọn...',
			TARGET_USE_TIME_FRAME: 'Sử dụng Khung thời gian?',
			VARIABLE_MAPPING_IGNORED: 'Bị bỏ qua',
			VARIABLE_MAPPING_SOURCE_PLACEHOLDER: 'Vui lòng chọn...',
			FREEZE_DEF: 'Đóng băng Chú giải',
			UNFREEZE_DEF: 'Bỏ Đóng băng Chú giải',
			VARIABLE_NOT_FILLED: 'Vui lòng xác nhận rằng tất cả các giá trị thuộc tính cho chú giải trục đã được điền đúng.',
			ASK_VALUES: 'Định nghĩa hoàn tất, Yêu cầu Dữ liệu',
			BACK_TO_DEF: 'Quay lại Định nghĩa',
			CHANGE_NAME: 'Thay đổi Tên',
			NAME_TITLE: 'Đặt tên có thể đọc được cho người.',
			DESCRIPTION_TITLE: 'Mô tả.',
			USER_GROUP_TITLE: 'Cấp quyền cho nhóm người dùng.',
			GRANT_USER_GROUP: 'Cấp quyền truy cập'
		}
	},
	SUBSCRIBE: {
		ON: 'Đăng ký qua email',
		BY_MAIL: 'Email',
		MAIL_ADDRESS: 'Địa chỉ email',
		BY_SLACK: 'Slack',
		SLACK_CHANNEL: 'Kênh Slack',
		FREQUENCY: 'Tần suất',
		DAILY: 'Hàng ngày',
		WEEKLY: 'Hàng tuần',
		MONTHLY: 'Hàng tháng',
		SUBSCRIPTION_SUBMITTED: 'Đã gửi yêu cầu đăng ký.'
	},
	SETTINGS: {
		TITLE: 'Cài đặt',
		LANGUAGE: 'Ngôn ngữ',
		THEME: 'Chủ đề',
		THEME_LIGHT: 'Sáng',
		THEME_LIGHT_CONTRAST_BIGGER: 'Tăng độ tương phản sáng',
		THEME_DARK: 'Tối',
		THEME_DARK_CONTRAST_BIGGER: 'Tăng độ tương phản tối',
		PAT: {
			TITLE: 'Mã Token Truy cập Cá nhân',
			CREATE: 'Tạo Mã Token Mới',
			DESCRIPTION: 'Các token bạn đã tạo có thể được sử dụng để truy cập API Watchmen.',
			DELETE_CONFIRM: 'Bạn có chắc chắn muốn xóa token này không? Lưu ý rằng hành động này không thể hoàn tác được.',
			INPUT_PLACEHOLDER: 'Ghi chú để nhận dạng mục đích của token',
			NOTE_REQUIRED: 'Ghi chú là bắt buộc để tạo token.'
		}
	},
	PARAM: {
		FROM: 'Từ',
		FROM_TOPIC: 'Chủ đề',
		FROM_CONSTANT: 'Hằng số',
		FROM_COMPUTED: 'Tính toán',
		FROM_INDICATOR: 'Tham chiếu',
		FROM_BUCKET: 'Bucket',
		FROM_TIME_FRAME: 'Khung thời gian'
	},
	FACTOR: {
		SEQUENCE: 'Sự xếp theo',
		NUMBER: 'Số',
		UNSIGNED: 'Số không dấu',
		TEXT: 'Văn bản',
		ADDRESS: 'Địa chỉ',
		CONTINENT: 'Châu lục',
		REGION: 'Vùng',
		COUNTRY: 'Quốc gia',
		PROVINCE: 'Bang / Tỉnh',
		CITY: 'Thành phố',
		DISTRICT: 'Quận',
		ROAD: 'Đường',
		COMMUNITY: 'Cộng đồng',
		FLOOR: 'Tầng',
		RESIDENCE_TYPE: 'Loại hình cư trú',
		RESIDENTIAL_AREA: 'Khu dân cư',
		EMAIL: 'Email',
		PHONE: 'Điện thoại',
		MOBILE: 'Di động',
		FAX: 'Fax',
		DATETIME: 'Ngày giờ',
		FULL_DATETIME: 'Ngày giờ đầy đủ',
		DATE: 'Ngày',
		TIME: 'Thời gian',
		YEAR: 'Năm',
		HALF_YEAR: 'Nửa năm đầu / Nửa năm sau',
		QUARTER: 'Quý',
		MONTH: 'Tháng',
		HALF_MONTH: 'Nửa tháng đầu / Nửa tháng sau',
		TEN_DAYS: '10 ngày đầu / 10 ngày giữa / 10 ngày cuối',
		WEEK_OF_YEAR: 'Tuần của năm',
		WEEK_OF_MONTH: 'Tuần của tháng',
		HALF_WEEK: 'Nửa tuần đầu / Nửa tuần sau',
		DAY_OF_MONTH: 'Ngày trong tháng',
		DAY_OF_WEEK: 'Ngày trong tuần',
		DAY_KIND: 'Ngày làm việc / Ngày nghỉ / Ngày lễ',
		HOUR: 'Giờ',
		HOUR_KIND: 'Giờ làm việc / Giờ nghỉ / Giờ ngủ',
		MINUTE: 'Phút',
		SECOND: 'Giây',
		MILLISECOND: 'Mili giây',
		AM_PM: 'Sáng / Chiều',
		GENDER: 'Giới tính',
		OCCUPATION: 'Nghề nghiệp',
		DATE_OF_BIRTH: 'Ngày sinh',
		AGE: 'Tuổi',
		ID_NO: 'Số CMND',
		RELIGION: 'Tôn giáo',
		NATIONALITY: 'Quốc tịch',
		BIZ_TRADE: 'Ngành nghề kinh doanh',
		BIZ_SCALE: 'Quy mô kinh doanh',
		BOOLEAN: 'Luận lý',
		ENUM: 'Định nghĩa',
		OBJECT: 'Đối tượng',
		ARRAY: 'Mảng'
	},
	PARAMETER: {
		EXPRESSION: 'Biểu thức',
		COMPUTE_TYPE: {
			NONE: 'Nguyên trạng',
			ADD: 'Cộng',
			SUBTRACT: 'Trừ',
			MULTIPLY: 'Nhân',
			DIVIDE: 'Chia',
			MODULUS: 'Số dư',
			YEAR_OF: 'Năm của',
			HALF_YEAR_OF: 'Nửa năm của',
			QUARTER_OF: 'Quý của',
			MONTH_OF: 'Tháng của',
			WEEK_OF_YEAR: 'Tuần của năm',
			WEEK_OF_MONTH: 'Tuần của tháng',
			DAY_OF_MONTH: 'Ngày của tháng',
			DAY_OF_WEEK: 'Ngày của tuần',
			CASE_THEN: 'Trường hợp rồi',
			ROUND: 'Làm tròn',
			ROUND_DIGITS: 'Chữ số',
			FLOOR: 'Sàn',
			CEIL: 'Trần',
			ABS: 'Giá trị tuyệt đối',
			MAX: 'Giá trị lớn nhất của',
			MIN: 'Giá trị nhỏ nhất của',
			INTERPOLATE: 'Nội suy tuyến tính',
			INTERPOLATE_MIN_VALUE: 'Giá trị dưới cùng',
			INTERPOLATE_MIN_VALUE_TO: 'Ánh xạ giá trị dưới cùng đến',
			INTERPOLATE_MAX_VALUE: 'Giá trị trên cùng',
			INTERPOLATE_MAX_VALUE_TO: 'Ánh xạ giá trị trên cùng đến'
		},
		EXPRESSION_OPERATOR: {
			EMPTY: 'Rỗng',
			NOT_EMPTY: 'Có giá trị',
			EQUALS: 'Bằng',
			NOT_EQUALS: 'Không bằng',
			LESS: 'Nhỏ hơn',
			LESS_EQUALS: 'Nhỏ hơn hoặc bằng',
			MORE: 'Lớn hơn',
			MORE_EQUALS: 'Lớn hơn hoặc bằng',
			IN: 'Trong',
			NOT_IN: 'Không trong'
		}
	},
	JOINT: {
		AND: 'Và',
		OR: 'HOẶC'
	},
	JOIN: {
		INNER: 'Khớp chính xác',
		LEFT: 'Ưu tiên bên trái',
		RIGHT: 'Ưu tiên bên phải'
	},
	FUNNEL: {
		COLUMN: 'Cột - Loại',
		RANGE: 'Phạm vi?',
		ENABLED: 'Kích hoạt?',
		NUMERIC: 'Số',
		DATE: 'Ngày',
		YEAR: 'Năm',
		HALF_YEAR: 'Nửa năm',
		QUARTER: 'Quý',
		MONTH: 'Tháng',
		HALF_MONTH: 'Một nửa tháng',
		TEN_DAYS: 'Mười ngày',
		WEEK_OF_MONTH: 'Tuần của tháng',
		HALF_WEEK: 'Nửa tuần',
		DAY_KIND: 'Loại ngày',
		DAY_OF_WEEK: 'Ngày của tuần',
		HOUR: 'Giờ',
		HOUR_KIND: 'Loại giờ',
		AM_PM: 'AM/PM',
		ENUM: 'Danh mục'
	},
	PAGINATION: {
		TOTAL: '',
		ROWS: 'Tổng số hàng',
		OF_PAGES: 'của',
		PAGES: 'Trang'
	},
	CHART: {
		SETTINGS_HEADER_LABEL: 'Cài đặt Báo cáo',
		SECTION_TITLE_BASIC_STYLE: 'Kiểu cơ bản',
		SECTION_TITLE_DIMENSIONS: 'Kích thước',
		SECTION_TITLE_INDICATORS: 'Chỉ số',
		SECTION_TITLE_BASIC: 'Cơ bản',
		SECTION_TITLE_PALETTE_SIZE: 'Kích thước bảng màu',
		SECTION_TITLE_COLOR: 'Màu sắc',
		SECTION_TITLE_BORDER: 'Đường viền',
		SECTION_TITLE_FONT: 'Font chữ',
		SECTION_TITLE_POSITION: 'Vị trí',
		SECTION_TITLE_PADDING: 'Đệm',
		SECTION_TITLE_GAP_AND_PADDING: 'Khoảng trống & Đệm',
		SECTION_TITLE_VALUE_FORMAT: 'Định dạng giá trị',
		SECTION_TITLE_FUNNEL_DEFINITION: 'Định nghĩa ống dẫn',
		DIMENSIONS: 'Kích thước',
		INDICATORS: 'Chỉ số',
		FILTERS: 'Bộ lọc',
		NO_FUNNEL_DETECTED: 'Không có ống dẫn khả dụng.',
		FUNNEL_DESCRIPTION: 'Các ống dẫn có sẵn được tự động phát hiện, bật chúng để điều chỉnh dữ liệu báo cáo động tại đây và trên bảng điều khiển.',
		FUNNEL_INSTANCE_DESCRIPTION: 'Mở bảng màu để định nghĩa giá trị của ống dẫn.',
		DESCRIPTION: 'Mô tả',
		WIDTH: 'Chiều rộng',
		HEIGHT: 'Chiều cao',
		PIXEL: 'PX',
		PERCENTAGE: '%',
		DEGREE: 'Độ',
		LINE_COLOR: 'Màu đường',
		LINE_STYLE: 'Kiểu đường',
		FONT_FAMILY: 'Font chữ',
		FONT_COLOR: 'Màu chữ',
		FONT_SIZE: 'Cỡ chữ',
		FONT_STYLE: 'Kiểu chữ',
		FONT_STYLE_NORMAL: 'Bình thường',
		FONT_STYLE_ITALIC: 'Nghiêng',
		FONT_WEIGHT: 'Độ đậm',
		FONT_WEIGHT_100: '100',
		FONT_WEIGHT_200: '200',
		FONT_WEIGHT_300: '300',
		FONT_WEIGHT_400: '400',
		FONT_WEIGHT_500: '500',
		FONT_WEIGHT_600: '600',
		FONT_WEIGHT_700: '700',
		FONT_WEIGHT_800: '800',
		FONT_WEIGHT_900: '900',
		BACKGROUND_COLOR: 'Màu nền',
		BORDER_STYLE: 'Kiểu đường viền',
		BORDER_STYLE_NONE: 'Không',
		BORDER_STYLE_SOLID: 'Đơn vị',
		BORDER_STYLE_DASHED: 'Đứt',
		BORDER_STYLE_DOTTED: 'Chấm',
		BORDER_COLOR: 'Màu đường viền',
		BORDER_WIDTH: 'Độ dày đường viền',
		BORDER_RADIUS: 'Bán kính đường viền',
		POSITION: 'Vị trí',
		POSITION_ON_OUTSIDE_OF_PIE: 'Vị trí bên ngoài',
		POSITION_TOP: 'Trên',
		POSITION_RIGHT: 'Phải',
		POSITION_LEFT: 'Trái',
		POSITION_BOTTOM: 'Dưới',
		HORIZONTAL_ALIGNMENT: 'Căn chỉnh ngang',
		HORIZONTAL_ALIGNMENT_AUTO: 'Tự động',
		HORIZONTAL_ALIGNMENT_LEFT: 'Trái',
		HORIZONTAL_ALIGNMENT_CENTER: 'Giữa',
		HORIZONTAL_ALIGNMENT_RIGHT: 'Phải',
		VERTICAL_ALIGNMENT: 'Căn chỉnh dọc',
		VERTICAL_ALIGNMENT_AUTO: 'Tự động',
		VERTICAL_ALIGNMENT_TOP: 'Trên',
		VERTICAL_ALIGNMENT_MIDDLE: 'Giữa',
		VERTICAL_ALIGNMENT_BOTTOM: 'Dưới',
		TITLE_TEXT_ITEM_GAP: 'Khoảng cách giữa tiêu đề',
		PADDING: 'Đệm',
		SHOW: 'Hiển thị',
		SERIES_TEXT_SHOW: 'Hiển thị văn bản chuỗi',
		SERIES_TEXT_POSITION: 'Vị trí văn bản chuỗi',
		SERIES_TEXT_FONT: 'Font văn bản chuỗi',
		SERIES_TEXT_COLOR: 'Màu văn bản chuỗi',
		SERIES_TEXT_BORDER: 'Đường viền văn bản chuỗi',
		SERIES_TEXT_GAP_AND_PADDING: 'Khoảng trống & Đệm văn bản chuỗi',
		LEGEND_ORIENT: 'Hướng',
		LEGEND_ORIENT_HORIZONTAL: 'Ngang',
		LEGEND_ORIENT_VERTICAL: 'Dọc',
		GRID_CONTAIN_LABEL: 'Chứa nhãn',
		AXIS_TYPE: 'Loại trục',
		AXIS_TYPE_CATEGORY: 'Danh mục',
		AXIS_TYPE_VALUE: 'Giá trị',
		AXIS_TYPE_TIME: 'Thời gian',
		AXIS_AUTO_MIN: 'Tự động tối thiểu',
		AXIS_MIN: 'Tối thiểu',
		AXIS_AUTO_MAX: 'Tự động tối đa',
		AXIS_MAX: 'Tối đa',
		AXIS_NAME_LOCATION: 'Vị trí tên',
		AXIS_NAME_LOCATION_START: 'Bắt đầu',
		AXIS_NAME_LOCATION_CENTER: 'Giữa',
		AXIS_NAME_LOCATION_END: 'Cuối',
		AXIS_NAME_GAP: 'Khoảng cách',
		AXIS_NAME_ROTATE: 'Xoay',
		AXIS_LABEL_INSIDE: 'Bên trong',
		LABEL_GAP: 'Khoảng cách',
		LABEL_ROTATE: 'Xoay',
		LABEL_FORMAT_USING_GROUP: 'Sử dụng nhóm',
		LABEL_FORMAT_USING_PERCENTAGE: 'Sử dụng %',
		LABEL_VALUE_AS_PERCENTAGE: 'Giá trị như %',
		LABEL_FRACTION_DIGITS: 'Số chữ số thập phân',
		LABEL_POSITION_TOP: 'Trên',
		LABEL_POSITION_LEFT: 'Trái',
		LABEL_POSITION_RIGHT: 'Phải',
		LABEL_POSITION_BOTTOM: 'Dưới',
		LABEL_POSITION_INSIDE: 'Bên trong',
		LABEL_POSITION_INSIDE_LEFT: 'Bên trong bên trái',
		LABEL_POSITION_INSIDE_RIGHT: 'Bên trong bên phải',
		LABEL_POSITION_INSIDE_TOP: 'Bên trong phía trên',
		LABEL_POSITION_INSIDE_BOTTOM: 'Bên trong phía dưới',
		LABEL_POSITION_INSIDE_TOP_LEFT: 'Bên trong trên bên trái',
		LABEL_POSITION_INSIDE_BOTTOM_LEFT: 'Bên trong dưới bên trái',
		LABEL_POSITION_INSIDE_TOP_RIGHT: 'Bên trong trên bên phải',
		LABEL_POSITION_INSIDE_BOTTOM_RIGHT: 'Bên trong dưới bên phải',
		LABEL_POSITION_OUTSIDE: 'Bên ngoài',
		LABEL_POSITION_CENTER: 'Giữa',
		DECAL: 'Dán',
		ROAM: 'Lang thang',
		TREE_LAYOUT: 'Bố cục',
		TREE_LAYOUT_ORTHOGONAL: 'Chính hướng',
		TREE_LAYOUT_RADIAL: 'Bán kính',
		TREE_ORIENT: 'Định hướng',
		TREE_ORIENT_LEFT_RIGHT: 'Từ trái sang phải',
		TREE_ORIENT_RIGHT_LEFT: 'Từ phải sang trái',
		TREE_ORIENT_TOP_BOTTOM: 'Từ trên xuống dưới',
		TREE_ORIENT_BOTTOM_TOP: 'Từ dưới lên trên',
		PIE_CENTER_X: 'Tâm X',
		PIE_CENTER_Y: 'Tâm Y',
		PIE_INSIDE_RADIUS: 'Bán kính trong',
		PIE_OUTSIDE_RADIUS: 'Bán kính ngoài',
		PIE_ROSE_TYPE: 'Loại hoa hồng',
		PIE_ROSE_TYPE_NONE: 'Không',
		PIE_ROSE_TYPE_RADIUS: 'Theo bán kính',
		PIE_ROSE_TYPE_AREA: 'Theo diện tích',
		PIE_SHOW_PERCENTAGE: 'Hiển thị %',
		PIE_LABEL_ALIGN_TO_NONE: 'Không',
		PIE_LABEL_ALIGN_TO_LABEL_LINE: 'Dòng nhãn',
		PIE_LABEL_ALIGN_TO_EDGE: 'Cạnh',
		MAP_REGION: 'Khu vực',
		MAP_REGION_CHINA_L1: 'Trung Quốc (Tỉnh)',
		MAP_REGION_CYPRUS_L1: 'Síp',
		MAP_REGION_JAPAN_L1: 'Nhật Bản (Tỉnh)',
		MAP_REGION_SINGAPORE_L1: 'Singapore',
		MAP_REGION_USA_L1: 'Hoa Kỳ (Bang)',
		TRUNCATION_TYPE: 'Loại',
		TRUNCATION_NONE: 'Không',
		TRUNCATION_TOP: 'Trên',
		TRUNCATION_BOTTOM: 'Dưới',
		TRUNCATION_COUNT: 'Số lượng',
		BAR_TRANSFORM_AXIS: 'Trục biến đổi',
		LINE_SMOOTH: 'Mượt',
		TOOLBOX_ORIENT: 'Định hướng',
		TOOLBOX_ORIENT_HORIZONTAL: 'Ngang',
		TOOLBOX_ORIENT_VERTICAL: 'Dọc',
		SECTION_TITLE_COUNT_CHART: 'Kiểu Đếm',
		SECTION_TITLE_BAR_CHART: 'Kiểu Cột/Đường',
		SECTION_TITLE_PIE_CHART: 'Kiểu Bánh',
		SECTION_TITLE_TREE_CHART: 'Kiểu Cây',
		SECTION_TITLE_TREEMAP_CHART: 'Kiểu Treemap',
		SECTION_TITLE_MAP_CHART: 'Kiểu Bản đồ',
		SECTION_TITLE_ECHART_TITLE: 'Tiêu đề',
		SECTION_TITLE_ECHART_SUBTITLE: 'Phụ đề',
		SECTION_TITLE_ECHART_LEGEND: 'Chú giải',
		SECTION_TITLE_ECHART_GRID: 'Lưới',
		SECTION_TITLE_ECHART_XAXIS: 'Trục X',
		SECTION_TITLE_ECHART_XAXIS_RANGE: 'Phạm vi Trục X',
		SECTION_TITLE_ECHART_XAXIS_NAME: 'Tên Trục X',
		SECTION_TITLE_ECHART_XAXIS_NAME_FONT: 'Tên Trục X - Font',
		SECTION_TITLE_ECHART_XAXIS_NAME_COLOR: 'Tên Trục X - Màu sắc',
		SECTION_TITLE_ECHART_XAXIS_NAME_BORDER: 'Tên Trục X - Viền',
		SECTION_TITLE_ECHART_XAXIS_NAME_GAP_AND_PADDING: 'Tên Trục X - Khoảng cách & Lề',
		SECTION_TITLE_ECHART_XAXIS_LABEL: 'Nhãn Trục X',
		SECTION_TITLE_ECHART_XAXIS_LABEL_FONT: 'Nhãn Trục X - Font',
		SECTION_TITLE_ECHART_XAXIS_LABEL_COLOR: 'Nhãn Trục X - Màu sắc',
		SECTION_TITLE_ECHART_XAXIS_LABEL_BORDER: 'Nhãn Trục X - Viền',
		SECTION_TITLE_ECHART_XAXIS_LABEL_GAP_AND_PADDING: 'Nhãn Trục X - Khoảng cách & Lề',
		SECTION_TITLE_ECHART_XAXIS_LINE: 'Đường chia Trục X',
		SECTION_TITLE_ECHART_XAXIS_MINOR_LINE: 'Đường chia phụ Trục X',
		SECTION_TITLE_ECHART_YAXIS: 'Trục Y',
		SECTION_TITLE_ECHART_YAXIS_RANGE: 'Phạm vi Trục Y',
		SECTION_TITLE_ECHART_YAXIS_NAME: 'Tên Trục Y',
		SECTION_TITLE_ECHART_YAXIS_NAME_FONT: 'Tên Trục Y - Font',
		SECTION_TITLE_ECHART_YAXIS_NAME_COLOR: 'Tên Trục Y - Màu sắc',
		SECTION_TITLE_ECHART_YAXIS_NAME_BORDER: 'Tên Trục Y - Viền',
		SECTION_TITLE_ECHART_YAXIS_NAME_GAP_AND_PADDING: 'Tên Trục Y - Khoảng cách & Lề',
		SECTION_TITLE_ECHART_YAXIS_LABEL: 'Nhãn Trục Y',
		SECTION_TITLE_ECHART_YAXIS_LABEL_FONT: 'Nhãn Trục Y - Font',
		SECTION_TITLE_ECHART_YAXIS_LABEL_COLOR: 'Nhãn Trục Y - Màu sắc',
		SECTION_TITLE_ECHART_YAXIS_LABEL_BORDER: 'Nhãn Trục Y - Viền',
		SECTION_TITLE_ECHART_YAXIS_LABEL_GAP_AND_PADDING: 'Nhãn Trục Y - Khoảng cách & Lề',
		SECTION_TITLE_ECHART_YAXIS_LINE: 'Đường chia Trục Y',
		SECTION_TITLE_ECHART_YAXIS_MINOR_LINE: 'Đường chia phụ Trục Y',
		SECTION_TITLE_ECHART_SCRIPT: 'Kịch bản',
		SECTION_TITLE_ECHART_SCRIPT_VARS_DEF: 'Định nghĩa Biến',
		SECTION_TITLE_ECHART_SCRIPT_VARS: 'Biến',
		SECTION_TITLE_TRUNCATION: 'Cắt dữ liệu',
		SECTION_TITLE_TOOLBOX: 'Hộp công cụ',
		NONAME_COLUMN: 'Cột Không tên',
		UNKNOWN_COLUMN_NAME: 'Tên Cột Không xác định',
		CAN_NOT_DELETE_DIMENSION: 'Không thể xóa vì đã đạt tối thiểu chiều',
		CAN_NOT_ADD_DIMENSION: 'Không thể thêm vì đã đạt tối đa chiều',
		CAN_NOT_DELETE_INDICATOR: 'Không thể xóa vì đã đạt tối thiểu chỉ số',
		CAN_NOT_ADD_INDICATOR: 'Không thể thêm vì đã đạt tối đa chỉ số',
		ADD_DIMENSION: 'Thêm Chiều',
		ADD_INDICATOR: 'Thêm Chỉ số',
		PLEASE_SELECT_DIMENSION: 'Vui lòng chọn...',
		PLEASE_SELECT_INDICATOR: 'Vui lòng chọn...',
		PLEASE_SELECT_FUNNEL_VALUE: 'Vui lòng chọn...',
		NO_ENUM_FUNNEL_VALUE: 'Không có giá trị được chọn',
		NO_SCRIPT_VARS: 'Không có biến kịch bản được định nghĩa',
		ARITHMETIC_NONE: 'Như Vậy',
		ARITHMETIC_SUMMARY: 'Tổng',
		ARITHMETIC_AVERAGE: 'Trung bình',
		ARITHMETIC_COUNT: 'Đếm',
		ARITHMETIC_DISTINCT_COUNT: 'Đếm Riêng Biệt',
		ARITHMETIC_MAX: 'Tối Đa',
		ARITHMETIC_MIN: 'Tối Thiểu',
		TYPE: 'Loại',
		TYPES: {
			COUNT: 'Giá trị Đơn',
			BAR: 'Thanh',
			LINE: 'Đường',
			SCATTER: 'Phân tán',
			PIE: 'Bánh',
			DOUGHNUT: 'Bánh rán',
			NIGHTINGALE: 'Nightingale',
			SUNBURST: 'Sunburst',
			TREE: 'Cây',
			TREEMAP: 'Bản đồ cây',
			MAP: 'Bản đồ',
			CUSTOMIZED: 'Tùy chỉnh'
		},
		COUNT: {
			FORMAT_USING_GROUP: 'Sử dụng Nhóm'
		},
		ECHART: {
			TEXT: 'Văn bản'
		},
		DEFINITION_BROKEN: 'Định nghĩa không hoàn chỉnh, không thể vẽ biểu đồ vào lúc này.'
	},
	MEASURE_METHOD: {
		CONTINENT: 'Lục địa',
		REGION: 'Vùng',
		COUNTRY: 'Quốc gia',
		PROVINCE: 'Tỉnh thành',
		CITY: 'Thành phố',
		DISTRICT: 'Quận huyện',
		FLOOR: 'Tầng',
		RESIDENCE_TYPE: 'Loại chỗ ở',
		RESIDENTIAL_AREA: 'Diện tích sống',
		YEAR: 'Năm',
		HALF_YEAR: 'Nửa năm đầu/tiếp theo',
		QUARTER: 'Quý',
		MONTH: 'Tháng',
		HALF_MONTH: 'Một nửa tháng đầu/tiếp theo',
		TEN_DAYS: 'Mười ngày đầu/tiếp theo',
		WEEK_OF_YEAR: 'Tuần trong năm',
		WEEK_OF_MONTH: 'Tuần trong tháng',
		HALF_WEEK: 'Một nửa tuần đầu/tiếp theo',
		DAY_OF_MONTH: 'Ngày trong tháng',
		DAY_OF_WEEK: 'Ngày trong tuần',
		DAY_KIND: 'Ngày làm việc/Ngày nghỉ lễ',
		HOUR: 'Giờ',
		HOUR_KIND: 'Giờ làm việc/Giờ nghỉ ngơi/Giờ ngủ',
		AM_PM: 'AM/PM',
		GENDER: 'Giới tính',
		OCCUPATION: 'Nghề nghiệp',
		AGE: 'Tuổi',
		RELIGION: 'Tôn giáo',
		NATIONALITY: 'Quốc tịch',
		BIZ_TRADE: 'Ngành nghề kinh doanh',
		BIZ_SCALE: 'Quy mô kinh doanh',
		BOOLEAN: 'Logic',
		ENUM: 'Danh mục'
	},
	RELEVANT_INDICATOR_TYPE: {
		SAME: 'Giống nhau',
		HIGH_CORRELATED: 'Tương quan cao',
		WEAK_CORRELATED: 'Tương quan yếu',
		THIS_CAUSES_RELEVANT: 'Gây ra liên quan',
		RELEVANT_CAUSES_THIS: 'Do liên quan gây ra'
	},
	SHARE: {
		NOTHING: 'Không có nội dung được tìm thấy, vui lòng liên hệ với quản trị viên để biết thêm thông tin.'
	},
	CALENDAR: {
		JAN: 'Một',
		FEB: 'Hai',
		MAR: 'Ba',
		APR: 'Tư',
		MAY: 'Năm',
		JUN: 'Sáu',
		JUL: 'Bảy',
		AUG: 'Tám',
		SEP: 'Chín',
		OCT: 'Mười',
		NOV: 'Mười Một',
		DEC: 'Mười Hai',
		WEEK: 'Tuần',
		WEEK_0: 'Tuần 0 (Tuần không đầy đủ)',
		WEEK_1: 'Tuần 1',
		WEEK_2: 'Tuần 2',
		WEEK_3: 'Tuần 3',
		WEEK_4: 'Tuần 4',
		WEEK_5: 'Tuần 5 (Tuần không đầy đủ)',
		HALF_YEAR_1ST: 'Nửa đầu năm',
		HALF_YEAR_2ND: 'Nửa sau năm',
		QUARTER_1ST: 'Quý 1',
		QUARTER_2ND: 'Quý 2',
		QUARTER_3RD: 'Quý 3',
		QUARTER_4TH: 'Quý 4',
		HALF_MONTH_1ST: 'Một nửa tháng đầu',
		HALF_MONTH_2ND: 'Một nửa tháng sau',
		TEN_DAYS_1ST: '10 ngày đầu tháng',
		TEN_DAYS_2ND: '10 ngày tiếp theo',
		TEN_DAYS_3RD: '10 ngày cuối cùng của tháng',
		HALF_WEEK_1ST: 'Một nửa tuần đầu',
		HALF_WEEK_2ND: 'Một nửa tuần sau',
		SUNDAY: 'Chủ Nhật',
		MONDAY: 'Thứ Hai',
		TUESDAY: 'Thứ Ba',
		WEDNESDAY: 'Thứ Tư',
		THURSDAY: 'Thứ Năm',
		FRIDAY: 'Thứ Sáu',
		SATURDAY: 'Thứ Bảy',
		WORKDAY: 'Ngày làm việc',
		WEEKEND: 'Cuối tuần',
		HOLIDAY: 'Ngày nghỉ lễ',
		WORK_TIME: 'Thời gian làm việc',
		OFF_HOURS: 'Giờ nghỉ ngơi',
		SLEEPING_TIME: 'Thời gian ngủ',
		AM: 'AM',
		PM: 'PM'
	},
	CONSANGUINITY: {
		OBJECTIVE_TARGET_BLOCK_LABEL: 'Mục tiêu',
		OBJECTIVE_FACTOR_BLOCK_LABEL: 'Chỉ số đo lường',
		INDICATOR_BLOCK_LABEL: 'Chỉ số',
		SUBJECT_BLOCK_LABEL: 'Chủ đề',
		REPORT_BLOCK_LABEL: 'Báo cáo',
		TOPIC_BLOCK_LABEL: 'Chủ đề',
		BUCKET_BLOCK_LABEL: 'Thùng',
		ENUM_BLOCK_LABEL: 'Danh mục',
		NO_OBJECTIVE_TARGET_FOUND: 'Không tìm thấy mục tiêu nào.',
		NONAME_OBJECTIVE_TARGET: 'Mục tiêu không tên',
		NONAME_OBJECTIVE_FACTOR: 'Chỉ số đo lường không tên',
		NONAME_INDICATOR: 'Chỉ số không tên',
		NONAME_SUBJECT: 'Chủ đề không tên',
		NONAME_SUBJECT_COLUMN: 'Cột chủ đề không tên',
		NONAME_REPORT: 'Báo cáo không tên',
		NONAME_TOPIC: 'Chủ đề không tên',
		NONAME_TOPIC_FACTOR: 'Yếu tố chủ đề không tên',
		NONAME_BUCKET: 'Thùng không tên',
		NONAME_ENUM: 'Danh mục không tên'
	},
	COPILOT: {
		YES: 'Chắc chắn, tiến lên.',
		NO: 'Không.',
		NOTED: 'Chú ý. Còn việc gì khác tôi có thể giúp bạn không?',
		ASK_RECOMMENDATION: 'Cho tôi những đề xuất của bạn.',
		REPLY_ASKING_RECOMMENDATION: 'Chú ý. Vui lòng đợi trong khi tôi kiểm tra các tùy chọn được đề xuất.',
		STILL_WORKING: 'Vẫn đang làm việc trên điều này...',
		CONNECT_FAIL: 'Có vẻ như có vấn đề; Tôi không thể kết nối với máy chủ vào lúc này. Bạn có muốn thử lại không?',
		ASK_RESTART_SESSION: 'Khởi động lại phiên mới.',
		OPTION_PICKED_NOTED: 'Chắc chắn rồi! Lựa chọn tuyệt vời. Xin hãy đợi trong khi tôi kiểm tra chi tiết.',
		CONNECTED_SPACE: {
			GREETING_FIRST_SESSION: 'Xin chào! Tôi là trợ lý trí tuệ nhân tạo. Tôi có thể giúp bạn phân tích dữ liệu của không gian kết nối hiện tại. Vui lòng đợi trong khi tôi kiểm tra các tùy chọn được đề xuất.',
			GREETING_RESTART_SESSION: 'Dạ, cho em hỏi giúp anh/chị điều gì ạ? Có thể anh/chị muốn xem lại các lựa chọn mà chúng em đề xuất không ạ?'
		}
	}
};
