CREATE TABLE alert_instances
(
    instance_id          VARCHAR(50)   NOT NULL,
    rule_id              VARCHAR(50),
    rule_name            VARCHAR(128),
    trigger_time         DATETIME,
    severity             VARCHAR(20),
    message              VARCHAR(1024),
    condition_results    JSON,
    actions              JSON,
    acknowledged         TINYINT,
    acknowledged_by      VARCHAR(50),
    acknowledged_at      DATETIME,
    acknowledge_reason   VARCHAR(1024),
    next_trigger_time    DATETIME,
    interval_minutes     INTEGER,
    tenant_id            VARCHAR(50)   NOT NULL,
    created_at           DATETIME      NOT NULL,
    created_by           VARCHAR(50)   NOT NULL,
    last_modified_at     DATETIME      NOT NULL,
    last_modified_by     VARCHAR(50)   NOT NULL,
    version              INTEGER       DEFAULT 1,
    user_id              VARCHAR(50)   NOT NULL,
    PRIMARY KEY (instance_id),
    INDEX (tenant_id),
    INDEX (rule_id),
    INDEX (trigger_time),
    INDEX (acknowledged),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by),
    INDEX (user_id)
);