# Storage entity names used by the meta services.
SIGNAL_ENTITY_NAME = 'sensing_signals'
SENSOR_ENTITY_NAME = 'sensing_sensors'
ACTION_RECORD_ENTITY_NAME = 'sensing_action_records'
SCHEMA_SNAPSHOT_ENTITY_NAME = 'sensing_schema_snapshots'

# Asset types referenced by AffectedAsset.type.
ASSET_TYPE_TOPIC = 'TOPIC'
ASSET_TYPE_PIPELINE = 'PIPELINE'
ASSET_TYPE_ONTOLOGY_OBJECT = 'ONTOLOGY_OBJECT'
ASSET_TYPE_DATA_PRODUCT = 'DATA_PRODUCT'
ASSET_TYPE_METRIC = 'METRIC'
ASSET_TYPE_DATA_SOURCE = 'DATA_SOURCE'
ASSET_TYPE_COLLECTOR_TABLE = 'COLLECTOR_TABLE'

# Execution modes for a recommended action (section 33 risk control).
EXECUTION_MODE_AUTO = 'auto'
EXECUTION_MODE_REVIEW = 'review'
EXECUTION_MODE_APPROVAL = 'approval'

# Risk levels.
RISK_LOW = 'low'
RISK_MEDIUM = 'medium'
RISK_HIGH = 'high'
RISK_CRITICAL = 'critical'

# Default page size for signal queries.
DEFAULT_PAGE_SIZE = 20

# Signal type strings -- the cross-module contract between sensors, the action
# map and signal consumers. Centralized to avoid typos across modules.
SIGNAL_SCHEMA_CHANGED = 'SCHEMA_CHANGED'
SIGNAL_SCHEMA_REFLECTION_FAILED = 'SCHEMA_REFLECTION_FAILED'
SIGNAL_SCHEMA_BASELINE_ESTABLISHED = 'SCHEMA_BASELINE_ESTABLISHED'
SIGNAL_TOPIC_DEFINITION_CHANGED = 'TOPIC_DEFINITION_CHANGED'
SIGNAL_COLLECTOR_TABLE_CHANGED = 'COLLECTOR_TABLE_CHANGED'
SIGNAL_PIPELINE_FAILURE = 'PIPELINE_FAILURE'
SIGNAL_DATA_FRESHNESS_BREACH = 'DATA_FRESHNESS_BREACH'
SIGNAL_DATA_QUALITY_DEGRADED = 'DATA_QUALITY_DEGRADED'
SIGNAL_DATA_PROFILE_READY = 'DATA_PROFILE_READY'
SIGNAL_DATA_DRIFT_DETECTED = 'DATA_DRIFT_DETECTED'
SIGNAL_SEMANTIC_MAPPING_CANDIDATE = 'SEMANTIC_MAPPING_CANDIDATE'
SIGNAL_SOURCE_DISCOVERED = 'SOURCE_DISCOVERED'
SIGNAL_DATA_CONTRACT_VIOLATION = 'DATA_CONTRACT_VIOLATION'
SIGNAL_PIPELINE_PERFORMANCE_DEGRADED = 'PIPELINE_PERFORMANCE_DEGRADED'
SIGNAL_METRIC_ANOMALY = 'METRIC_ANOMALY'

# Table / column change types produced by the schema diff engine and consumed by
# the schema drift sensor.
CHANGE_TABLE_ADDED = 'TABLE_ADDED'
CHANGE_TABLE_REMOVED = 'TABLE_REMOVED'
CHANGE_COLUMNS_CHANGED = 'COLUMNS_CHANGED'
CHANGE_COLUMN_ADDED = 'COLUMN_ADDED'
CHANGE_COLUMN_REMOVED = 'COLUMN_REMOVED'
CHANGE_COLUMN_TYPE_CHANGED = 'TYPE_CHANGED'
CHANGE_COLUMN_NULLABLE_CHANGED = 'NULLABLE_CHANGED'
CHANGE_COLUMN_DEFAULT_CHANGED = 'DEFAULT_CHANGED'
CHANGE_COLUMN_COMMENT_CHANGED = 'COMMENT_CHANGED'
