CREATE OR REPLACE FUNCTION DATEDIFF(end_date IN TIMESTAMPTZ, start_date IN TIMESTAMPTZ) RETURNS INT AS
$$
BEGIN
    RETURN DATE_PART('DAY', DATE_TRUNC('DAY', end_date) - DATE_TRUNC('DAY', start_date));
END;
$$ LANGUAGE PLPGSQL;
