export enum IndicatorDeclarationStep {
	CREATE_OR_FIND = 1,
	PICK_TOPIC_OR_SUBJECT,
	MEASURE_METHODS,
	DEFINE_BUCKETS,
	SAVE_INDICATOR,
	RELEVANT_INDICATORS,
	USER_GROUPS,
	FILTERS,
	CATEGORIES,
	DESCRIPTION,
	LAST_STEP
}