ALTER TABLE data_sources RENAME TO data_sources_1;
ALTER TABLE data_sources_1 RENAME TO data_sources;
ALTER TABLE data_sources RENAME COLUMN datasourceid TO data_source_id;
ALTER TABLE data_sources MODIFY (data_source_id VARCHAR2(50) NOT NULL);
ALTER TABLE data_sources RENAME COLUMN dataSourceCode TO data_source_code;
ALTER TABLE data_sources MODIFY (data_source_code VARCHAR2(50) NOT NULL);
ALTER TABLE data_sources RENAME COLUMN dataSourceType TO data_source_type;
ALTER TABLE data_sources MODIFY (data_source_type VARCHAR2(50) NOT NULL);
ALTER TABLE data_sources MODIFY port VARCHAR2(5) NULL;
ALTER TABLE data_sources MODIFY url VARCHAR2(255) NULL;
ALTER TABLE data_sources RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE data_sources MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE data_sources DROP COLUMN createtime;
ALTER TABLE data_sources DROP COLUMN lastmodified;
ALTER TABLE data_sources ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE data_sources ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE data_sources ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE data_sources ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE data_sources ADD version NUMBER(20) NULL;
CREATE INDEX created_at ON data_sources (created_at);
CREATE INDEX created_by ON data_sources (created_by);
CREATE INDEX last_modified_at ON data_sources (last_modified_at);
CREATE INDEX last_modified_by ON data_sources (last_modified_by);
CREATE INDEX tenant_id ON data_sources (tenant_id);
CREATE INDEX data_source_code ON data_sources (data_source_code);
CREATE INDEX data_source_type ON data_sources (data_source_type);
