ALTER TABLE user_groups RENAME TO user_groups_1;
ALTER TABLE user_groups_1 RENAME TO user_groups;
ALTER TABLE user_groups RENAME COLUMN usergroupid TO user_group_id;
ALTER TABLE user_groups MODIFY (user_group_id VARCHAR2(50) NOT NULL);
ALTER TABLE user_groups MODIFY description VARCHAR2(255) NULL;
ALTER TABLE user_groups RENAME COLUMN userids TO user_ids;
ALTER TABLE user_groups MODIFY (user_ids CLOB NULL);
ALTER TABLE user_groups RENAME COLUMN spaceids TO space_ids;
ALTER TABLE user_groups MODIFY (space_ids CLOB NULL);
ALTER TABLE user_groups RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE user_groups MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE user_groups DROP COLUMN createtime;
ALTER TABLE user_groups DROP COLUMN lastmodified;
ALTER TABLE user_groups ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE user_groups ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE user_groups ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE user_groups ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE user_groups ADD version NUMBER(20) NULL;
CREATE INDEX created_at ON user_groups (created_at);
CREATE INDEX created_by ON user_groups (created_by);
CREATE INDEX last_modified_at ON user_groups (last_modified_at);
CREATE INDEX last_modified_by ON user_groups (last_modified_by);
CREATE INDEX name ON user_groups (name);
CREATE INDEX tenant_id ON user_groups (tenant_id);
