ALTER TABLE users RENAME TO users_1;
ALTER TABLE users_1 RENAME TO users;
ALTER TABLE users RENAME COLUMN userid TO user_id;
ALTER TABLE users MODIFY (user_id VARCHAR2(50) NOT NULL);
ALTER TABLE users MODIFY nickname VARCHAR2(50) NULL;
ALTER TABLE users MODIFY password VARCHAR2(255) NULL;
ALTER TABLE users MODIFY is_active tinyint(1) NOT NULL;
ALTER TABLE users RENAME COLUMN groupids TO group_ids;
ALTER TABLE users MODIFY (group_ids CLOB NULL);
ALTER TABLE users MODIFY role VARCHAR2(20) NOT NULL;
ALTER TABLE users RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE users MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE users DROP COLUMN createtime;
ALTER TABLE users DROP COLUMN lastmodified;
ALTER TABLE users ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE users ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE users ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE users ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE users ADD version NUMBER(20) NULL;
CREATE INDEX created_at ON users (created_at);
CREATE INDEX created_by ON users (created_by);
CREATE INDEX last_modified_at ON users (last_modified_at);
CREATE INDEX last_modified_by ON users (last_modified_by);
CREATE INDEX role ON users (role);
CREATE INDEX tenant_id ON users (tenant_id);
CREATE UNIQUE INDEX name ON users (name);
