ALTER TABLE spaces RENAME TO spaces_1;
ALTER TABLE spaces_1 RENAME TO spaces;
ALTER TABLE spaces RENAME COLUMN spaceid TO space_id;
ALTER TABLE spaces MODIFY (space_id VARCHAR2(50) NOT NULL);
ALTER TABLE spaces MODIFY name VARCHAR2(50) NOT NULL;
ALTER TABLE spaces MODIFY description VARCHAR2(255) NULL;
ALTER TABLE spaces RENAME COLUMN topicids TO topic_ids;
ALTER TABLE spaces MODIFY (topic_ids CLOB NULL);
ALTER TABLE spaces RENAME COLUMN groupids TO group_ids;
ALTER TABLE spaces MODIFY (group_ids CLOB NULL);
ALTER TABLE spaces RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE spaces MODIFY (tenant_id VARCHAR2(50) NULL);
ALTER TABLE spaces DROP COLUMN createtime;
ALTER TABLE spaces DROP COLUMN lastmodified;
ALTER TABLE spaces ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE spaces ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE spaces ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE spaces ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE spaces ADD version NUMBER(20) NULL;
CREATE INDEX created_at ON spaces (created_at);
CREATE INDEX created_by ON spaces (created_by);
CREATE INDEX last_modified_at ON spaces (last_modified_at);
CREATE INDEX last_modified_by ON spaces (last_modified_by);
CREATE INDEX name ON spaces (name);
CREATE INDEX tenant_id ON spaces (tenant_id);
