ALTER TABLE console_spaces RENAME TO connected_spaces;
ALTER TABLE connected_spaces RENAME COLUMN connectid TO connect_id;
ALTER TABLE connected_spaces MODIFY (connect_id VARCHAR2(50) NOT NULL);
ALTER TABLE connected_spaces RENAME COLUMN spaceid TO space_id;
ALTER TABLE connected_spaces MODIFY (space_id VARCHAR2(50) NOT NULL);
ALTER TABLE connected_spaces MODIFY name VARCHAR2(50) NOT NULL;
ALTER TABLE connected_spaces DROP COLUMN type;
ALTER TABLE connected_spaces RENAME COLUMN istemplate TO is_template;
ALTER TABLE connected_spaces MODIFY (is_template NUMBER(1) NOT NULL);
ALTER TABLE connected_spaces DROP COLUMN subjects;
ALTER TABLE connected_spaces DROP COLUMN groupids;
ALTER TABLE connected_spaces RENAME COLUMN userid TO user_id;
ALTER TABLE connected_spaces MODIFY (user_id VARCHAR2(50) NOT NULL);
ALTER TABLE connected_spaces RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE connected_spaces MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE connected_spaces RENAME COLUMN lastvisittime TO last_visit_time;
ALTER TABLE connected_spaces MODIFY (last_visit_time DATE NOT NULL);
ALTER TABLE connected_spaces DROP COLUMN createtime;
ALTER TABLE connected_spaces DROP COLUMN lastmodified;
ALTER TABLE connected_spaces ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE connected_spaces ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE connected_spaces ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE connected_spaces ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
CREATE INDEX created_at ON connected_spaces (created_at);
CREATE INDEX created_by ON connected_spaces (created_by);
CREATE INDEX last_modified_at ON connected_spaces (last_modified_at);
CREATE INDEX last_modified_by ON connected_spaces (last_modified_by);
CREATE INDEX name ON connected_spaces (name);
CREATE INDEX space_id ON connected_spaces (space_id);
CREATE INDEX tenant_id ON connected_spaces (tenant_id);
CREATE INDEX user_id ON connected_spaces (user_id);
