ALTER TABLE reports RENAME TO reports_1;
ALTER TABLE reports_1 RENAME TO reports;
ALTER TABLE reports RENAME COLUMN reportid TO report_id;
ALTER TABLE reports MODIFY (report_id VARCHAR2(50) NOT NULL);
ALTER TABLE reports MODIFY name VARCHAR2(50) NOT NULL;
ALTER TABLE reports ADD connect_id VARCHAR2(50) NOT NULL;
ALTER TABLE reports ADD subject_id VARCHAR2(50) NOT NULL;
ALTER TABLE reports MODIFY description VARCHAR2(255) NULL;
ALTER TABLE reports MODIFY simulating NUMBER(1) NOT NULL;
ALTER TABLE reports RENAME COLUMN simulateData TO simulate_data;
ALTER TABLE reports MODIFY (simulate_data CLOB NULL);
ALTER TABLE reports RENAME COLUMN simulateThumbnail TO simulate_thumbnail;
ALTER TABLE reports MODIFY (simulate_thumbnail MEDIUMTEXT NULL);
ALTER TABLE reports ADD user_id VARCHAR2(50) NOT NULL;
ALTER TABLE reports RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE reports MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE reports RENAME COLUMN lastvisittime TO last_visit_time;
ALTER TABLE reports MODIFY (last_visit_time DATE NOT NULL);
ALTER TABLE reports DROP COLUMN createtime;
ALTER TABLE reports DROP COLUMN lastmodified;
ALTER TABLE reports DROP COLUMN createdat;
ALTER TABLE reports ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE reports ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE reports ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE reports ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
CREATE INDEX created_at ON reports (created_at);
CREATE INDEX created_by ON reports (created_by);
CREATE INDEX last_modified_at ON reports (last_modified_at);
CREATE INDEX last_modified_by ON reports (last_modified_by);
CREATE INDEX name ON reports (name);
CREATE INDEX user_id ON reports (user_id);
CREATE INDEX tenant_id ON reports (tenant_id);
