ALTER TABLE console_space_subjects RENAME TO subjects;
ALTER TABLE subjects RENAME COLUMN subjectid TO subject_id;
ALTER TABLE subjects MODIFY (subject_id VARCHAR2(50) NOT NULL);
ALTER TABLE subjects MODIFY name VARCHAR2(50) NOT NULL;
ALTER TABLE subjects DROP COLUMN topiccount;
ALTER TABLE subjects DROP COLUMN graphicscount;
ALTER TABLE subjects DROP COLUMN reports;
ALTER TABLE subjects ADD connect_id VARCHAR2(50) NOT NULL;
ALTER TABLE subjects ADD auto_refresh_interval NUMBER(20) NULL;
ALTER TABLE subjects ADD user_id VARCHAR2(50) NOT NULL;
ALTER TABLE subjects RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE subjects MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE subjects RENAME COLUMN lastvisittime TO last_visit_time;
ALTER TABLE subjects MODIFY (last_visit_time DATE NOT NULL);
ALTER TABLE subjects DROP COLUMN createdat;
ALTER TABLE subjects DROP COLUMN lastmodified;
ALTER TABLE subjects DROP COLUMN createtime;
ALTER TABLE subjects ADD (created_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE subjects ADD (created_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
ALTER TABLE subjects ADD (last_modified_at DATE DEFAULT SYSDATE NOT NULL);
ALTER TABLE subjects ADD (last_modified_by VARCHAR2(50) DEFAULT '-1' NOT NULL);
CREATE INDEX created_at ON subjects (created_at);
CREATE INDEX created_by ON subjects (created_by);
CREATE INDEX last_modified_at ON subjects (last_modified_at);
CREATE INDEX last_modified_by ON subjects (last_modified_by);
CREATE INDEX name ON subjects (name);
CREATE INDEX tenant_id ON subjects (tenant_id);
CREATE INDEX user_id ON subjects (user_id);
