ALTER TABLE console_space_favorites RENAME TO favorites;
ALTER TABLE favorites RENAME COLUMN connectedspaceids TO connected_space_ids;
ALTER TABLE favorites MODIFY (connected_space_ids CLOB);
ALTER TABLE favorites RENAME COLUMN dashboardids TO dashboard_ids;
ALTER TABLE favorites MODIFY (dashboard_ids CLOB);
ALTER TABLE favorites RENAME COLUMN userid TO user_id;
ALTER TABLE favorites MODIFY (user_id VARCHAR2(50) NOT NULL);
ALTER TABLE favorites RENAME COLUMN tenantid TO tenant_id;
ALTER TABLE favorites MODIFY (tenant_id VARCHAR2(50) NOT NULL);
ALTER TABLE favorites DROP COLUMN createtime;
ALTER TABLE favorites DROP COLUMN lastmodified;
ALTER TABLE favorites ADD last_visit_time DATE NOT NULL;
CREATE INDEX tenant_id ON favorites (tenant_id);
