RENAME TABLE console_spaces TO connected_spaces;
ALTER TABLE connected_spaces CHANGE connectid connect_id VARCHAR(50) NOT NULL;
ALTER TABLE connected_spaces CHANGE spaceid space_id VARCHAR(50) NOT NULL;
ALTER TABLE connected_spaces MODIFY name VARCHAR(50) NOT NULL;
ALTER TABLE connected_spaces DROP type;
ALTER TABLE connected_spaces CHANGE istemplate is_template TINYINT(1) NOT NULL;
ALTER TABLE connected_spaces DROP subjects;
ALTER TABLE connected_spaces DROP groupids;
ALTER TABLE connected_spaces CHANGE userid user_id VARCHAR(50) NOT NULL;
ALTER TABLE connected_spaces CHANGE tenantid tenant_id VARCHAR(50) NOT NULL;
ALTER TABLE connected_spaces CHANGE lastvisittime last_visit_time DATETIME NOT NULL;
ALTER TABLE connected_spaces DROP createtime;
ALTER TABLE connected_spaces DROP lastmodified;
ALTER TABLE connected_spaces ADD created_at DATETIME NOT NULL;
ALTER TABLE connected_spaces ADD created_by VARCHAR(50) NOT NULL;
ALTER TABLE connected_spaces ADD last_modified_at DATETIME NOT NULL;
ALTER TABLE connected_spaces ADD last_modified_by VARCHAR(50) NOT NULL;
CREATE INDEX created_at ON connected_spaces (created_at);
CREATE INDEX created_by ON connected_spaces (created_by);
CREATE INDEX last_modified_at ON connected_spaces (last_modified_at);
CREATE INDEX last_modified_by ON connected_spaces (last_modified_by);
CREATE INDEX name ON connected_spaces (name);
CREATE INDEX space_id ON connected_spaces (space_id);
CREATE INDEX tenant_id ON connected_spaces (tenant_id);
CREATE INDEX user_id ON connected_spaces (user_id);
