RENAME TABLE console_space_subjects TO subjects;
ALTER TABLE subjects CHANGE subjectid subject_id VARCHAR(50) NOT NULL;
ALTER TABLE subjects MODIFY name VARCHAR(50) NOT NULL;
ALTER TABLE subjects DROP topiccount;
ALTER TABLE subjects DROP graphicscount;
ALTER TABLE subjects DROP reports;
ALTER TABLE subjects DROP reportids;
ALTER TABLE subjects ADD connect_id VARCHAR(50) NOT NULL;
ALTER TABLE subjects ADD auto_refresh_interval BIGINT NULL;
ALTER TABLE subjects ADD user_id VARCHAR(50) NOT NULL;
ALTER TABLE subjects CHANGE tenantid tenant_id VARCHAR(50) NOT NULL;
ALTER TABLE subjects CHANGE lastvisittime last_visit_time DATETIME NOT NULL;
ALTER TABLE subjects DROP createdat;
ALTER TABLE subjects DROP lastmodified;
ALTER TABLE subjects DROP createtime;
ALTER TABLE subjects ADD created_at DATETIME NOT NULL;
ALTER TABLE subjects ADD created_by VARCHAR(50) NOT NULL;
ALTER TABLE subjects ADD last_modified_at DATETIME NOT NULL;
ALTER TABLE subjects ADD last_modified_by VARCHAR(50) NOT NULL;
CREATE INDEX created_at ON subjects (created_at);
CREATE INDEX created_by ON subjects (created_by);
CREATE INDEX last_modified_at ON subjects (last_modified_at);
CREATE INDEX last_modified_by ON subjects (last_modified_by);
CREATE INDEX name ON subjects (name);
CREATE INDEX tenant_id ON subjects (tenant_id);
CREATE INDEX user_id ON subjects (user_id);
