CREATE TABLE indicators
(
    indicator_id        VARCHAR(50) NOT NULL,
    name                VARCHAR(50),
    topic_or_subject_id VARCHAR(50),
    base_on             VARCHAR(10),
    factor_id           VARCHAR(50),
    category_1          VARCHAR(100),
    category_2          VARCHAR(100),
    category_3          VARCHAR(100),
    value_buckets       JSON,
    relevants           JSON,
    group_ids           JSON,
    filter              JSON,
    description         VARCHAR(1024),
    tenant_id           VARCHAR(50) NOT NULL,
    created_at          DATETIME    NOT NULL,
    created_by          VARCHAR(50) NOT NULL,
    last_modified_at    DATETIME    NOT NULL,
    last_modified_by    VARCHAR(50) NOT NULL,
    version             BIGINT,
    PRIMARY KEY (indicator_id),
    INDEX (name),
    INDEX (topic_or_subject_id),
    INDEX (BASE_ON),
    INDEX (category_1),
    INDEX (category_2),
    INDEX (category_3),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);
