CREATE TABLE snapshot_schedulers
(
    scheduler_id      VARCHAR(50) NOT NULL,
    topic_id          VARCHAR(50) NOT NULL,
    target_topic_name VARCHAR(50) NOT NULL,
    target_topic_id   VARCHAR(50) NOT NULL,
    pipeline_id       VARCHAR(50) NOT NULL,
    frequency         VARCHAR(20) NOT NULL,
    filter            JSON,
    weekday           VARCHAR(10),
    day               VARCHAR(10),
    hour              TINYINT,
    minute            TINYINT,
    enabled           TINYINT,
    tenant_id         VARCHAR(50) NOT NULL,
    created_at        DATETIME    NOT NULL,
    created_by        VARCHAR(50) NOT NULL,
    last_modified_at  DATETIME    NOT NULL,
    last_modified_by  VARCHAR(50) NOT NULL,
    version           BIGINT,
    PRIMARY KEY (scheduler_id),
    INDEX (topic_id),
    INDEX (target_topic_id),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);
