import { SemanticModelMeasure, SemanticModelDimension } from '@/model/semanticModel';
import { Topic } from '@/services/topicService';

interface AutoGenerateOptions {
  formData: SemanticModel;
  setFormData: React.Dispatch<React.SetStateAction<SemanticModel>>;
  topics: Topic[];
  toast: (options: { title: string; description?: string; variant?: 'destructive' | 'default' }) => void;
  measuresEndRef: React.RefObject<HTMLDivElement | null>;
  dimensionsEndRef: React.RefObject<HTMLDivElement | null>;
  t: (key: string, options?: Record<string, unknown>) => string;
}

export function useAutoGenerate({
  formData,
  setFormData,
  topics,
  toast,
  measuresEndRef,
  dimensionsEndRef,
  t
}: AutoGenerateOptions) {
  const autoGenerateMeasures = () => {
    if (!formData.topicId) {
      toast({
        title: t('common:error'),
        description: t('semanticModel:toast.topicRequired'),
        variant: "destructive"
      });
      return;
    }

    const topic = topics.find(tp => tp.id === formData.topicId);
    if (!topic || !topic.factors) {
      toast({
        title: t('common:error'),
        description: t('semanticModel:toast.topicInvalid'),
        variant: "destructive"
      });
      return;
    }

    const newMeasures: SemanticModelMeasure[] = [];

    topic.factors.forEach(factor => {
      const isNumeric = ['number', 'unsigned', 'integer', 'decimal'].includes(factor.type);
      const isId = factor.name.toLowerCase() === 'id' || factor.name.toLowerCase().endsWith('id');

      if (isId) {
        newMeasures.push({
          name: `${factor.name}_count`,
          agg: 'count',
          description: `Count of ${factor.label || factor.name}`,
          create_metric: false,
          expr: factor.name,
          agg_params: null,
          metadata: null,
          non_additive_dimension: null,
          agg_time_dimension: null,
          label: factor.label
        });
      } else if (isNumeric) {
        newMeasures.push({
          name: `${factor.name}_sum`,
          agg: 'sum',
          description: `Sum of ${factor.label || factor.name}`,
          create_metric: false,
          expr: factor.name,
          agg_params: null,
          metadata: null,
          non_additive_dimension: null,
          agg_time_dimension: null,
          label: factor.label
        });
      }
    });

    if (newMeasures.length === 0) {
      toast({
        title: t('common:loading'),
        description: t('semanticModel:toast.noMeasuresGenerated'),
      });
      return;
    }

    setFormData(prev => ({
      ...prev,
      measures: [...prev.measures, ...newMeasures]
    }));

    toast({
      title: t('common:success'),
      description: t('semanticModel:toast.measuresGenerated', { count: newMeasures.length }),
    });

    setTimeout(() => {
      measuresEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, 100);
  };

  const autoGenerateDimensions = () => {
    if (!formData.topicId) {
      toast({
        title: t('common:error'),
        description: t('semanticModel:toast.topicRequired'),
        variant: "destructive"
      });
      return;
    }

    const topic = topics.find(tp => tp.id === formData.topicId);
    if (!topic || !topic.factors) {
      toast({
        title: t('common:error'),
        description: t('semanticModel:toast.topicInvalid'),
        variant: "destructive"
      });
      return;
    }

    const newDimensions: SemanticModelDimension[] = [];

    topic.factors.forEach(factor => {
      if (['object', 'array'].includes(factor.type)) return;

      const isTime = ['datetime', 'full-datetime', 'date', 'time', 'year', 'month', 'week', 'day', 'hour', 'minute', 'second'].some(t => factor.type.includes(t));

      if (isTime) {
        newDimensions.push({
          name: `${factor.name}`,
          description: factor.label || factor.name,
          type: 'time',
          is_partition: false,
          type_params: {
            time_granularity: 'day',
            validity_params: null
          },
          expr: factor.name,
          metadata: null,
          label: factor.label
        });
      } else {
        const isNumeric = ['number', 'unsigned', 'integer', 'decimal'].includes(factor.type);
        const isId = factor.name.toLowerCase() === 'id' || factor.name.toLowerCase().endsWith('id');

        if (isNumeric || isId) return;

        newDimensions.push({
          name: `${factor.name}`,
          description: factor.label || factor.name,
          type: 'categorical',
          is_partition: false,
          type_params: null,
          expr: factor.name,
          metadata: null,
          label: factor.label
        });
      }
    });

    if (newDimensions.length === 0) {
      toast({
        title: t('common:loading'),
        description: t('semanticModel:toast.noDimensionsGenerated'),
      });
      return;
    }

    setFormData(prev => ({
      ...prev,
      dimensions: [...prev.dimensions, ...newDimensions]
    }));

    toast({
      title: t('common:success'),
      description: t('semanticModel:toast.dimensionsGenerated', { count: newDimensions.length }),
    });

    setTimeout(() => {
      dimensionsEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, 100);
  };

  return { autoGenerateMeasures, autoGenerateDimensions };
}
