[tool.poetry]
name = "watchmen-rest-indicator"
version = "16.1.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_rest_indicator", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
watchmen-indicator-surface = { path = "../watchmen-indicator-surface", develop = true }
watchmen-rest-doll = { path = "../watchmen-rest-doll", develop = true }
watchmen-storage-mysql = { path = "../watchmen-storage-mysql", develop = true, optional = true }
watchmen-storage-oracle = { path = "../watchmen-storage-oracle", develop = true, optional = true }
watchmen-storage-mongodb = { path = "../watchmen-storage-mongodb", develop = true, optional = true }
watchmen-storage-mssql = { path = "../watchmen-storage-mssql", develop = true, optional = true }
watchmen-storage-postgresql = { path = "../watchmen-storage-postgresql", develop = true, optional = true }
kafka-python = { version = "^2.0.2", optional = true }
aiokafka = { version = "^0.7.2", optional = true }
aio-pika = { version = "^7.1.2", optional = true }
starlette-prometheus = { version = "^0.9.0", optional = true }
requests = { version = "^2.27.1", optional = true }
python3-saml = { version = "^1.14.0", optional = true }
cryptography = { version = "^36.0.2", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
trino = ["watchmen-inquiry-trino"]
mysql = ["watchmen-storage-mysql"]
oracle = ["watchmen-storage-oracle"]
mongodb = ["watchmen-storage-mongodb"]
mssql = ["watchmen-storage-mssql"]
postgresql = ["watchmen-storage-postgresql"]
kafka = ["kafka-python", "aiokafka"]
rabbit = ["aio-pika"]
prometheus = ["starlette-prometheus"]
standard_ext_writer = ["requests"]
es_ext_writer = []
sso = ["python3-saml", "cryptography"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
