CREATE TABLE change_data_record
(
    change_record_id    BIGINT      NOT NULL,
    model_name          VARCHAR(50) NOT NULL,
    table_name          VARCHAR(50) NOT NULL,
    data_id             VARCHAR(50) NOT NULL,
    root_table_name     VARCHAR(50),
    root_data_id        VARCHAR(50),
    is_merged           TINYINT  NOT NULL,
    table_trigger_id    VARCHAR(50) NOT NULL,
    model_trigger_id    VARCHAR(50) NOT NULL,
    event_trigger_id    VARCHAR(50) NOT NULL,
    tenant_id           VARCHAR(50) NOT NULL,
    created_at          DATETIME    NOT NULL,
    created_by          VARCHAR(50) NOT NULL,
    last_modified_at    DATETIME    NOT NULL,
    last_modified_by    VARCHAR(50) NOT NULL,
    PRIMARY KEY (change_record_id),
    UNIQUE KEY unique_data(table_trigger_id, table_name, data_id),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);