CREATE TABLE change_data_record
(
    change_record_id        BIGINT      NOT NULL,
    model_name              VARCHAR(50) NOT NULL,
    table_name              VARCHAR(50) NOT NULL,
    data_id                 JSON        NOT NULL,
    root_table_name         VARCHAR(50),
    root_data_id            JSON,
    is_merged               TINYINT     NOT NULL,
    status                  TINYINT     NOT NULL,
    result                  JSON,
    table_trigger_id        BIGINT      NOT NULL,
    model_trigger_id        BIGINT      NOT NULL,
    module_trigger_id       BIGINT      NOT NULL,
    event_trigger_id        BIGINT      NOT NULL,
    tenant_id               VARCHAR(50) NOT NULL,
    created_at              DATETIME    NOT NULL,
    created_by              VARCHAR(50) NOT NULL,
    last_modified_at        DATETIME    NOT NULL,
    last_modified_by        VARCHAR(50) NOT NULL,
    PRIMARY KEY (change_record_id),
    INDEX (table_trigger_id),
    INDEX (model_trigger_id),
    INDEX (module_trigger_id),
    INDEX (event_trigger_id),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);