from watchmen_indicator_surface import get_indicator_surface_routers
from watchmen_rest_doll.admin import sync_user_group_change
from watchmen_rest_doll.main import app
from watchmen_rest_doll.meta_import import mix_import_handle
from watchmen_utilities import ArrayHelper
from .sync_user_group_change import UserGroupChangeHandler
from .indicators_import import IndicatorsImportHandler

sync_user_group_change.register_indicator_handler(UserGroupChangeHandler())
mix_import_handle.register_indicator_handler(IndicatorsImportHandler())
ArrayHelper(get_indicator_surface_routers()).each(lambda x: app.include_router(x))
