CREATE TABLE reports
(
    report_id          VARCHAR(50) NOT NULL,
    name               VARCHAR(50) NOT NULL,
    connect_id         VARCHAR(50) NOT NULL,
    subject_id         VARCHAR(50) NOT NULL,
    description        VARCHAR(1024),
    filters            JSON,
    funnels            JSON,
    indicators         JSON,
    dimensions         JSON,
    rect               JSON,
    chart              JSON,
    simulating         TINYINT(1)  NOT NULL,
    simulate_data      JSON,
    simulate_thumbnail MEDIUMTEXT,
    user_id            VARCHAR(50) NOT NULL,
    tenant_id          VARCHAR(50) NOT NULL,
    last_visit_time    DATETIME    NULL,
    created_at         DATETIME    NOT NULL,
    created_by         VARCHAR(50) NOT NULL,
    last_modified_at   DATETIME    NOT NULL,
    last_modified_by   VARCHAR(50) NOT NULL,
    PRIMARY KEY (report_id),
    INDEX (name),
    INDEX (user_id),
    INDEX (tenant_id),
    INDEX (created_at),
    INDEX (created_by),
    INDEX (last_modified_at),
    INDEX (last_modified_by)
);
