[tool.poetry]
name = "watchmen-webhook"
version = "16.5.0"
description = ""
authors = ["luke0623 <luke0623@outlook.com>"]
readme = "README.md"
packages = [{include = "watchmen_webhook"}]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
