"""Proposal model - agents propose changes to the ontology."""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ProposalAction(str, Enum):
    """Types of actions an agent can propose."""
    ADD_NODE = "add_node"
    UPDATE_NODE = "update_node"
    ADD_RELATION = "add_relation"
    UPDATE_RELATION = "update_relation"
    ADD_ATTRIBUTE = "add_attribute"
    UPDATE_HEALTH = "update_health"
    ADD_DATA_SOURCE = "add_data_source"


class ProposalStatus(str, Enum):
    """Status of a proposal in the governance workflow."""
    PENDING = "pending"          # Waiting for review
    APPROVED = "approved"        # Approved, ready to materialize
    REJECTED = "rejected"        # Rejected
    MATERIALIZED = "materialized"  # Successfully applied
    FAILED = "failed"            # Materialization failed


class Proposal(BaseModel):
    """A proposal to change the ontology, generated by an agent."""
    proposal_id: str
    agent_type: str  # architect, materialization, health, insight
    action: ProposalAction
    target_node_id: Optional[str] = None
    target_relation_id: Optional[str] = None
    payload: Dict[str, Any] = Field(default_factory=dict)  # Action-specific data
    rationale: str  # Why this change is proposed
    confidence: float = Field(ge=0, le=1, description="Agent's confidence in this proposal")
    status: ProposalStatus = ProposalStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    decided_at: Optional[datetime] = None
    decided_by: Optional[str] = None  # User or system that made the decision
    decision_notes: Optional[str] = None

    def approve(self, decided_by: str, notes: Optional[str] = None) -> None:
        """Approve this proposal."""
        self.status = ProposalStatus.APPROVED
        self.decided_at = datetime.utcnow()
        self.decided_by = decided_by
        self.decision_notes = notes
        self.updated_at = datetime.utcnow()

    def reject(self, decided_by: str, notes: Optional[str] = None) -> None:
        """Reject this proposal."""
        self.status = ProposalStatus.REJECTED
        self.decided_at = datetime.utcnow()
        self.decided_by = decided_by
        self.decision_notes = notes
        self.updated_at = datetime.utcnow()

    def mark_materialized(self) -> None:
        """Mark as successfully materialized."""
        self.status = ProposalStatus.MATERIALIZED
        self.updated_at = datetime.utcnow()

    def mark_failed(self, error: str) -> None:
        """Mark as failed during materialization."""
        self.status = ProposalStatus.FAILED
        self.decision_notes = error
        self.updated_at = datetime.utcnow()
