[tool.poetry]
name = "watchmen-reactor-surface"
version = "16.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_reactor_surface", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
watchmen-reactor-service = { path = "../watchmen-reactor-service", develop = true }
watchmen-storage-mysql = { path = "../watchmen-storage-mysql", develop = true, optional = true }
kafka-python = { version = "^2.0.2", optional = true }
aiokafka = { version = "^0.7.2", optional = true }
aio-pika = { version = "^6.8.2", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
mysql = ["watchmen-storage-mysql"]
kafka = ["kafka-python", "aiokafka"]
rabbitmq = ["aio-pika"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
