import {
	AppState,
	MainNavKey,
	DataSource,
	Topic,
	Pipeline,
	PerceiveScenario,
	AgentLog,
	ObservabilityEdge,
	ObservabilityEvent,
	ObservabilityImpactItem,
	ObservabilityKpi,
	ObservabilityNode,
	ObservabilityStageHealth,
	GovernRule,
	MaskingPolicy,
} from "./models";

export const mainNav: Array<{ key: MainNavKey; label: string; icon: string }> = [
	{ key: "observe", label: "Observe", icon: "◌" },
	{ key: "perceive", label: "Perceive", icon: "◎" },
	{ key: "ingest", label: "Ingest", icon: "⬡" },
	{ key: "transform", label: "Transform", icon: "⟳" },
	{ key: "model", label: "Model", icon: "◫" },
	{ key: "govern", label: "Govern", icon: "⛨" },
	{ key: "feedback", label: "Feedback", icon: "↺" },
	{ key: "settings", label: "Settings", icon: "⚙" },
];

export const initialDataSources: DataSource[] = [
	{
		dataSourceId: "ds-1",
		dataSourceCode: "mysql_sales",
		dataSourceType: "mysql",
		host: "192.168.1.10",
		name: "Sales Production DB",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:30:00",
		recordCount: 45200000,
		domain: "commerce",
	},
	{
		dataSourceId: "ds-2",
		dataSourceCode: "pg_analytics",
		dataSourceType: "postgresql",
		host: "192.168.1.20",
		name: "Analytics DW",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:45:00",
		recordCount: 128000000,
		domain: "commerce",
	},
	{
		dataSourceId: "ds-3",
		dataSourceCode: "mongo_users",
		dataSourceType: "mongodb",
		host: "192.168.2.15",
		name: "User Profile Store",
		healthStatus: "warning",
		lastSync: "2026-05-26 07:52:00",
		recordCount: 8900000,
		domain: "user",
	},
	{
		dataSourceId: "ds-4",
		dataSourceCode: "oracle_finance",
		dataSourceType: "oracle",
		host: "192.168.3.5",
		name: "Finance Ledger DB",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:00:00",
		recordCount: 21000000,
		domain: "finance",
	},
	{
		dataSourceId: "ds-5",
		dataSourceCode: "s3_event_logs",
		dataSourceType: "s3",
		name: "Event Log Archive",
		url: "s3://data-lake/events/",
		healthStatus: "error",
		lastSync: "2026-05-25 23:15:00",
		recordCount: 345000000,
		domain: "platform",
	},
	{
		dataSourceId: "ds-6",
		dataSourceCode: "mssql_risk",
		dataSourceType: "mssql",
		host: "192.168.4.10",
		name: "Risk Assessment DB",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:15:00",
		recordCount: 5600000,
		domain: "risk",
	},
	{
		dataSourceId: "ds-7",
		dataSourceCode: "snowflake_dw",
		dataSourceType: "snowflake",
		name: "Snowflake Data Warehouse",
		url: "snowflake://acct/data_mart",
		healthStatus: "healthy",
		lastSync: "2026-05-26 09:00:00",
		recordCount: 890000000,
		domain: "commerce",
	},
];

export const initialTopics: Topic[] = [
	{
		topicId: "t-1",
		name: "sales_order_raw",
		type: "raw",
		kind: "business",
		dataSourceId: "ds-1",
		factors: [
			{ factorId: "f-1", name: "order_id", label: "Order ID", type: "text" },
			{ factorId: "f-2", name: "amount", label: "Amount", type: "number" },
			{ factorId: "f-3", name: "customer_id", label: "Customer ID", type: "text" },
		],
		description: "Raw sales order data from MySQL",
		domain: "commerce",
		recordCount: 45200000,
		healthStatus: "warning",
	},
	{
		topicId: "t-2",
		name: "user_profile",
		type: "raw",
		kind: "business",
		dataSourceId: "ds-3",
		factors: [
			{ factorId: "f-4", name: "user_id", label: "User ID", type: "text" },
			{ factorId: "f-5", name: "email", label: "Email", type: "text" },
			{ factorId: "f-6", name: "phone", label: "Phone", type: "text" },
		],
		description: "User profile data from MongoDB",
		domain: "user",
		recordCount: 8900000,
		healthStatus: "warning",
	},
	{
		topicId: "t-3",
		name: "finance_transactions",
		type: "raw",
		kind: "business",
		dataSourceId: "ds-4",
		factors: [
			{ factorId: "f-7", name: "txn_id", label: "Transaction ID", type: "text" },
			{ factorId: "f-8", name: "paid_amount", label: "Paid Amount", type: "number" },
			{ factorId: "f-9", name: "payment_method", label: "Payment Method", type: "text" },
		],
		description: "Financial transaction records from Oracle",
		domain: "finance",
		recordCount: 21000000,
		healthStatus: "healthy",
	},
	{
		topicId: "t-4",
		name: "sales_order_curated",
		type: "meta",
		kind: "business",
		factors: [
			{ factorId: "f-10", name: "order_id", label: "Order ID", type: "text" },
			{ factorId: "f-11", name: "paid_amount", label: "Paid Amount", type: "number" },
			{ factorId: "f-12", name: "customer_id", label: "Customer ID", type: "text" },
			{ factorId: "f-13", name: "order_status", label: "Order Status", type: "text" },
			{ factorId: "f-14", name: "created_at", label: "Created At", type: "datetime" },
		],
		description: "Curated order fact topic with enriched fields",
		domain: "commerce",
		recordCount: 44800000,
		healthStatus: "warning",
	},
	{
		topicId: "t-5",
		name: "daily_gmv_aggregate",
		type: "aggregate",
		kind: "business",
		factors: [
			{ factorId: "f-15", name: "report_date", label: "Report Date", type: "date" },
			{ factorId: "f-16", name: "total_gmv", label: "Total GMV", type: "number" },
			{ factorId: "f-17", name: "order_count", label: "Order Count", type: "number" },
		],
		description: "Daily GMV aggregate from curated orders",
		domain: "finance",
		recordCount: 365,
		healthStatus: "warning",
	},
	{
		topicId: "t-6",
		name: "risk_scores",
		type: "ratio",
		kind: "business",
		dataSourceId: "ds-6",
		factors: [
			{ factorId: "f-18", name: "order_id", label: "Order ID", type: "text" },
			{ factorId: "f-19", name: "risk_score", label: "Risk Score", type: "number" },
			{ factorId: "f-20", name: "fraud_flag", label: "Fraud Flag", type: "boolean" },
		],
		description: "Risk assessment scores for orders",
		domain: "risk",
		recordCount: 5600000,
		healthStatus: "error",
	},
	{
		topicId: "t-7",
		name: "event_clickstream",
		type: "raw",
		kind: "system",
		dataSourceId: "ds-5",
		factors: [
			{ factorId: "f-21", name: "event_id", label: "Event ID", type: "text" },
			{ factorId: "f-22", name: "event_type", label: "Event Type", type: "text" },
			{ factorId: "f-23", name: "page_url", label: "Page URL", type: "text" },
		],
		description: "Raw clickstream events from S3 archive",
		domain: "platform",
		recordCount: 345000000,
		healthStatus: "error",
	},
];

export const initialPipelines: Pipeline[] = [
	{
		pipelineId: "p-1",
		topicId: "t-1",
		name: "sync_sales_order_to_dw",
		type: "insert-or-merge",
		enabled: true,
		validated: true,
		healthStatus: "error",
		lastRun: "2026-05-26 09:42:11",
	},
	{
		pipelineId: "p-2",
		topicId: "t-2",
		name: "sync_user_profile",
		type: "merge",
		enabled: true,
		validated: true,
		healthStatus: "warning",
		lastRun: "2026-05-26 09:30:00",
	},
	{
		pipelineId: "p-3",
		topicId: "t-3",
		name: "finance_txn_to_curated",
		type: "insert",
		enabled: true,
		validated: true,
		healthStatus: "healthy",
		lastRun: "2026-05-26 09:45:00",
	},
	{
		pipelineId: "p-4",
		topicId: "t-4",
		name: "curate_sales_order",
		type: "insert-or-merge",
		enabled: true,
		validated: false,
		healthStatus: "warning",
		lastRun: "2026-05-26 09:35:00",
	},
	{
		pipelineId: "p-5",
		topicId: "t-5",
		name: "compute_daily_gmv",
		type: "insert",
		enabled: true,
		validated: true,
		healthStatus: "healthy",
		lastRun: "2026-05-26 06:00:00",
	},
	{
		pipelineId: "p-6",
		topicId: "t-6",
		name: "refresh_risk_scores",
		type: "merge",
		enabled: true,
		validated: true,
		healthStatus: "error",
		lastRun: "2026-05-26 08:15:00",
	},
	{
		pipelineId: "p-7",
		topicId: "t-7",
		name: "archive_clickstream",
		type: "insert",
		enabled: false,
		validated: true,
		healthStatus: "healthy",
		lastRun: "2026-05-25 23:59:00",
	},
];

export const initialGovernRules: GovernRule[] = [
	{
		ruleId: "gr-1",
		name: "Order Amount > 0",
		description: "Validates that every order has a positive amount value",
		category: "validity",
		severity: "critical",
		targetTopic: "sales_order_raw",
		targetFactor: "amount",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 99.97,
	},
	{
		ruleId: "gr-2",
		name: "Customer ID Format",
		description: "Ensures customer_id matches ^CUST-\\d{8}$ pattern",
		category: "validity",
		severity: "critical",
		targetTopic: "sales_order_raw",
		targetFactor: "customer_id",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 97.7,
	},
	{
		ruleId: "gr-3",
		name: "Duplicate Order Detection",
		description: "Detects duplicate order_id within 24-hour window",
		category: "uniqueness",
		severity: "warning",
		targetTopic: "sales_order_raw",
		targetFactor: "order_id",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 99.99,
	},
	{
		ruleId: "gr-4",
		name: "Freshness SLA - Raw Order",
		description: "Raw order topic must sync within 10 minutes",
		category: "freshness",
		severity: "warning",
		targetTopic: "sales_order_raw",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 94.2,
	},
	{
		ruleId: "gr-5",
		name: "Email Format Check",
		description: "Validates email field format for user profiles",
		category: "validity",
		severity: "warning",
		targetTopic: "user_profile",
		targetFactor: "email",
		enabled: true,
		lastChecked: "2026-05-26 09:30:00",
		passRate: 99.5,
	},
	{
		ruleId: "gr-6",
		name: "Txn Amount Non-Null",
		description: "Finance transaction paid_amount must never be null",
		category: "completeness",
		severity: "critical",
		targetTopic: "finance_transactions",
		targetFactor: "paid_amount",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 99.99,
	},
	{
		ruleId: "gr-7",
		name: "Risk Score Range",
		description: "Risk scores must be between 0 and 100",
		category: "validity",
		severity: "critical",
		targetTopic: "risk_scores",
		targetFactor: "risk_score",
		enabled: true,
		lastChecked: "2026-05-26 09:15:00",
		passRate: 98.1,
	},
	{
		ruleId: "gr-8",
		name: "GMV Consistency Check",
		description: "Daily GMV must reconcile with sum of individual orders",
		category: "consistency",
		severity: "warning",
		targetTopic: "daily_gmv_aggregate",
		enabled: true,
		lastChecked: "2026-05-26 06:30:00",
		passRate: 96.8,
	},
];

export const initialMaskingPolicies: MaskingPolicy[] = [
	{
		policyId: "mp-1",
		name: "Mask User Email",
		targetTopic: "user_profile",
		targetFactor: "email",
		strategy: "partial_mask",
		enabled: true,
		appliesTo: ["analyst", "viewer"],
	},
	{
		policyId: "mp-2",
		name: "Tokenize Customer ID",
		targetTopic: "sales_order_curated",
		targetFactor: "customer_id",
		strategy: "tokenize",
		enabled: true,
		appliesTo: ["analyst", "viewer", "developer"],
	},
	{
		policyId: "mp-3",
		name: "Redact Phone Number",
		targetTopic: "user_profile",
		targetFactor: "phone",
		strategy: "redact",
		enabled: true,
		appliesTo: ["viewer"],
	},
	{
		policyId: "mp-4",
		name: "Hash Payment Method",
		targetTopic: "finance_transactions",
		targetFactor: "payment_method",
		strategy: "sha256",
		enabled: false,
		appliesTo: ["viewer"],
	},
];

export const initialPerceiveScenarios: PerceiveScenario[] = [
	{
		id: "perceive-1",
		title: "Order Amount Distribution Drift",
		description:
			"Significant rightward shift detected in order amounts over the past 24 hours. Mean rose from 316 to 402, P95 from 1,380 to 1,740. Possible causes include promotional activity or anomalous order influx. Recommend reviewing alert thresholds.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-30 10:12:08",
		status: "pending",
		severity: "critical",
		confidence: 92,
		driftMetrics: [
			{ label: "P50", baseline: 219, current: 258, unit: "CNY" },
			{ label: "P95", baseline: 1380, current: 1740, unit: "CNY" },
			{ label: "Mean", baseline: 316, current: 402, unit: "CNY" },
		],
		proposedChanges: [
			{ field: "amount_alert_threshold", baseline: "1200", current: "1600", impact: "high" },
			{ field: "drift_detection_window", baseline: "7d", current: "14d", impact: "medium" },
			{
				field: "notification_channel",
				baseline: "slack:data-alert",
				current: "slack:data-alert + email:oncall",
				impact: "low",
			},
		],
	},
	{
		id: "perceive-2",
		title: "Customer ID Format Anomalies",
		description:
			"Over the past 6 hours, 1,247 non-standard customer_id records detected (2.3%), far exceeding the 0.1% baseline. Likely caused by upstream data entry rule changes.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-30 08:45:32",
		status: "pending",
		severity: "warning",
		confidence: 87,
		driftMetrics: [
			{ label: "Anomaly Rate", baseline: 0.1, current: 2.3, unit: "%" },
			{ label: "Anomaly Records", baseline: 54, current: 1247, unit: "" },
			{ label: "Affected Fields", baseline: 1, current: 3, unit: "" },
		],
		proposedChanges: [
			{ field: "customer_id_regex", baseline: "^CUST-\\d{8}$", current: "^CUST-\\d{8,12}$", impact: "high" },
			{ field: "quality_rule_action", baseline: "reject", current: "quarantine", impact: "medium" },
		],
	},
	{
		id: "perceive-3",
		title: "New Field Suggestion: payment_method",
		description:
			"AI detected a new payment_method field in the source system over the past week (coverage 98.7%). Recommend syncing it to the Topic to improve data completeness.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-29 22:10:15",
		status: "approved",
		severity: "info",
		confidence: 96,
		driftMetrics: [
			{ label: "Field Coverage", baseline: 0, current: 98.7, unit: "%" },
			{ label: "Daily Records", baseline: 0, current: 15234, unit: "" },
			{ label: "Unique Values", baseline: 0, current: 5, unit: "" },
		],
		proposedChanges: [
			{ field: "add_factor", baseline: "—", current: "payment_method (text)", impact: "medium" },
			{ field: "pipeline_rebuild", baseline: "No", current: "Yes", impact: "low" },
		],
	},
	{
		id: "perceive-4",
		title: "Data Latency Alert Recovered",
		description:
			"Sales Production DB sync latency has recovered to <5s. The previous 45s delay caused by network jitter has resolved automatically. Alert has been auto-downgraded.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-29 18:30:00",
		status: "rejected",
		severity: "info",
		confidence: 78,
		driftMetrics: [
			{ label: "Sync Latency", baseline: 2.1, current: 3.8, unit: "s" },
			{ label: "Failure Rate", baseline: 0, current: 0.02, unit: "%" },
			{ label: "Throughput", baseline: 1240, current: 1198, unit: "rows/s" },
		],
		proposedChanges: [{ field: "latency_alert_threshold", baseline: "30s", current: "60s", impact: "low" }],
	},
];

export const initialAgentLogs: AgentLog[] = [
	{
		id: "log-1",
		timestamp: "2026-03-30 10:12:08",
		action: "detected",
		scenarioId: "perceive-1",
		content: "Significant order amount distribution drift detected on sales_order_raw, P95 shifted +26.1%",
	},
	{
		id: "log-2",
		timestamp: "2026-03-30 10:12:09",
		action: "analyzed",
		scenarioId: "perceive-1",
		content: "Analysis: likely caused by promotional activity or anomalous order influx, confidence 92%",
	},
	{
		id: "log-3",
		timestamp: "2026-03-30 10:12:10",
		action: "suggested",
		scenarioId: "perceive-1",
		content: "Suggestion: raise alert threshold 1200→1600, extend detection window 7d→14d",
	},
	{
		id: "log-4",
		timestamp: "2026-03-30 08:45:32",
		action: "detected",
		scenarioId: "perceive-2",
		content: "customer_id format anomaly rate surged from 0.1% to 2.3%",
	},
	{
		id: "log-5",
		timestamp: "2026-03-30 08:45:33",
		action: "analyzed",
		scenarioId: "perceive-2",
		content: "Correlation: anomalies concentrated in 3 upstream write channels",
	},
	{
		id: "log-6",
		timestamp: "2026-03-30 08:45:34",
		action: "suggested",
		scenarioId: "perceive-2",
		content: "Suggestion: relax regex matching rules, change quality_rule_action from reject to quarantine",
	},
	{
		id: "log-7",
		timestamp: "2026-03-29 22:10:15",
		action: "detected",
		scenarioId: "perceive-3",
		content: "New payment_method field detected in source system, coverage 98.7%",
	},
	{
		id: "log-8",
		timestamp: "2026-03-29 22:10:16",
		action: "suggested",
		scenarioId: "perceive-3",
		content: "Suggestion: sync this field and rebuild pipeline",
	},
	{
		id: "log-9",
		timestamp: "2026-03-29 18:30:00",
		action: "info",
		scenarioId: "perceive-4",
		content: "Data sync latency recovered, alert auto-downgraded",
	},
];

export const initialObservabilityKpis: ObservabilityKpi[] = [
	{
		label: "Total Assets",
		value: "3,482",
		sub: "Topics, pipelines, semantics, metrics and consumption assets",
		tone: "blue",
	},
	{ label: "Healthy", value: "3,106", sub: "Assets within freshness and execution SLA", tone: "green" },
	{ label: "Warnings", value: "274", sub: "Delayed, partial or drifted dependencies", tone: "orange" },
	{ label: "Errors", value: "102", sub: "Blocking failures with active downstream impact", tone: "gray" },
];

export const initialObservabilityStageHealth: ObservabilityStageHealth[] = [
	{ stage: "ingest", healthy: 186, warning: 21, error: 5 },
	{ stage: "raw", healthy: 742, warning: 64, error: 17 },
	{ stage: "pipeline", healthy: 268, warning: 33, error: 11 },
	{ stage: "topic", healthy: 911, warning: 72, error: 14 },
	{ stage: "semantic", healthy: 204, warning: 27, error: 8 },
	{ stage: "metric", healthy: 662, warning: 48, error: 29 },
	{ stage: "consumption", healthy: 133, warning: 9, error: 18 },
];

export const initialObservabilityNodes: ObservabilityNode[] = [
	{
		id: "source-mysql-sales",
		stage: "ingest",
		type: "source_system",
		name: "mysql_sales",
		label: "Sales Production DB",
		description: "Primary OLTP source for order transactions.",
		healthStatus: "healthy",
		badges: ["mysql", "low-latency"],
		metadata: { owner: "commerce-platform", region: "cn-shanghai", domain: "commerce" },
	},
	{
		id: "table-orders",
		stage: "ingest",
		type: "source_table",
		name: "sales_order",
		label: "sales_order",
		description: "Source order header table.",
		healthStatus: "warning",
		badges: ["freshness +18m"],
		metadata: { database: "sales_prod", schema: "public", domain: "commerce" },
	},
	{
		id: "topic-sales-order-raw",
		stage: "raw",
		type: "raw_topic",
		name: "sales_order_raw",
		label: "sales_order_raw",
		description: "Raw sales order landing topic.",
		healthStatus: "warning",
		badges: ["stale", "raw"],
		metadata: { records24h: 1523400, freshnessMinutes: 18, domain: "commerce" },
	},
	{
		id: "factor-order-amount",
		stage: "raw",
		type: "raw_factor",
		name: "amount",
		label: "Order Amount",
		healthStatus: "warning",
		badges: ["drift +27%"],
		metadata: { type: "number", domain: "commerce" },
	},
	{
		id: "pipeline-sync-sales-order",
		stage: "pipeline",
		type: "pipeline",
		name: "sync_sales_order_to_dw",
		label: "Sync Sales Order To DW",
		description: "Transforms raw order events into curated order facts.",
		healthStatus: "error",
		badges: ["2 failed runs", "retrying"],
		metadata: { enabled: true, validated: true, lastFailure: "2026-03-30 09:42:11", domain: "commerce" },
	},
	{
		id: "topic-sales-order-standard",
		stage: "topic",
		type: "topic",
		name: "sales_order",
		label: "sales_order",
		description: "Curated order fact topic.",
		healthStatus: "warning",
		badges: ["downstream impacted"],
		metadata: { factors: 14, domain: "commerce" },
	},
	{
		id: "factor-paid-amount",
		stage: "topic",
		type: "factor",
		name: "paid_amount",
		label: "Paid Amount",
		healthStatus: "warning",
		badges: ["mapped"],
		metadata: { sourceFactor: "amount", domain: "commerce" },
	},
	{
		id: "semantic-orders-finance",
		stage: "semantic",
		type: "semantic_model",
		name: "orders_finance",
		label: "Orders Finance",
		description: "Semantic layer for commerce finance metrics.",
		healthStatus: "warning",
		badges: ["topic-linked"],
		metadata: { topic: "sales_order", domain: "finance" },
	},
	{
		id: "measure-paid-amount",
		stage: "semantic",
		type: "semantic_measure",
		name: "paid_amount",
		label: "Paid Amount",
		healthStatus: "warning",
		badges: ["expr amount"],
		metadata: { agg: "sum", domain: "finance" },
	},
	{
		id: "metric-total-gmv",
		stage: "metric",
		type: "metric",
		name: "total_gmv",
		label: "Total GMV",
		description: "Total paid amount in selected window.",
		healthStatus: "warning",
		badges: ["simple", "4 impacted charts"],
		metadata: { metricType: "simple", domain: "finance" },
	},
	{
		id: "metric-order-risk-score",
		stage: "metric",
		type: "metric",
		name: "order_risk_score",
		label: "Order Risk Score",
		description: "Composite risk score derived from fulfillment and refund behavior.",
		healthStatus: "error",
		badges: ["derived", "lineage partial"],
		metadata: { metricType: "derived", domain: "risk" },
	},
	{
		id: "metric-ref-total-claim-cases",
		stage: "metric",
		type: "metric_ref",
		name: "refund_case_count",
		label: "Refund Case Count",
		healthStatus: "warning",
		badges: ["metric_ref"],
		metadata: { branch: "risk", domain: "risk" },
	},
	{
		id: "chart-gmv-dashboard",
		stage: "consumption",
		type: "chart",
		name: "gmv_dashboard_card",
		label: "GMV Executive Dashboard",
		healthStatus: "warning",
		badges: ["chart", "exec"],
		metadata: { owner: "finance-ops", domain: "finance" },
	},
	{
		id: "alert-gmv-anomaly",
		stage: "consumption",
		type: "alert",
		name: "gmv_anomaly_alert",
		label: "GMV Anomaly Alert",
		healthStatus: "warning",
		badges: ["alert"],
		metadata: { severity: "critical", domain: "finance" },
	},
];

export const initialObservabilityEdges: ObservabilityEdge[] = [
	{ id: "edge-1", from: "source-mysql-sales", to: "table-orders", relation: "collects_from" },
	{ id: "edge-2", from: "table-orders", to: "topic-sales-order-raw", relation: "collects_from" },
	{ id: "edge-3", from: "topic-sales-order-raw", to: "factor-order-amount", relation: "maps_to" },
	{ id: "edge-4", from: "pipeline-sync-sales-order", to: "topic-sales-order-raw", relation: "reads_from" },
	{ id: "edge-5", from: "pipeline-sync-sales-order", to: "topic-sales-order-standard", relation: "writes_to" },
	{ id: "edge-6", from: "factor-order-amount", to: "factor-paid-amount", relation: "maps_to", isInferred: true },
	{ id: "edge-7", from: "topic-sales-order-standard", to: "semantic-orders-finance", relation: "maps_to" },
	{ id: "edge-8", from: "semantic-orders-finance", to: "measure-paid-amount", relation: "defines" },
	{ id: "edge-9", from: "measure-paid-amount", to: "metric-total-gmv", relation: "uses" },
	{ id: "edge-10", from: "metric-order-risk-score", to: "metric-ref-total-claim-cases", relation: "derived_from" },
	{ id: "edge-11", from: "metric-total-gmv", to: "chart-gmv-dashboard", relation: "uses" },
	{ id: "edge-12", from: "metric-total-gmv", to: "alert-gmv-anomaly", relation: "uses" },
];

export const initialObservabilityEvents: ObservabilityEvent[] = [
	{
		id: "obs-event-1",
		timestamp: "2026-03-30 09:42:11",
		severity: "critical",
		eventType: "pipeline_failure",
		targetId: "pipeline-sync-sales-order",
		targetLabel: "Sync Sales Order To DW",
		message: "Pipeline failed twice due to duplicate key conflicts on curated order topic.",
		impactedMetrics: ["total_gmv", "order_risk_score"],
		healthStatus: "error",
	},
	{
		id: "obs-event-2",
		timestamp: "2026-03-30 09:15:00",
		severity: "warning",
		eventType: "freshness_breach",
		targetId: "topic-sales-order-raw",
		targetLabel: "sales_order_raw",
		message: "Raw topic freshness exceeded SLA by 18 minutes.",
		impactedMetrics: ["total_gmv"],
		healthStatus: "warning",
	},
	{
		id: "obs-event-3",
		timestamp: "2026-03-30 08:58:34",
		severity: "warning",
		eventType: "metric_partial_lineage",
		targetId: "metric-order-risk-score",
		targetLabel: "Order Risk Score",
		message: "Derived metric lineage is partial because one metric_ref branch has missing semantic resolution.",
		impactedMetrics: ["order_risk_score"],
		healthStatus: "warning",
	},
];

export const initialObservabilityImpact: ObservabilityImpactItem[] = [
	{
		id: "impact-1",
		type: "metric",
		name: "total_gmv",
		severity: "critical",
		healthStatus: "warning",
		shortestPath: ["sync_sales_order_to_dw", "sales_order", "orders_finance", "total_gmv"],
	},
	{
		id: "impact-2",
		type: "metric",
		name: "order_risk_score",
		severity: "critical",
		healthStatus: "error",
		shortestPath: ["sync_sales_order_to_dw", "sales_order", "orders_finance", "order_risk_score"],
	},
	{
		id: "impact-3",
		type: "consumption",
		name: "GMV Executive Dashboard",
		severity: "warning",
		healthStatus: "warning",
		shortestPath: [
			"sync_sales_order_to_dw",
			"sales_order",
			"orders_finance",
			"total_gmv",
			"GMV Executive Dashboard",
		],
	},
	{
		id: "impact-4",
		type: "consumption",
		name: "GMV Anomaly Alert",
		severity: "warning",
		healthStatus: "warning",
		shortestPath: ["sync_sales_order_to_dw", "sales_order", "orders_finance", "total_gmv", "GMV Anomaly Alert"],
	},
];

export const initialChat = [
	{
		id: "msg-1",
		role: "assistant",
		content: "Hello, I'm the Watchmen Agent. There are 2 pending perception events awaiting your review.",
		suggestedActions: [{ label: "View Pending Events", action: "VIEW_PENDING" }],
	},
];

export const initialWorkflow = [
	{
		id: "wf-1",
		module: "ingest",
		title: "Source connected",
		description: "Sales Production DB (MySQL)",
		status: "completed",
	},
	{
		id: "wf-2",
		module: "model",
		title: "Topic defined",
		description: "sales_order_raw (Raw Topic)",
		status: "completed",
	},
	{
		id: "wf-3",
		module: "transform",
		title: "Sync Pipeline",
		description: "sync_sales_order_to_dw",
		status: "completed",
	},
	{
		id: "wf-4",
		module: "govern",
		title: "Quality Monitoring",
		description: "Active — 2 drifts detected",
		status: "in_progress",
	},
];

export const createInitialState = (): AppState => ({
	main: "observe",
	chatHistory: initialChat as any,
	activeWorkflow: initialWorkflow as any,
	isChatting: false,
	dataSources: initialDataSources,
	topics: initialTopics,
	pipelines: initialPipelines,
	perceiveScenarios: [...initialPerceiveScenarios],
	selectedScenarioId: "perceive-1",
	agentLogs: [...initialAgentLogs],
	eventFilter: "all",
	observabilityView: "overview",
	observabilityDirection: "downstream",
	observabilityFocusNodeId: "pipeline-sync-sales-order",
	observabilitySelectedNodeId: "pipeline-sync-sales-order",
	observabilityNodes: [...initialObservabilityNodes],
	observabilityEdges: [...initialObservabilityEdges],
	observabilityEvents: [...initialObservabilityEvents],
	observabilityImpact: [...initialObservabilityImpact],
	observabilityKpis: [...initialObservabilityKpis],
	observabilityStageHealth: [...initialObservabilityStageHealth],
	observabilityCatalogFilter: { search: "", stage: "", health: "", domain: "", sort: "name", page: 1, pageSize: 10 },
	observabilityGraphZoom: "stage",
	observabilityGraphDomain: "",
	observabilityEventFilter: { severity: "", eventType: "", page: 1, pageSize: 10 },
	observabilityGlobalSearch: "",
	governRules: [...initialGovernRules],
	maskingPolicies: [...initialMaskingPolicies],
});
