import {
	AppState,
	MainNavKey,
	DataSource,
	Topic,
	Pipeline,
	PerceiveScenario,
	AgentLog,
	ObservabilityEdge,
	ObservabilityEvent,
	ObservabilityImpactItem,
	ObservabilityKpi,
	ObservabilityNode,
	ObservabilityStageHealth,
	GovernRule,
	MaskingPolicy,
	OntologyObject,
	OntologyLink,
	GlossaryTerm,
} from "./models";

export type MainNavItem = { key: MainNavKey; label: string; icon: string };

export type MainNavGroup = { label: string; items: MainNavItem[] };

// Sidebar sections follow the ontology construction loop:
// Ontology (the kernel) <- Agent proposals <- Build stages <- Runtime checks <- Trust guard.
export const mainNavGroups: MainNavGroup[] = [
	{ label: "", items: [{ key: "ontology", label: "Ontology", icon: "◆" }] },
	{
		label: "Agent",
		items: [
			{ key: "perceive", label: "Perceive", icon: "◎" },
			{ key: "feedback", label: "Feedback", icon: "↺" },
		],
	},
	{
		label: "Build",
		items: [
			{ key: "ingest", label: "Ingest", icon: "⬡" },
			{ key: "model", label: "Model", icon: "◫" },
			{ key: "transform", label: "Transform", icon: "⟳" },
		],
	},
	{ label: "Runtime", items: [{ key: "observe", label: "Observe", icon: "◌" }] },
	{ label: "Trust", items: [{ key: "govern", label: "Govern", icon: "⛨" }] },
	{ label: "System", items: [{ key: "settings", label: "Settings", icon: "⚙" }] },
];

export const mainNav: MainNavItem[] = mainNavGroups.flatMap((group) => group.items);

export const initialDataSources: DataSource[] = [
	{
		dataSourceId: "ds-1",
		dataSourceCode: "mysql_sales",
		dataSourceType: "mysql",
		host: "192.168.1.10",
		name: "Sales Production DB",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:30:00",
		recordCount: 45200000,
		domain: "commerce",
	},
	{
		dataSourceId: "ds-2",
		dataSourceCode: "pg_analytics",
		dataSourceType: "postgresql",
		host: "192.168.1.20",
		name: "Analytics DW",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:45:00",
		recordCount: 128000000,
		domain: "commerce",
	},
	{
		dataSourceId: "ds-3",
		dataSourceCode: "mongo_users",
		dataSourceType: "mongodb",
		host: "192.168.2.15",
		name: "User Profile Store",
		healthStatus: "warning",
		lastSync: "2026-05-26 07:52:00",
		recordCount: 8900000,
		domain: "user",
	},
	{
		dataSourceId: "ds-4",
		dataSourceCode: "oracle_finance",
		dataSourceType: "oracle",
		host: "192.168.3.5",
		name: "Finance Ledger DB",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:00:00",
		recordCount: 21000000,
		domain: "finance",
	},
	{
		dataSourceId: "ds-5",
		dataSourceCode: "s3_event_logs",
		dataSourceType: "s3",
		name: "Event Log Archive",
		url: "s3://data-lake/events/",
		healthStatus: "error",
		lastSync: "2026-05-25 23:15:00",
		recordCount: 345000000,
		domain: "platform",
	},
	{
		dataSourceId: "ds-6",
		dataSourceCode: "mssql_risk",
		dataSourceType: "mssql",
		host: "192.168.4.10",
		name: "Risk Assessment DB",
		healthStatus: "healthy",
		lastSync: "2026-05-26 08:15:00",
		recordCount: 5600000,
		domain: "risk",
	},
	{
		dataSourceId: "ds-7",
		dataSourceCode: "snowflake_dw",
		dataSourceType: "snowflake",
		name: "Snowflake Data Warehouse",
		url: "snowflake://acct/data_mart",
		healthStatus: "healthy",
		lastSync: "2026-05-26 09:00:00",
		recordCount: 890000000,
		domain: "commerce",
	},
];

export const initialTopics: Topic[] = [
	{
		topicId: "t-1",
		name: "sales_order_raw",
		type: "raw",
		kind: "business",
		dataSourceId: "ds-1",
		factors: [
			{ factorId: "f-1", name: "order_id", label: "Order ID", type: "text" },
			{ factorId: "f-2", name: "amount", label: "Amount", type: "number" },
			{ factorId: "f-3", name: "customer_id", label: "Customer ID", type: "text" },
		],
		description: "Raw sales order data from MySQL",
		domain: "commerce",
		recordCount: 45200000,
		healthStatus: "warning",
	},
	{
		topicId: "t-2",
		name: "user_profile",
		type: "raw",
		kind: "business",
		dataSourceId: "ds-3",
		factors: [
			{ factorId: "f-4", name: "user_id", label: "User ID", type: "text" },
			{ factorId: "f-5", name: "email", label: "Email", type: "text" },
			{ factorId: "f-6", name: "phone", label: "Phone", type: "text" },
		],
		description: "User profile data from MongoDB",
		domain: "user",
		recordCount: 8900000,
		healthStatus: "warning",
	},
	{
		topicId: "t-3",
		name: "finance_transactions",
		type: "raw",
		kind: "business",
		dataSourceId: "ds-4",
		factors: [
			{ factorId: "f-7", name: "txn_id", label: "Transaction ID", type: "text" },
			{ factorId: "f-8", name: "paid_amount", label: "Paid Amount", type: "number" },
			{ factorId: "f-9", name: "payment_method", label: "Payment Method", type: "text" },
		],
		description: "Financial transaction records from Oracle",
		domain: "finance",
		recordCount: 21000000,
		healthStatus: "healthy",
	},
	{
		topicId: "t-4",
		name: "sales_order_curated",
		type: "meta",
		kind: "business",
		factors: [
			{ factorId: "f-10", name: "order_id", label: "Order ID", type: "text" },
			{ factorId: "f-11", name: "paid_amount", label: "Paid Amount", type: "number" },
			{ factorId: "f-12", name: "customer_id", label: "Customer ID", type: "text" },
			{ factorId: "f-13", name: "order_status", label: "Order Status", type: "text" },
			{ factorId: "f-14", name: "created_at", label: "Created At", type: "datetime" },
		],
		description: "Curated order fact topic with enriched fields",
		domain: "commerce",
		recordCount: 44800000,
		healthStatus: "warning",
	},
	{
		topicId: "t-5",
		name: "daily_gmv_aggregate",
		type: "aggregate",
		kind: "business",
		factors: [
			{ factorId: "f-15", name: "report_date", label: "Report Date", type: "date" },
			{ factorId: "f-16", name: "total_gmv", label: "Total GMV", type: "number" },
			{ factorId: "f-17", name: "order_count", label: "Order Count", type: "number" },
		],
		description: "Daily GMV aggregate from curated orders",
		domain: "finance",
		recordCount: 365,
		healthStatus: "warning",
	},
	{
		topicId: "t-6",
		name: "risk_scores",
		type: "ratio",
		kind: "business",
		dataSourceId: "ds-6",
		factors: [
			{ factorId: "f-18", name: "order_id", label: "Order ID", type: "text" },
			{ factorId: "f-19", name: "risk_score", label: "Risk Score", type: "number" },
			{ factorId: "f-20", name: "fraud_flag", label: "Fraud Flag", type: "boolean" },
		],
		description: "Risk assessment scores for orders",
		domain: "risk",
		recordCount: 5600000,
		healthStatus: "error",
	},
	{
		topicId: "t-7",
		name: "event_clickstream",
		type: "raw",
		kind: "system",
		dataSourceId: "ds-5",
		factors: [
			{ factorId: "f-21", name: "event_id", label: "Event ID", type: "text" },
			{ factorId: "f-22", name: "event_type", label: "Event Type", type: "text" },
			{ factorId: "f-23", name: "page_url", label: "Page URL", type: "text" },
		],
		description: "Raw clickstream events from S3 archive",
		domain: "platform",
		recordCount: 345000000,
		healthStatus: "error",
	},
];

export const initialPipelines: Pipeline[] = [
	{
		pipelineId: "p-1",
		topicId: "t-1",
		name: "sync_sales_order_to_dw",
		type: "insert-or-merge",
		enabled: true,
		validated: true,
		healthStatus: "error",
		lastRun: "2026-05-26 09:42:11",
	},
	{
		pipelineId: "p-2",
		topicId: "t-2",
		name: "sync_user_profile",
		type: "merge",
		enabled: true,
		validated: true,
		healthStatus: "warning",
		lastRun: "2026-05-26 09:30:00",
	},
	{
		pipelineId: "p-3",
		topicId: "t-3",
		name: "finance_txn_to_curated",
		type: "insert",
		enabled: true,
		validated: true,
		healthStatus: "healthy",
		lastRun: "2026-05-26 09:45:00",
	},
	{
		pipelineId: "p-4",
		topicId: "t-4",
		name: "curate_sales_order",
		type: "insert-or-merge",
		enabled: true,
		validated: false,
		healthStatus: "warning",
		lastRun: "2026-05-26 09:35:00",
	},
	{
		pipelineId: "p-5",
		topicId: "t-5",
		name: "compute_daily_gmv",
		type: "insert",
		enabled: true,
		validated: true,
		healthStatus: "healthy",
		lastRun: "2026-05-26 06:00:00",
	},
	{
		pipelineId: "p-6",
		topicId: "t-6",
		name: "refresh_risk_scores",
		type: "merge",
		enabled: true,
		validated: true,
		healthStatus: "error",
		lastRun: "2026-05-26 08:15:00",
	},
	{
		pipelineId: "p-7",
		topicId: "t-7",
		name: "archive_clickstream",
		type: "insert",
		enabled: false,
		validated: true,
		healthStatus: "healthy",
		lastRun: "2026-05-25 23:59:00",
	},
];

export const initialGovernRules: GovernRule[] = [
	{
		ruleId: "gr-1",
		name: "Order Amount > 0",
		description: "Validates that every order has a positive amount value",
		category: "validity",
		severity: "critical",
		targetTopic: "sales_order_raw",
		targetFactor: "amount",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 99.97,
		params: { threshold: "1200", drift_window: "7d" },
	},
	{
		ruleId: "gr-2",
		name: "Customer ID Format",
		description: "Ensures customer_id matches the configured pattern",
		category: "validity",
		severity: "critical",
		targetTopic: "sales_order_raw",
		targetFactor: "customer_id",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 97.7,
		params: { regex: "^CUST-\\d{8}$", action: "reject" },
	},
	{
		ruleId: "gr-3",
		name: "Duplicate Order Detection",
		description: "Detects duplicate order_id within 24-hour window",
		category: "uniqueness",
		severity: "warning",
		targetTopic: "sales_order_raw",
		targetFactor: "order_id",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 99.99,
	},
	{
		ruleId: "gr-4",
		name: "Freshness SLA - Raw Order",
		description: "Raw order topic must sync within 10 minutes",
		category: "freshness",
		severity: "warning",
		targetTopic: "sales_order_raw",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 94.2,
	},
	{
		ruleId: "gr-5",
		name: "Email Format Check",
		description: "Validates email field format for user profiles",
		category: "validity",
		severity: "warning",
		targetTopic: "user_profile",
		targetFactor: "email",
		enabled: true,
		lastChecked: "2026-05-26 09:30:00",
		passRate: 99.5,
	},
	{
		ruleId: "gr-6",
		name: "Txn Amount Non-Null",
		description: "Finance transaction paid_amount must never be null",
		category: "completeness",
		severity: "critical",
		targetTopic: "finance_transactions",
		targetFactor: "paid_amount",
		enabled: true,
		lastChecked: "2026-05-26 09:45:00",
		passRate: 99.99,
	},
	{
		ruleId: "gr-7",
		name: "Risk Score Range",
		description: "Risk scores must be between 0 and 100",
		category: "validity",
		severity: "critical",
		targetTopic: "risk_scores",
		targetFactor: "risk_score",
		enabled: true,
		lastChecked: "2026-05-26 09:15:00",
		passRate: 98.1,
	},
	{
		ruleId: "gr-8",
		name: "GMV Consistency Check",
		description: "Daily GMV must reconcile with sum of individual orders",
		category: "consistency",
		severity: "warning",
		targetTopic: "daily_gmv_aggregate",
		enabled: true,
		lastChecked: "2026-05-26 06:30:00",
		passRate: 96.8,
	},
];

export const initialMaskingPolicies: MaskingPolicy[] = [
	{
		policyId: "mp-1",
		name: "Mask User Email",
		targetTopic: "user_profile",
		targetFactor: "email",
		strategy: "partial_mask",
		enabled: true,
		appliesTo: ["analyst", "viewer"],
	},
	{
		policyId: "mp-2",
		name: "Tokenize Customer ID",
		targetTopic: "sales_order_curated",
		targetFactor: "customer_id",
		strategy: "tokenize",
		enabled: true,
		appliesTo: ["analyst", "viewer", "developer"],
	},
	{
		policyId: "mp-3",
		name: "Redact Phone Number",
		targetTopic: "user_profile",
		targetFactor: "phone",
		strategy: "redact",
		enabled: true,
		appliesTo: ["viewer"],
	},
	{
		policyId: "mp-4",
		name: "Hash Payment Method",
		targetTopic: "finance_transactions",
		targetFactor: "payment_method",
		strategy: "sha256",
		enabled: false,
		appliesTo: ["viewer"],
	},
];

export const initialPerceiveScenarios: PerceiveScenario[] = [
	{
		id: "perceive-1",
		title: "Order Amount Distribution Drift",
		description:
			"Significant rightward shift detected in order amounts over the past 24 hours. Mean rose from 316 to 402, P95 from 1,380 to 1,740. Possible causes include promotional activity or anomalous order influx. Recommend reviewing alert thresholds.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-30 10:12:08",
		status: "pending",
		severity: "critical",
		confidence: 92,
		driftMetrics: [
			{ label: "P50", baseline: 219, current: 258, unit: "CNY" },
			{ label: "P95", baseline: 1380, current: 1740, unit: "CNY" },
			{ label: "Mean", baseline: 316, current: 402, unit: "CNY" },
		],
		proposedChanges: [
			{
				field: "amount_alert_threshold",
				baseline: "1200",
				current: "1600",
				impact: "high",
				targetKind: "quality_rule",
				targetLabel: "RULE gr-1 · Order Amount > 0",
				effect: { kind: "update_rule_params", ruleId: "gr-1", params: { threshold: "1600", drift_window: "14d" } },
			},
			{
				field: "drift_detection_window",
				baseline: "7d",
				current: "14d",
				impact: "medium",
				targetKind: "quality_rule",
				targetLabel: "RULE gr-1 · drift window",
			},
			{
				field: "notification_channel",
				baseline: "slack:data-alert",
				current: "slack:data-alert + email:oncall",
				impact: "low",
				targetKind: "platform_config",
				targetLabel: "PLATFORM · alert routing",
			},
		],
		affectedObjectIds: ["obj-sales-order", "obj-payment"],
		affectedAttributes: ["obj-sales-order.paid_amount", "obj-payment.paid_amount"],
		relatedRuleIds: ["gr-1", "gr-8"],
		relatedTermIds: ["gt-gmv", "gt-paid-amount"],
	},
	{
		id: "perceive-2",
		title: "Customer ID Format Anomalies",
		description:
			"Over the past 6 hours, 1,247 non-standard customer_id records detected (2.3%), far exceeding the 0.1% baseline. Likely caused by upstream data entry rule changes.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-30 08:45:32",
		status: "pending",
		severity: "warning",
		confidence: 87,
		driftMetrics: [
			{ label: "Anomaly Rate", baseline: 0.1, current: 2.3, unit: "%" },
			{ label: "Anomaly Records", baseline: 54, current: 1247, unit: "" },
			{ label: "Affected Fields", baseline: 1, current: 3, unit: "" },
		],
		proposedChanges: [
			{
				field: "customer_id_regex",
				baseline: "^CUST-\\d{8}$",
				current: "^CUST-\\d{8,12}$",
				impact: "high",
				targetKind: "quality_rule",
				targetLabel: "RULE gr-2 · Customer ID Format",
				effect: { kind: "update_rule_params", ruleId: "gr-2", params: { regex: "^CUST-\\d{8,12}$" } },
			},
			{
				field: "quality_rule_action",
				baseline: "reject",
				current: "quarantine",
				impact: "medium",
				targetKind: "quality_rule",
				targetLabel: "RULE gr-2 · action",
				effect: { kind: "update_rule_params", ruleId: "gr-2", params: { action: "quarantine" } },
			},
			{
				field: "glossary_definition_sync",
				baseline: "CUST-######## (8 digits)",
				current: "CUST-######## or CUST-############ (8/12 digits)",
				impact: "medium",
				targetKind: "glossary_term",
				targetLabel: "TERM Customer ID · definition conflict",
				effect: {
					kind: "update_glossary_term",
					termId: "gt-customer-id",
					definition: "Stable identifier of a customer across systems, formatted as CUST-######## or the extended CUST-############ (8/12 digits).",
					status: "draft",
				},
			},
		],
		affectedObjectIds: ["obj-sales-order", "obj-customer"],
		affectedAttributes: ["obj-sales-order.customer_id", "obj-customer.user_id"],
		relatedRuleIds: ["gr-2", "gr-3"],
		relatedPolicyIds: ["mp-2"],
		relatedTermIds: ["gt-customer-id"],
	},
	{
		id: "perceive-3",
		title: "New Field Suggestion: payment_method",
		description:
			"AI detected a new payment_method field in the source system over the past week (coverage 98.7%). Recommend syncing it to the Topic to improve data completeness.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-29 22:10:15",
		status: "approved",
		severity: "info",
		confidence: 96,
		driftMetrics: [
			{ label: "Field Coverage", baseline: 0, current: 98.7, unit: "%" },
			{ label: "Daily Records", baseline: 0, current: 15234, unit: "" },
			{ label: "Unique Values", baseline: 0, current: 5, unit: "" },
		],
		proposedChanges: [
			{
				field: "add_factor",
				baseline: "—",
				current: "payment_method (text)",
				impact: "medium",
				targetKind: "ontology_attribute",
				targetLabel: "OBJECT Sales Order · attribute payment_method",
				effect: {
					kind: "add_attribute",
					objectId: "obj-sales-order",
					attribute: {
						name: "payment_method",
						label: "Payment Method",
						type: "text",
						sourceTopic: "sales_order_curated",
						sourceFactor: "payment_method",
						glossaryTermIds: ["gt-payment-method"],
					},
				},
			},
			{
				field: "pipeline_rebuild",
				baseline: "No",
				current: "Yes",
				impact: "low",
				targetKind: "platform_config",
				targetLabel: "PLATFORM · pipeline p-1 rebuild",
			},
		],
		affectedObjectIds: ["obj-sales-order"],
		affectedAttributes: ["obj-sales-order.payment_method"],
		relatedTermIds: ["gt-payment-method"],
	},
	{
		id: "perceive-4",
		title: "Data Latency Alert Recovered",
		description:
			"Sales Production DB sync latency has recovered to <5s. The previous 45s delay caused by network jitter has resolved automatically. Alert has been auto-downgraded.",
		topicName: "sales_order_raw",
		detectedAt: "2026-03-29 18:30:00",
		status: "rejected",
		severity: "info",
		confidence: 78,
		driftMetrics: [
			{ label: "Sync Latency", baseline: 2.1, current: 3.8, unit: "s" },
			{ label: "Failure Rate", baseline: 0, current: 0.02, unit: "%" },
			{ label: "Throughput", baseline: 1240, current: 1198, unit: "rows/s" },
		],
		proposedChanges: [
			{
				field: "latency_alert_threshold",
				baseline: "30s",
				current: "60s",
				impact: "low",
				targetKind: "platform_config",
				targetLabel: "PLATFORM · latency alert threshold",
			},
		],
		affectedObjectIds: ["obj-sales-order"],
	},
	{
		id: "perceive-5",
		title: "Sensitive Field Without Masking: payment_method",
		description:
			"Governance scan found finance_transactions.payment_method exposed in plaintext: its masking policy (Hash Payment Method) is disabled while 340 viewer-role queries touched the field this week. Recommend enabling tokenization for analyst and viewer roles.",
		topicName: "finance_transactions",
		detectedAt: "2026-03-30 11:05:00",
		status: "pending",
		severity: "warning",
		confidence: 89,
		driftMetrics: [
			{ label: "Masked Rows", baseline: 0, current: 0, unit: "%" },
			{ label: "Exposed Fields", baseline: 0, current: 1, unit: "" },
			{ label: "Weekly Viewer Queries", baseline: 120, current: 340, unit: "" },
		],
		proposedChanges: [
			{
				field: "add_masking_policy",
				baseline: "mp-4 disabled (sha256)",
				current: "mp-5 tokenize (enabled)",
				impact: "high",
				targetKind: "masking_policy",
				targetLabel: "POLICY mp-5 · Tokenize Payment Method",
				effect: {
					kind: "add_masking_policy",
					policy: {
						policyId: "mp-5",
						name: "Tokenize Payment Method",
						targetTopic: "finance_transactions",
						targetFactor: "payment_method",
						strategy: "tokenize",
						enabled: true,
						appliesTo: ["analyst", "viewer"],
					},
				},
			},
		],
		affectedObjectIds: ["obj-payment"],
		affectedAttributes: ["obj-payment.payment_method"],
		relatedPolicyIds: ["mp-4"],
		relatedTermIds: ["gt-payment-method"],
	},
	{
		id: "perceive-6",
		title: "New Field Suggestion: region on user_profile",
		description:
			"AI detected a new region field in the user profile source over the past week (coverage 97.2%, 7 distinct values). Mapping it onto the Customer object enables region-level analysis without schema changes downstream.",
		topicName: "user_profile",
		detectedAt: "2026-03-30 11:40:00",
		status: "pending",
		severity: "info",
		confidence: 94,
		driftMetrics: [
			{ label: "Field Coverage", baseline: 0, current: 97.2, unit: "%" },
			{ label: "Daily Records", baseline: 0, current: 8400, unit: "" },
			{ label: "Unique Values", baseline: 0, current: 7, unit: "" },
		],
		proposedChanges: [
			{
				field: "add_factor",
				baseline: "—",
				current: "region (text)",
				impact: "medium",
				targetKind: "ontology_attribute",
				targetLabel: "OBJECT Customer · attribute region",
				effect: {
					kind: "add_attribute",
					objectId: "obj-customer",
					attribute: {
						name: "region",
						label: "Region",
						type: "text",
						sourceTopic: "user_profile",
						sourceFactor: "region",
					},
				},
			},
			{
				field: "backfill_pipeline",
				baseline: "No",
				current: "Yes",
				impact: "low",
				targetKind: "platform_config",
				targetLabel: "PLATFORM · backfill sync",
			},
		],
		affectedObjectIds: ["obj-customer"],
		affectedAttributes: ["obj-customer.region"],
	},
];

export const initialAgentLogs: AgentLog[] = [
	{
		id: "log-1",
		timestamp: "2026-03-30 10:12:08",
		action: "detected",
		scenarioId: "perceive-1",
		content: "Significant order amount distribution drift detected on sales_order_raw, P95 shifted +26.1%",
	},
	{
		id: "log-2",
		timestamp: "2026-03-30 10:12:09",
		action: "analyzed",
		scenarioId: "perceive-1",
		content: "Analysis: likely caused by promotional activity or anomalous order influx, confidence 92%",
	},
	{
		id: "log-3",
		timestamp: "2026-03-30 10:12:10",
		action: "suggested",
		scenarioId: "perceive-1",
		content: "Suggestion: raise alert threshold 1200→1600, extend detection window 7d→14d",
	},
	{
		id: "log-4",
		timestamp: "2026-03-30 08:45:32",
		action: "detected",
		scenarioId: "perceive-2",
		content: "customer_id format anomaly rate surged from 0.1% to 2.3%",
	},
	{
		id: "log-5",
		timestamp: "2026-03-30 08:45:33",
		action: "analyzed",
		scenarioId: "perceive-2",
		content: "Correlation: anomalies concentrated in 3 upstream write channels",
	},
	{
		id: "log-6",
		timestamp: "2026-03-30 08:45:34",
		action: "suggested",
		scenarioId: "perceive-2",
		content: "Suggestion: relax regex matching rules, change quality_rule_action from reject to quarantine",
	},
	{
		id: "log-7",
		timestamp: "2026-03-29 22:10:15",
		action: "detected",
		scenarioId: "perceive-3",
		content: "New payment_method field detected in source system, coverage 98.7%",
	},
	{
		id: "log-8",
		timestamp: "2026-03-29 22:10:16",
		action: "suggested",
		scenarioId: "perceive-3",
		content: "Suggestion: sync this field and rebuild pipeline",
	},
	{
		id: "log-9",
		timestamp: "2026-03-29 18:30:00",
		action: "info",
		scenarioId: "perceive-4",
		content: "Data sync latency recovered, alert auto-downgraded",
	},
	{
		id: "log-10",
		timestamp: "2026-03-30 11:05:00",
		action: "detected",
		scenarioId: "perceive-5",
		content: "finance_transactions.payment_method exposed without active masking (mp-4 disabled), 340 viewer queries this week",
	},
	{
		id: "log-11",
		timestamp: "2026-03-30 11:05:01",
		action: "suggested",
		scenarioId: "perceive-5",
		content: "Suggestion: add masking policy mp-5 (tokenize) for analyst and viewer roles",
	},
	{
		id: "log-12",
		timestamp: "2026-03-30 11:40:00",
		action: "detected",
		scenarioId: "perceive-6",
		content: "New region field detected on user_profile, coverage 97.2% with 7 distinct values",
	},
	{
		id: "log-13",
		timestamp: "2026-03-30 11:40:01",
		action: "suggested",
		scenarioId: "perceive-6",
		content: "Suggestion: map region onto the Customer object as a new attribute",
	},
];

export const initialObservabilityKpis: ObservabilityKpi[] = [
	{
		label: "Total Assets",
		value: "3,482",
		sub: "Topics, pipelines, semantics, metrics and consumption assets",
		tone: "blue",
	},
	{ label: "Healthy", value: "3,106", sub: "Assets within freshness and execution SLA", tone: "green" },
	{ label: "Warnings", value: "274", sub: "Delayed, partial or drifted dependencies", tone: "orange" },
	{ label: "Errors", value: "102", sub: "Blocking failures with active downstream impact", tone: "gray" },
];

export const initialObservabilityStageHealth: ObservabilityStageHealth[] = [
	{ stage: "ingest", healthy: 186, warning: 21, error: 5 },
	{ stage: "raw", healthy: 742, warning: 64, error: 17 },
	{ stage: "pipeline", healthy: 268, warning: 33, error: 11 },
	{ stage: "topic", healthy: 911, warning: 72, error: 14 },
	{ stage: "semantic", healthy: 204, warning: 27, error: 8 },
	{ stage: "metric", healthy: 662, warning: 48, error: 29 },
	{ stage: "consumption", healthy: 133, warning: 9, error: 18 },
];

export const initialObservabilityNodes: ObservabilityNode[] = [
	{
		id: "source-mysql-sales",
		stage: "ingest",
		type: "source_system",
		name: "mysql_sales",
		label: "Sales Production DB",
		description: "Primary OLTP source for order transactions.",
		healthStatus: "healthy",
		badges: ["mysql", "low-latency"],
		metadata: { owner: "commerce-platform", region: "cn-shanghai", domain: "commerce" },
	},
	{
		id: "table-orders",
		stage: "ingest",
		type: "source_table",
		name: "sales_order",
		label: "sales_order",
		description: "Source order header table.",
		healthStatus: "warning",
		badges: ["freshness +18m"],
		metadata: { database: "sales_prod", schema: "public", domain: "commerce" },
	},
	{
		id: "topic-sales-order-raw",
		stage: "raw",
		type: "raw_topic",
		name: "sales_order_raw",
		label: "sales_order_raw",
		description: "Raw sales order landing topic.",
		healthStatus: "warning",
		badges: ["stale", "raw"],
		metadata: { records24h: 1523400, freshnessMinutes: 18, domain: "commerce" },
	},
	{
		id: "factor-order-amount",
		stage: "raw",
		type: "raw_factor",
		name: "amount",
		label: "Order Amount",
		healthStatus: "warning",
		badges: ["drift +27%"],
		metadata: { type: "number", domain: "commerce" },
	},
	{
		id: "pipeline-sync-sales-order",
		stage: "pipeline",
		type: "pipeline",
		name: "sync_sales_order_to_dw",
		label: "Sync Sales Order To DW",
		description: "Transforms raw order events into curated order facts.",
		healthStatus: "error",
		badges: ["2 failed runs", "retrying"],
		metadata: { enabled: true, validated: true, lastFailure: "2026-03-30 09:42:11", domain: "commerce" },
	},
	{
		id: "topic-sales-order-standard",
		stage: "topic",
		type: "topic",
		name: "sales_order",
		label: "sales_order",
		description: "Curated order fact topic.",
		healthStatus: "warning",
		badges: ["downstream impacted"],
		metadata: { factors: 14, domain: "commerce" },
	},
	{
		id: "factor-paid-amount",
		stage: "topic",
		type: "factor",
		name: "paid_amount",
		label: "Paid Amount",
		healthStatus: "warning",
		badges: ["mapped"],
		metadata: { sourceFactor: "amount", domain: "commerce" },
	},
	{
		id: "semantic-orders-finance",
		stage: "semantic",
		type: "semantic_model",
		name: "orders_finance",
		label: "Orders Finance",
		description: "Semantic layer for commerce finance metrics.",
		healthStatus: "warning",
		badges: ["topic-linked"],
		metadata: { topic: "sales_order", domain: "finance" },
	},
	{
		id: "measure-paid-amount",
		stage: "semantic",
		type: "semantic_measure",
		name: "paid_amount",
		label: "Paid Amount",
		healthStatus: "warning",
		badges: ["expr amount"],
		metadata: { agg: "sum", domain: "finance" },
	},
	{
		id: "metric-total-gmv",
		stage: "metric",
		type: "metric",
		name: "total_gmv",
		label: "Total GMV",
		description: "Total paid amount in selected window.",
		healthStatus: "warning",
		badges: ["simple", "4 impacted charts"],
		metadata: { metricType: "simple", domain: "finance" },
	},
	{
		id: "metric-order-risk-score",
		stage: "metric",
		type: "metric",
		name: "order_risk_score",
		label: "Order Risk Score",
		description: "Composite risk score derived from fulfillment and refund behavior.",
		healthStatus: "error",
		badges: ["derived", "lineage partial"],
		metadata: { metricType: "derived", domain: "risk" },
	},
	{
		id: "metric-ref-total-claim-cases",
		stage: "metric",
		type: "metric_ref",
		name: "refund_case_count",
		label: "Refund Case Count",
		healthStatus: "warning",
		badges: ["metric_ref"],
		metadata: { branch: "risk", domain: "risk" },
	},
	{
		id: "chart-gmv-dashboard",
		stage: "consumption",
		type: "chart",
		name: "gmv_dashboard_card",
		label: "GMV Executive Dashboard",
		healthStatus: "warning",
		badges: ["chart", "exec"],
		metadata: { owner: "finance-ops", domain: "finance" },
	},
	{
		id: "alert-gmv-anomaly",
		stage: "consumption",
		type: "alert",
		name: "gmv_anomaly_alert",
		label: "GMV Anomaly Alert",
		healthStatus: "warning",
		badges: ["alert"],
		metadata: { severity: "critical", domain: "finance" },
	},
];

export const initialObservabilityEdges: ObservabilityEdge[] = [
	{ id: "edge-1", from: "source-mysql-sales", to: "table-orders", relation: "collects_from" },
	{ id: "edge-2", from: "table-orders", to: "topic-sales-order-raw", relation: "collects_from" },
	{ id: "edge-3", from: "topic-sales-order-raw", to: "factor-order-amount", relation: "maps_to" },
	{ id: "edge-4", from: "pipeline-sync-sales-order", to: "topic-sales-order-raw", relation: "reads_from" },
	{ id: "edge-5", from: "pipeline-sync-sales-order", to: "topic-sales-order-standard", relation: "writes_to" },
	{ id: "edge-6", from: "factor-order-amount", to: "factor-paid-amount", relation: "maps_to", isInferred: true },
	{ id: "edge-7", from: "topic-sales-order-standard", to: "semantic-orders-finance", relation: "maps_to" },
	{ id: "edge-8", from: "semantic-orders-finance", to: "measure-paid-amount", relation: "defines" },
	{ id: "edge-9", from: "measure-paid-amount", to: "metric-total-gmv", relation: "uses" },
	{ id: "edge-10", from: "metric-order-risk-score", to: "metric-ref-total-claim-cases", relation: "derived_from" },
	{ id: "edge-11", from: "metric-total-gmv", to: "chart-gmv-dashboard", relation: "uses" },
	{ id: "edge-12", from: "metric-total-gmv", to: "alert-gmv-anomaly", relation: "uses" },
];

export const initialObservabilityEvents: ObservabilityEvent[] = [
	{
		id: "obs-event-1",
		timestamp: "2026-03-30 09:42:11",
		severity: "critical",
		eventType: "pipeline_failure",
		targetId: "pipeline-sync-sales-order",
		targetLabel: "Sync Sales Order To DW",
		message: "Pipeline failed twice due to duplicate key conflicts on curated order topic.",
		impactedMetrics: ["total_gmv", "order_risk_score"],
		healthStatus: "error",
	},
	{
		id: "obs-event-2",
		timestamp: "2026-03-30 09:15:00",
		severity: "warning",
		eventType: "freshness_breach",
		targetId: "topic-sales-order-raw",
		targetLabel: "sales_order_raw",
		message: "Raw topic freshness exceeded SLA by 18 minutes.",
		impactedMetrics: ["total_gmv"],
		healthStatus: "warning",
	},
	{
		id: "obs-event-3",
		timestamp: "2026-03-30 08:58:34",
		severity: "warning",
		eventType: "metric_partial_lineage",
		targetId: "metric-order-risk-score",
		targetLabel: "Order Risk Score",
		message: "Derived metric lineage is partial because one metric_ref branch has missing semantic resolution.",
		impactedMetrics: ["order_risk_score"],
		healthStatus: "warning",
	},
];

export const initialObservabilityImpact: ObservabilityImpactItem[] = [
	{
		id: "impact-1",
		type: "metric",
		name: "total_gmv",
		severity: "critical",
		healthStatus: "warning",
		shortestPath: ["sync_sales_order_to_dw", "sales_order", "orders_finance", "total_gmv"],
	},
	{
		id: "impact-2",
		type: "metric",
		name: "order_risk_score",
		severity: "critical",
		healthStatus: "error",
		shortestPath: ["sync_sales_order_to_dw", "sales_order", "orders_finance", "order_risk_score"],
	},
	{
		id: "impact-3",
		type: "consumption",
		name: "GMV Executive Dashboard",
		severity: "warning",
		healthStatus: "warning",
		shortestPath: [
			"sync_sales_order_to_dw",
			"sales_order",
			"orders_finance",
			"total_gmv",
			"GMV Executive Dashboard",
		],
	},
	{
		id: "impact-4",
		type: "consumption",
		name: "GMV Anomaly Alert",
		severity: "warning",
		healthStatus: "warning",
		shortestPath: ["sync_sales_order_to_dw", "sales_order", "orders_finance", "total_gmv", "GMV Anomaly Alert"],
	},
];

// ---------------------------------------------------------------------------
// Ontology: business objects, links and glossary.
// Attributes map 1:1 onto the factors of the existing topics above; quality
// rule / masking policy ids reference initialGovernRules / initialMaskingPolicies.
// ---------------------------------------------------------------------------
export const initialOntologyObjects: OntologyObject[] = [
	{
		id: "obj-customer",
		name: "customer",
		displayName: "Customer",
		description: "Unified customer profile assembled from identity and contact attributes.",
		domain: "user",
		icon: "CU",
		color: "violet",
		sensitivity: "confidential",
		healthStatus: "warning",
		primaryTopicId: "t-2",
		sourceTopicIds: ["t-2"],
		attributes: [
			{ name: "user_id", label: "User ID", type: "text", sourceTopic: "user_profile", sourceFactor: "user_id" },
			{
				name: "email",
				label: "Email",
				type: "text",
				sourceTopic: "user_profile",
				sourceFactor: "email",
				sensitive: true,
				maskedBy: "mp-1",
				qualityRuleIds: ["gr-5"],
			},
			{
				name: "phone",
				label: "Phone",
				type: "text",
				sourceTopic: "user_profile",
				sourceFactor: "phone",
				sensitive: true,
				maskedBy: "mp-3",
			},
		],
		derivedAttributes: [
			{
				id: "da-customer-ltv",
				name: "lifetime_value",
				label: "Lifetime Value",
				description: "Sum of paid amounts across every order placed by the customer.",
				aggregate: "sum",
				path: ["lk-places", "obj-sales-order"],
				targetField: "paid_amount",
			},
			{
				id: "da-customer-order-count",
				name: "order_count",
				label: "Order Count",
				description: "Number of orders linked to the customer.",
				aggregate: "count",
				path: ["lk-places", "obj-sales-order"],
				targetField: "order_id",
			},
		],
	},
	{
		id: "obj-sales-order",
		name: "sales_order",
		displayName: "Sales Order",
		description: "Curated order fact object materialized from raw and curated order topics.",
		domain: "commerce",
		icon: "SO",
		color: "indigo",
		sensitivity: "internal",
		healthStatus: "warning",
		primaryTopicId: "t-4",
		sourceTopicIds: ["t-4", "t-1"],
		attributes: [
			{
				name: "order_id",
				label: "Order ID",
				type: "text",
				sourceTopic: "sales_order_curated",
				sourceFactor: "order_id",
				qualityRuleIds: ["gr-3"],
			},
			{
				name: "paid_amount",
				label: "Paid Amount",
				type: "number",
				sourceTopic: "sales_order_curated",
				sourceFactor: "paid_amount",
				qualityRuleIds: ["gr-1", "gr-8"],
				glossaryTermIds: ["gt-gmv", "gt-paid-amount"],
			},
			{
				name: "customer_id",
				label: "Customer ID",
				type: "text",
				sourceTopic: "sales_order_curated",
				sourceFactor: "customer_id",
				sensitive: true,
				maskedBy: "mp-2",
				qualityRuleIds: ["gr-2"],
				glossaryTermIds: ["gt-customer-id"],
			},
			{
				name: "order_status",
				label: "Order Status",
				type: "text",
				sourceTopic: "sales_order_curated",
				sourceFactor: "order_status",
			},
			{
				name: "created_at",
				label: "Created At",
				type: "datetime",
				sourceTopic: "sales_order_curated",
				sourceFactor: "created_at",
			},
			{
				name: "payment_method",
				label: "Payment Method",
				type: "text",
				sourceTopic: "sales_order_curated",
				sourceFactor: "payment_method",
				glossaryTermIds: ["gt-payment-method"],
			},
		],
		derivedAttributes: [],
	},
	{
		id: "obj-payment",
		name: "payment",
		displayName: "Payment",
		description: "Settlement transactions captured by the finance ledger.",
		domain: "finance",
		icon: "PM",
		color: "green",
		sensitivity: "confidential",
		healthStatus: "healthy",
		primaryTopicId: "t-3",
		sourceTopicIds: ["t-3"],
		attributes: [
			{ name: "txn_id", label: "Transaction ID", type: "text", sourceTopic: "finance_transactions", sourceFactor: "txn_id" },
			{
				name: "paid_amount",
				label: "Paid Amount",
				type: "number",
				sourceTopic: "finance_transactions",
				sourceFactor: "paid_amount",
				qualityRuleIds: ["gr-6"],
				glossaryTermIds: ["gt-paid-amount"],
			},
			{
				name: "payment_method",
				label: "Payment Method",
				type: "text",
				sourceTopic: "finance_transactions",
				sourceFactor: "payment_method",
				maskedBy: "mp-4",
				glossaryTermIds: ["gt-payment-method"],
			},
		],
		derivedAttributes: [],
	},
	{
		id: "obj-risk-profile",
		name: "risk_profile",
		displayName: "Risk Profile",
		description: "Per-order risk assessment scores produced by the risk engine.",
		domain: "risk",
		icon: "RP",
		color: "red",
		sensitivity: "restricted",
		healthStatus: "error",
		primaryTopicId: "t-6",
		sourceTopicIds: ["t-6"],
		attributes: [
			{ name: "order_id", label: "Order ID", type: "text", sourceTopic: "risk_scores", sourceFactor: "order_id" },
			{
				name: "risk_score",
				label: "Risk Score",
				type: "number",
				sourceTopic: "risk_scores",
				sourceFactor: "risk_score",
				qualityRuleIds: ["gr-7"],
				glossaryTermIds: ["gt-risk-score"],
			},
			{ name: "fraud_flag", label: "Fraud Flag", type: "boolean", sourceTopic: "risk_scores", sourceFactor: "fraud_flag" },
		],
		derivedAttributes: [],
	},
	{
		id: "obj-behavior-event",
		name: "behavior_event",
		displayName: "Behavior Event",
		description: "Clickstream behavior events streamed from platform archives.",
		domain: "platform",
		icon: "BE",
		color: "orange",
		sensitivity: "internal",
		healthStatus: "error",
		primaryTopicId: "t-7",
		sourceTopicIds: ["t-7"],
		attributes: [
			{ name: "event_id", label: "Event ID", type: "text", sourceTopic: "event_clickstream", sourceFactor: "event_id" },
			{ name: "event_type", label: "Event Type", type: "text", sourceTopic: "event_clickstream", sourceFactor: "event_type" },
			{ name: "page_url", label: "Page URL", type: "text", sourceTopic: "event_clickstream", sourceFactor: "page_url" },
		],
		derivedAttributes: [],
	},
];

export const initialOntologyLinks: OntologyLink[] = [
	{
		id: "lk-places",
		name: "places",
		sourceObjectId: "obj-customer",
		targetObjectId: "obj-sales-order",
		cardinality: "one-to-many",
		joinDescription: "user_id = customer_id",
		description: "A customer places many sales orders.",
	},
	{
		id: "lk-settles",
		name: "settles",
		sourceObjectId: "obj-sales-order",
		targetObjectId: "obj-payment",
		cardinality: "one-to-many",
		joinDescription: "order_id = txn_id",
		description: "An order is settled by one or more payment transactions.",
	},
	{
		id: "lk-assessed-by",
		name: "assessed_by",
		sourceObjectId: "obj-sales-order",
		targetObjectId: "obj-risk-profile",
		cardinality: "one-to-one",
		joinDescription: "order_id = order_id",
		description: "Every order carries at most one risk assessment.",
	},
	{
		id: "lk-generates",
		name: "generates",
		sourceObjectId: "obj-customer",
		targetObjectId: "obj-behavior-event",
		cardinality: "one-to-many",
		joinDescription: "user_id = user_id",
		description: "Customer activity produces behavior events.",
	},
];

export const initialGlossaryTerms: GlossaryTerm[] = [
	{
		id: "gt-gmv",
		name: "gmv",
		displayName: "GMV",
		definition: "Gross Merchandise Value — total paid amount of orders within the selected window.",
		status: "active",
		category: "Commerce Metrics",
		relatedObjectIds: ["obj-sales-order"],
		relatedAttributes: ["obj-sales-order.paid_amount"],
	},
	{
		id: "gt-paid-amount",
		name: "paid_amount",
		displayName: "Paid Amount",
		definition: "Amount actually settled by the buyer, excluding cancelled or unpaid portions.",
		status: "active",
		category: "Commerce Metrics",
		relatedObjectIds: ["obj-sales-order", "obj-payment"],
		relatedAttributes: ["obj-sales-order.paid_amount", "obj-payment.paid_amount"],
	},
	{
		id: "gt-customer-id",
		name: "customer_id",
		displayName: "Customer ID",
		definition: "Stable identifier of a customer across systems, formatted as CUST-######## .",
		status: "active",
		category: "Party Domain",
		relatedObjectIds: ["obj-customer", "obj-sales-order"],
		relatedAttributes: ["obj-customer.user_id", "obj-sales-order.customer_id"],
	},
	{
		id: "gt-risk-score",
		name: "risk_score",
		displayName: "Risk Score",
		definition: "Composite 0-100 score derived from fulfillment and refund behavior.",
		status: "draft",
		category: "Risk Domain",
		relatedObjectIds: ["obj-risk-profile"],
		relatedAttributes: ["obj-risk-profile.risk_score"],
	},
	{
		id: "gt-payment-method",
		name: "payment_method",
		displayName: "Payment Method",
		definition: "Channel used to settle the transaction (card, wallet, bank transfer, ...).",
		status: "active",
		category: "Payment Domain",
		relatedObjectIds: ["obj-payment"],
		relatedAttributes: ["obj-payment.payment_method"],
	},
	{
		id: "gt-churn",
		name: "churn",
		displayName: "Churn",
		definition: "Customer is considered churned after 90 days without behavior events.",
		status: "draft",
		category: "Party Domain",
		relatedObjectIds: ["obj-customer", "obj-behavior-event"],
		relatedAttributes: [],
	},
];

export const initialChat = [
	{
		id: "msg-1",
		role: "assistant",
		content: "Hello, I'm the Watchmen Agent. There are 4 pending perception events awaiting your review.",
		suggestedActions: [
			{ label: "View Pending Events", action: "VIEW_PENDING" },
			{ label: "Explore Ontology", action: "OPEN_ONTOLOGY" },
		],
	},
];

export const initialWorkflow = [
	{
		id: "wf-1",
		module: "ingest",
		title: "Source connected",
		description: "Sales Production DB (MySQL)",
		status: "completed",
	},
	{
		id: "wf-2",
		module: "model",
		title: "Topic defined",
		description: "sales_order_raw (Raw Topic)",
		status: "completed",
	},
	{
		id: "wf-3",
		module: "transform",
		title: "Sync Pipeline",
		description: "sync_sales_order_to_dw",
		status: "completed",
	},
	{
		id: "wf-4",
		module: "govern",
		title: "Quality Monitoring",
		description: "Active — 2 drifts detected",
		status: "in_progress",
	},
];

export const createInitialState = (): AppState => ({
	main: "ontology",
	chatHistory: initialChat as any,
	activeWorkflow: initialWorkflow as any,
	isChatting: false,
	dataSources: initialDataSources,
	topics: initialTopics,
	pipelines: initialPipelines,
	perceiveScenarios: [...initialPerceiveScenarios],
	selectedScenarioId: "perceive-1",
	agentLogs: [...initialAgentLogs],
	eventFilter: "all",
	ontologyObjects: [...initialOntologyObjects],
	ontologyLinks: [...initialOntologyLinks],
	glossaryTerms: [...initialGlossaryTerms],
	ontologyView: "overview",
	ontologySelectedObjectId: null,
	ontologyCatalogFilter: { search: "", domain: "", sensitivity: "" },
	observabilityView: "overview",
	observabilityDirection: "downstream",
	observabilityFocusNodeId: "pipeline-sync-sales-order",
	observabilitySelectedNodeId: "pipeline-sync-sales-order",
	observabilityNodes: [...initialObservabilityNodes],
	observabilityEdges: [...initialObservabilityEdges],
	observabilityEvents: [...initialObservabilityEvents],
	observabilityImpact: [...initialObservabilityImpact],
	observabilityKpis: [...initialObservabilityKpis],
	observabilityStageHealth: [...initialObservabilityStageHealth],
	observabilityCatalogFilter: { search: "", stage: "", health: "", domain: "", sort: "name", page: 1, pageSize: 10 },
	observabilityGraphZoom: "stage",
	observabilityGraphDomain: "",
	observabilityEventFilter: { severity: "", eventType: "", page: 1, pageSize: 10 },
	observabilityGlobalSearch: "",
	governRules: [...initialGovernRules],
	maskingPolicies: [...initialMaskingPolicies],
});
