[tool.poetry]
name = "watchmen-reactor-service"
version = "16.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
watchmen-meta-service = { path = "../watchmen-meta-service", develop = true }
watchmen-storage-mysql = { path = "../watchmen-storage-mysql", develop = true, optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
mysql = ["watchmen-storage-mysql"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
