name: 'Change version action'
description: 'Github actions for change version command'
author: 'skywalkerX69 <skywalkerX69@outlook.com>'
inputs:
  version:
    description: 'Package version'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
