[tool.poetry]
name = "watchmen-reactor"
version = "16.0.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_reactor", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
cacheout = "^0.13.1"
watchmen-meta = { path = "../watchmen-meta", develop = true }
watchmen-storage-mysql = { path = "../watchmen-storage-mysql", develop = true, optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
mysql = ["watchmen-storage-mysql"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
