[tool.poetry]
name = "watchmen-function-aws"
version = "16.3.0"
description = ""
authors = ["botlikes <75356972+botlikes456@users.noreply.github.com>"]
license = "MIT"
packages = [
    { include = "watchmen_lambda", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
aws-cdk-lib = "2.0.0"
constructs = "^10.0.0"
boto3 = "1.24.11"
watchmen-pipeline-surface = "16.3.0"
watchmen-storage-mysql = "16.3.0"



[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
