name: Create release

on:
  workflow_call:
    inputs:
      tag:
        description: Tag name
        required: true
        type: string

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Release tag: [${{ inputs.tag }}]"
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: Release ${{ inputs.tag }}
          draft: false
          prerelease: false
