name: Publish cli (deprecated)
on:
  workflow_dispatch:
      image_version:
        description: 'package version'
        required: true
        type: string
jobs:
  publish_cli:
    name: Package the image and push to gitHub container registry
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.storage == 'oracle' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Cli build and push
        uses: docker/build-push-action@v2
        with:
          context: ./packages/watchmen-cli
          file: ./packages/watchmen-cli/Dockerfile
          push: true
          tags: ghcr.io/indexical-metrics-measure-advisory/watchmen-cli:${{ github.event.inputs.image_version }}