name: Manual Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string
        default: 'main'
      version:
        description: Version
        required: true
        type: string
        default: '16.0.27'
jobs:
  change-version:
    uses: ./.github/workflows/change-module-version.yml
    with:
      version: ${{ github.event.inputs.version }}
