name: Manual Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string
        default: 'main'
      version:
        description: Version
        required: true
        type: string
        default: '16.0.27'
jobs:
  prepare:
    name: Prepare jobs
    runs-on: ubuntu-latest
    outputs:
      pre_release_branch_name: ${{ steps.compute-pre-release-branch.outputs.pre_release_branch_name }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Compute target branch
        uses: ./.github/actions/compute-pre-release-branch
        id: compute-pre-release-branch
        with:
          version: ${{ github.event.inputs.version }}
      - name: Echo target branch
        run: |
          echo "Target branch: [$PRE_RELEASE_BRANCH_NAME]"
          echo "::set-output name=pre_release_branch_name::$PRE_RELEASE_BRANCH_NAME"
  change-version:
    needs: prepare
    uses: ./.github/workflows/change-module-version.yml
    with:
      ref: main
      branch: ${{ needs.prepare.outputs.pre_release_branch_name }}
      version: ${{ github.event.inputs.version }}
#  package-and-publish:
#    uses: ./.github/workflows/package-and-publish.yml
#    with:
#      branch: $PRE_RELEASE_BRANCH_NAME
#      version: ${{ github.event.inputs.version }}
