name: Manual Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string
        default: 'main'
      version:
        description: Version
        required: true
        type: string
        default: 'p-16.0.27'
jobs:
  manual_release:
    name: Package the all components
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Echo inputs
        run: |
          echo "Branch: ${{ github.event.inputs.branch}}"
          echo "Version: ${{ github.event.inputs.version}}"
      - name: Change version [Watchmen-Utilities]
        uses: ./.github/actions/change-poetry-version/
        id: change-poetry-version-utilities
        with:
          project-file: ./packages/watchmen-utilities/pyproject.toml
          target-version: ${{ github.event.inputs.version }}
      - name: Change version [Watchmen-Auth]
        uses: ./.github/actions/change-poetry-version/
        id: change-poetry-version-auth
        with:
          project-file: ./packages/watchmen-auth/pyproject.toml
          target-version: ${{ github.event.inputs.version }}
      - name: Change Version [Watchmen-Web-Client]
        uses: ./.github/actions/change-node-version/
        id: change-node-version
        with:
          package-file: ./packages/watchmen-web-client/package.json
          target-version: ${{ github.event.inputs.version }}
