name: Manual Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string
        default: 'main'
      version:
        description: Version
        required: true
        type: string
        default: '16.0.27'
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
#  prepare:
#    name: Prepare jobs
#    runs-on: ubuntu-latest
#    outputs:
#      pre_release_branch_name: ${{ steps.compute-pre-release-branch.outputs.pre_release_branch_name }}
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v3
#      - name: Compute target branch
#        uses: ./.github/actions/compute-pre-release-branch
#        id: compute-pre-release-branch
#        with:
#          version: ${{ github.event.inputs.version }}
#      - name: Echo target branch
#        run: |
#          echo "Target branch: [$PRE_RELEASE_BRANCH_NAME]"
#          echo "::set-output name=pre_release_branch_name::xyz"
#  catch-pre-release-branch:
#    runs-on: ubuntu-latest
#    needs: prepare
#    steps:
#      - run: echo ${{ needs.prepare.outputs.pre_release_branch_name }}
#  change-version:
#    needs: prepare
#    uses: ./.github/workflows/change-module-version.yml
#    with:
#      ref: main
#      branch: ${{ needs.prepare.outputs.pre_release_branch_name }}
#      version: ${{ github.event.inputs.version }}
#  package-and-publish:
#    uses: ./.github/workflows/package-and-publish.yml
#    with:
#      branch: $PRE_RELEASE_BRANCH_NAME
#      version: ${{ github.event.inputs.version }}
