name: Publish Release
on:
  release:
    types: [published]
jobs:
  publish_release:
    name: Package the all components
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Change version in config file
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - run: python change_version.py ${{ github.event.release.tag_name }}
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: package watchmen-utilities and publish to pypi
        working-directory: ./packages/watchmen-utilities
        run: |
          poetry update
          poetry build
          poetry publish -u '${{secrets.PIP_USERNAME}}' -p '${{secrets.PIP_PASSWORD}}'
      - name: package watchmen-model and publish to pypi
        working-directory: ./packages/watchmen-model
        run: |
          poetry update
          poetry build
          poetry publish -u '${{secrets.PIP_USERNAME}}' -p '${{secrets.PIP_PASSWORD}}'