name: Package and publish doll

on:
  workflow_call:
    inputs:
      branch:
        description: Pre-release branch
        required: true
        type: string
      version:
        description: Target version
        required: true
        type: string

# check out given pre-release branch
# build and publish to Pypi
jobs:
  build-and-publish:
    name: Package modules and publish
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "Pre-release branch: [${{ inputs.branch }}]"
          echo "Target version: [${{ inputs.version }}]"
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Setup poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Package [watchmen-rest-doll] and publish to Pypi
        working-directory: ./packages/watchmen-rest-doll
        run: |
          poetry build
      #          poetry publish -u '${{ secrets.PIP_USERNAME }}' -p '${{ secrets.PIP_PASSWORD }}''
