name: use custom action
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'package version'
        required: true
        type: string
      filepath:
        description: 'file path'
        required: true
        type: string
      filetype:
        description: 'file type'
        required: true
        type: string
jobs:
  publish_release:
    name: Package the all components
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: package watchmen-utilities and publish to pypi
        uses: ./.github/actions/change-version-action/
        id: change-version
        with:
          version: ${{ github.event.inputs.version }}
          filepath: /packages/watchmen-utilities
          filetype: ${{ github.event.inputs.filetyp }}
          pip_username: ${{secrets.PIP_USERNAME}}
          pip_password: ${{secrets.PIP_PASSWORD}}